// NextMav Procure — Enterprise seed data
// Comprehensive demo data for "Apex Industries Ltd." showing the full P2P lifecycle
// plus budgets, vendor compliance, templates, integrations, audit logs.

import type {
  ActivityLog,
  ApprovalWorkflow,
  Asset,
  AuditLogEntry,
  Budget,
  Branch,
  Comment,
  Contract,
  Department,
  DocumentRecord,
  GoodsReceipt,
  Integration,
  InventoryItem,
  Invoice,
  Notification,
  NotificationPreference,
  Organization,
  Payment,
  PurchaseOrder,
  PurchaseRequest,
  RequestTemplate,
  RFQ,
  SupplierActivity,
  SupplierPortalUser,
  User,
  Vendor,
  VendorDocument,
} from "./types";

export const seedOrganization: Organization = {
  id: "org_apex",
  name: "Apex Industries",
  legalName: "Apex Industries Ltd.",
  industry: "Manufacturing & Construction",
  country: "Nigeria",
  currency: "NGN",
  taxId: "TIN-NG-20194832",
  plan: "ENTERPRISE",
  branding: {
    primaryColor: "#10b981",
  },
  createdAt: "2023-03-15T09:00:00Z",
};

export const seedBranches: Branch[] = [
  {
    id: "br_hq",
    organizationId: "org_apex",
    name: "Headquarters — Lagos",
    address: "12 Adeola Odeku Street, Victoria Island",
    city: "Lagos",
    country: "Nigeria",
    timezone: "Africa/Lagos",
  },
  {
    id: "br_abuja",
    organizationId: "org_apex",
    name: "Abuja Regional Office",
    address: "Plot 788, Central Business District",
    city: "Abuja",
    country: "Nigeria",
    timezone: "Africa/Lagos",
  },
  {
    id: "br_phc",
    organizationId: "org_apex",
    name: "Port Harcourt Plant",
    address: "Trans-Amadi Industrial Layout",
    city: "Port Harcourt",
    country: "Nigeria",
    timezone: "Africa/Lagos",
  },
  {
    id: "br_accra",
    organizationId: "org_apex",
    name: "Accra Branch (Ghana)",
    address: "Osu Ringway East, Accra",
    city: "Accra",
    country: "Ghana",
    timezone: "Africa/Accra",
  },
];

export const seedDepartments: Department[] = [
  { id: "dep_eng", organizationId: "org_apex", branchId: "br_phc", name: "Engineering", budget: 480000, spent: 218500, budgetPeriod: "ANNUALLY" },
  { id: "dep_ops", organizationId: "org_apex", branchId: "br_hq", name: "Operations", budget: 360000, spent: 142800, budgetPeriod: "ANNUALLY" },
  { id: "dep_it", organizationId: "org_apex", branchId: "br_hq", name: "Information Technology", budget: 240000, spent: 89600, budgetPeriod: "ANNUALLY" },
  { id: "dep_fin", organizationId: "org_apex", branchId: "br_hq", name: "Finance", budget: 120000, spent: 41200, budgetPeriod: "ANNUALLY" },
  { id: "dep_hr", organizationId: "org_apex", branchId: "br_hq", name: "Human Resources", budget: 90000, spent: 32100, budgetPeriod: "ANNUALLY" },
  { id: "dep_mkt", organizationId: "org_apex", branchId: "br_abuja", name: "Marketing & Sales", budget: 180000, spent: 67400, budgetPeriod: "ANNUALLY" },
  { id: "dep_fac", organizationId: "org_apex", branchId: "br_phc", name: "Facilities", budget: 150000, spent: 58200, budgetPeriod: "ANNUALLY" },
  { id: "dep_qa", organizationId: "org_apex", branchId: "br_phc", name: "Quality Assurance", budget: 85000, spent: 24800, budgetPeriod: "ANNUALLY" },
];

export const seedUsers: User[] = [
  {
    id: "usr_amina",
    organizationId: "org_apex",
    branchId: "br_hq",
    departmentId: "dep_eng",
    email: "amina.okafor@apex.com",
    name: "Amina Okafor",
    role: "SUPER_ADMIN",
    jobTitle: "Chief Operating Officer",
    phone: "+234 803 555 0101",
    avatarColor: "bg-emerald-500",
    initials: "AO",
    status: "ACTIVE",
    lastLoginAt: new Date().toISOString(),
    mfaEnabled: true,
    createdAt: "2023-03-15T09:00:00Z",
  },
  {
    id: "usr_tunde",
    organizationId: "org_apex",
    branchId: "br_hq",
    departmentId: "dep_ops",
    email: "tunde.bello@apex.com",
    name: "Tunde Bello",
    role: "PROCUREMENT_MANAGER",
    jobTitle: "Head of Procurement",
    phone: "+234 803 555 0102",
    avatarColor: "bg-amber-500",
    initials: "TB",
    status: "ACTIVE",
    lastLoginAt: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    mfaEnabled: true,
    createdAt: "2023-04-02T09:00:00Z",
  },
  {
    id: "usr_fatima",
    organizationId: "org_apex",
    branchId: "br_hq",
    departmentId: "dep_fin",
    email: "fatima.sani@apex.com",
    name: "Fatima Sani",
    role: "FINANCE_OFFICER",
    jobTitle: "Senior Finance Officer",
    phone: "+234 803 555 0103",
    avatarColor: "bg-rose-500",
    initials: "FS",
    status: "ACTIVE",
    lastLoginAt: new Date(Date.now() - 5 * 3600 * 1000).toISOString(),
    mfaEnabled: true,
    createdAt: "2023-05-18T09:00:00Z",
  },
  {
    id: "usr_chidi",
    organizationId: "org_apex",
    branchId: "br_phc",
    departmentId: "dep_eng",
    email: "chidi.nwosu@apex.com",
    name: "Chidi Nwosu",
    role: "DEPARTMENT_MANAGER",
    jobTitle: "Engineering Manager",
    phone: "+234 803 555 0104",
    avatarColor: "bg-sky-500",
    initials: "CN",
    status: "ACTIVE",
    lastLoginAt: new Date(Date.now() - 1 * 3600 * 1000).toISOString(),
    mfaEnabled: false,
    createdAt: "2023-06-22T09:00:00Z",
  },
  {
    id: "usr_grace",
    organizationId: "org_apex",
    branchId: "br_hq",
    departmentId: "dep_it",
    email: "grace.adeyemi@apex.com",
    name: "Grace Adeyemi",
    role: "DEPARTMENT_MANAGER",
    jobTitle: "IT Manager",
    phone: "+234 803 555 0105",
    avatarColor: "bg-violet-500",
    initials: "GA",
    status: "ACTIVE",
    lastLoginAt: new Date(Date.now() - 8 * 3600 * 1000).toISOString(),
    mfaEnabled: true,
    createdAt: "2023-07-11T09:00:00Z",
  },
  {
    id: "usr_emeka",
    organizationId: "org_apex",
    branchId: "br_phc",
    departmentId: "dep_eng",
    email: "emeka.eze@apex.com",
    name: "Emeka Eze",
    role: "EMPLOYEE",
    jobTitle: "Site Engineer",
    phone: "+234 803 555 0106",
    avatarColor: "bg-teal-500",
    initials: "EE",
    status: "ACTIVE",
    lastLoginAt: new Date(Date.now() - 26 * 3600 * 1000).toISOString(),
    mfaEnabled: false,
    createdAt: "2023-09-04T09:00:00Z",
  },
  {
    id: "usr_ngozi",
    organizationId: "org_apex",
    branchId: "br_hq",
    departmentId: "dep_it",
    email: "ngozi.obi@apex.com",
    name: "Ngozi Obi",
    role: "EMPLOYEE",
    jobTitle: "IT Specialist",
    phone: "+234 803 555 0107",
    avatarColor: "bg-orange-500",
    initials: "NO",
    status: "ACTIVE",
    lastLoginAt: new Date(Date.now() - 3 * 3600 * 1000).toISOString(),
    mfaEnabled: false,
    createdAt: "2024-01-15T09:00:00Z",
  },
  {
    id: "usr_yusuf",
    organizationId: "org_apex",
    branchId: "br_hq",
    departmentId: "dep_ops",
    email: "yusuf.aliyu@apex.com",
    name: "Yusuf Aliyu",
    role: "EMPLOYEE",
    jobTitle: "Operations Analyst",
    phone: "+234 803 555 0108",
    avatarColor: "bg-cyan-500",
    initials: "YA",
    status: "ACTIVE",
    lastLoginAt: new Date(Date.now() - 12 * 3600 * 1000).toISOString(),
    mfaEnabled: false,
    createdAt: "2024-02-20T09:00:00Z",
  },
  {
    id: "usr_funke",
    organizationId: "org_apex",
    branchId: "br_hq",
    email: "funke.adewale@apex.com",
    name: "Funke Adewale",
    role: "AUDITOR",
    jobTitle: "Internal Auditor",
    phone: "+234 803 555 0109",
    avatarColor: "bg-slate-500",
    initials: "FA",
    status: "ACTIVE",
    lastLoginAt: new Date(Date.now() - 48 * 3600 * 1000).toISOString(),
    mfaEnabled: true,
    createdAt: "2023-08-30T09:00:00Z",
  },
  {
    id: "usr_kwame",
    organizationId: "org_apex",
    branchId: "br_accra",
    departmentId: "dep_ops",
    email: "kwame.mensah@apex.com",
    name: "Kwame Mensah",
    role: "DEPARTMENT_MANAGER",
    jobTitle: "Ghana Operations Lead",
    phone: "+233 24 555 0110",
    avatarColor: "bg-emerald-600",
    initials: "KM",
    status: "INVITED",
    mfaEnabled: false,
    createdAt: "2026-01-10T09:00:00Z",
  },
];

const now = new Date();
const iso = (offsetDays: number) =>
  new Date(now.getTime() + offsetDays * 24 * 60 * 60 * 1000).toISOString();

// ---------------------------------------------------------------------------
// Vendor Documents
// ---------------------------------------------------------------------------
const seedVendorDocuments: VendorDocument[] = [
  { id: "vd_1", vendorId: "vnd_techcore", type: "CERTIFICATE", name: "ISO 9001 Certificate", fileName: "iso-9001-2024.pdf", fileSize: "245 KB", uploadedAt: "2024-03-15T10:00:00Z", expiresAt: iso(180), status: "VALID" },
  { id: "vd_2", vendorId: "vnd_techcore", type: "TAX", name: "Tax Clearance Certificate", fileName: "tax-clearance-2024.pdf", fileSize: "180 KB", uploadedAt: "2024-03-15T10:00:00Z", expiresAt: iso(60), status: "EXPIRING" },
  { id: "vd_3", vendorId: "vnd_techcore", type: "BANK_PROOF", name: "Bank Account Proof", fileName: "bank-proof.pdf", fileSize: "92 KB", uploadedAt: "2024-03-15T10:00:00Z", status: "VALID" },
  { id: "vd_4", vendorId: "vnd_safetync", type: "CERTIFICATE", name: "HSE Compliance Certificate", fileName: "hse-cert.pdf", fileSize: "312 KB", uploadedAt: "2024-01-25T10:00:00Z", expiresAt: iso(120), status: "VALID" },
  { id: "vd_5", vendorId: "vnd_safetync", type: "INSURANCE", name: "Public Liability Insurance", fileName: "liability-insurance.pdf", fileSize: "425 KB", uploadedAt: "2024-01-25T10:00:00Z", expiresAt: iso(-15), status: "EXPIRED" },
  { id: "vd_6", vendorId: "vnd_steelworks", type: "CERTIFICATE", name: "ASTM A615 Compliance", fileName: "astm-cert.pdf", fileSize: "198 KB", uploadedAt: "2023-09-18T10:00:00Z", status: "VALID" },
  { id: "vd_7", vendorId: "vnd_steelworks", type: "INSURANCE", name: "Workers Compensation Insurance", fileName: "wc-insurance.pdf", fileSize: "356 KB", uploadedAt: "2023-09-18T10:00:00Z", expiresAt: iso(90), status: "VALID" },
  { id: "vd_8", vendorId: "vnd_powergen", type: "CERTIFICATE", name: "Perkins Authorized Dealer", fileName: "perkins-auth.pdf", fileSize: "142 KB", uploadedAt: "2024-02-14T10:00:00Z", expiresAt: iso(200), status: "VALID" },
];

export const seedVendors: Vendor[] = [
  {
    id: "vnd_techcore",
    organizationId: "org_apex",
    companyName: "TechCore Distributors Ltd.",
    contactPerson: "Ibrahim Mohammed",
    email: "sales@techcore-ng.com",
    phone: "+234 805 234 1100",
    address: "14 Computer Village, Ikeja, Lagos",
    category: "IT Equipment",
    taxNumber: "TIN-TC-193820",
    bankName: "First Bank Nigeria",
    bankAccount: "3031xxxxxx92",
    rating: 4.7,
    status: "ACTIVE",
    totalOrders: 24,
    totalValue: 184500,
    paymentTerms: "Net 30",
    preferredCurrency: "NGN",
    complianceScore: 92,
    onTimeDeliveryRate: 94,
    qualityRating: 4.6,
    documents: seedVendorDocuments.filter((d) => d.vendorId === "vnd_techcore"),
    tags: ["preferred", "it", "lagos"],
    notes: "Reliable IT equipment distributor with strong delivery performance.",
    createdAt: "2024-03-12T09:00:00Z",
  },
  {
    id: "vnd_safetync",
    organizationId: "org_apex",
    companyName: "SafetyNig Industrial Supplies",
    contactPerson: "Blessing Okon",
    email: "info@safetync.com",
    phone: "+234 805 999 2233",
    address: "78 Industrial Layout, Trans-Amadi, Port Harcourt",
    category: "Safety Equipment",
    taxNumber: "TIN-SN-445120",
    bankName: "Access Bank",
    bankAccount: "0091xxxxxx34",
    rating: 4.5,
    status: "PREFERRED",
    totalOrders: 18,
    totalValue: 96200,
    paymentTerms: "Net 30",
    preferredCurrency: "NGN",
    complianceScore: 88,
    onTimeDeliveryRate: 91,
    qualityRating: 4.5,
    documents: seedVendorDocuments.filter((d) => d.vendorId === "vnd_safetync"),
    tags: ["preferred", "safety", "ppe"],
    notes: "Specializes in safety equipment. Insurance expired — needs renewal.",
    createdAt: "2024-01-25T09:00:00Z",
  },
  {
    id: "vnd_steelworks",
    organizationId: "org_apex",
    companyName: "SteelWorks Africa Ltd.",
    contactPerson: "Olumide Adesanya",
    email: "quotes@steelworks.africa",
    phone: "+234 807 112 8890",
    address: "Plot 45, Apapa Industrial Zone, Lagos",
    category: "Construction Materials",
    taxNumber: "TIN-SW-778301",
    bankName: "Zenith Bank",
    bankAccount: "1015xxxxxx88",
    rating: 4.3,
    status: "ACTIVE",
    totalOrders: 31,
    totalValue: 412000,
    paymentTerms: "30% advance, 70% on delivery",
    preferredCurrency: "NGN",
    complianceScore: 95,
    onTimeDeliveryRate: 88,
    qualityRating: 4.4,
    documents: seedVendorDocuments.filter((d) => d.vendorId === "vnd_steelworks"),
    tags: ["construction", "steel", "lagos"],
    notes: "Largest steel supplier. Excellent quality but delivery times can vary.",
    createdAt: "2023-09-18T09:00:00Z",
  },
  {
    id: "vnd_officedirect",
    organizationId: "org_apex",
    companyName: "OfficeDirect Nigeria",
    contactPerson: "Chioma Eze",
    email: "orders@officedirect.ng",
    phone: "+234 809 445 6677",
    address: "21 Allen Avenue, Ikeja, Lagos",
    category: "Office Supplies",
    taxNumber: "TIN-OD-220914",
    bankName: "GTBank",
    bankAccount: "0123xxxxxx76",
    rating: 4.6,
    status: "ACTIVE",
    totalOrders: 42,
    totalValue: 67800,
    paymentTerms: "Net 15",
    preferredCurrency: "NGN",
    complianceScore: 90,
    onTimeDeliveryRate: 96,
    qualityRating: 4.5,
    documents: [],
    tags: ["office", "supplies"],
    notes: "Reliable office supplies vendor. Fast turnaround.",
    createdAt: "2023-05-08T09:00:00Z",
  },
  {
    id: "vnd_powergen",
    organizationId: "org_apex",
    companyName: "PowerGen Solutions",
    contactPerson: "Samuel Adeyinka",
    email: "sales@powergen.com",
    phone: "+234 802 778 1100",
    address: "5 Marina Road, Lagos Island",
    category: "Electrical & Power",
    taxNumber: "TIN-PG-556720",
    bankName: "UBA",
    bankAccount: "2155xxxxxx09",
    rating: 4.4,
    status: "ACTIVE",
    totalOrders: 16,
    totalValue: 138900,
    paymentTerms: "30% advance, 60% on delivery, 10% after commissioning",
    preferredCurrency: "NGN",
    complianceScore: 91,
    onTimeDeliveryRate: 89,
    qualityRating: 4.4,
    documents: seedVendorDocuments.filter((d) => d.vendorId === "vnd_powergen"),
    tags: ["electrical", "generators", "power"],
    notes: "Authorized Perkins dealer. Strong technical team.",
    createdAt: "2024-02-14T09:00:00Z",
  },
  {
    id: "vnd_logifleet",
    organizationId: "org_apex",
    companyName: "LogiFleet Logistics",
    contactPerson: "Hauwa Bello",
    email: "contact@logifleet.ng",
    phone: "+234 806 223 4478",
    address: "Apapa Port Complex, Lagos",
    category: "Logistics",
    taxNumber: "TIN-LF-991023",
    bankName: "Stanbic IBTC",
    bankAccount: "0009xxxxxx55",
    rating: 4.1,
    status: "ACTIVE",
    totalOrders: 9,
    totalValue: 52300,
    paymentTerms: "Net 15",
    preferredCurrency: "NGN",
    complianceScore: 78,
    onTimeDeliveryRate: 82,
    qualityRating: 4.0,
    documents: [],
    tags: ["logistics", "freight"],
    notes: "Logistics partner for port-to-site deliveries.",
    createdAt: "2024-06-30T09:00:00Z",
  },
  {
    id: "vnd_globalequip",
    organizationId: "org_apex",
    companyName: "Global Equipment Trading",
    contactPerson: "Daniel Park",
    email: "daniel@globalequip.com",
    phone: "+27 11 555 4400",
    address: "Sandton City, Johannesburg, South Africa",
    category: "Industrial Equipment",
    taxNumber: "TIN-GE-SA-22001",
    bankName: "Standard Bank",
    bankAccount: "62xxxxxx01",
    rating: 4.8,
    status: "PROSPECTIVE",
    totalOrders: 2,
    totalValue: 84000,
    paymentTerms: "Letter of Credit at sight",
    preferredCurrency: "NGN",
    complianceScore: 86,
    onTimeDeliveryRate: 100,
    qualityRating: 4.9,
    documents: [],
    tags: ["premium", "international", "south-africa"],
    notes: "Premium international supplier. Higher cost but superior quality and 24-month warranty.",
    createdAt: "2025-11-04T09:00:00Z",
  },
  {
    id: "vnd_primecement",
    organizationId: "org_apex",
    companyName: "Prime Cement Distributors",
    contactPerson: "Rasaq Olaniyan",
    email: "sales@primecement.ng",
    phone: "+234 803 447 8821",
    address: "Shagamu Industrial Road, Ogun State",
    category: "Construction Materials",
    taxNumber: "TIN-PC-664200",
    bankName: "First Bank Nigeria",
    bankAccount: "3044xxxxxx11",
    rating: 4.0,
    status: "ACTIVE",
    totalOrders: 14,
    totalValue: 92700,
    paymentTerms: "50% advance, 50% on delivery",
    preferredCurrency: "NGN",
    complianceScore: 85,
    onTimeDeliveryRate: 87,
    qualityRating: 4.0,
    documents: [],
    tags: ["construction", "cement"],
    notes: "Cement distributor for construction projects.",
    createdAt: "2024-08-22T09:00:00Z",
  },
  {
    id: "vnd_arcticair",
    organizationId: "org_apex",
    companyName: "Arctic Air HVAC Systems",
    contactPerson: "Lola Martins",
    email: "lola@arcticair.com",
    phone: "+234 809 223 5566",
    address: "34 Adeyemo Alakija, Victoria Island, Lagos",
    category: "HVAC & Cooling",
    taxNumber: "TIN-AA-337812",
    bankName: "GTBank",
    bankAccount: "0222xxxxxx83",
    rating: 3.9,
    status: "PROSPECTIVE",
    totalOrders: 0,
    totalValue: 0,
    paymentTerms: "Quarterly billing in advance",
    preferredCurrency: "NGN",
    complianceScore: 72,
    onTimeDeliveryRate: 0,
    qualityRating: 0,
    documents: [],
    tags: ["hvac", "maintenance"],
    notes: "HVAC maintenance contractor. Recently onboarded.",
    createdAt: "2026-01-15T09:00:00Z",
  },
  {
    id: "vnd_legacytools",
    organizationId: "org_apex",
    companyName: "Legacy Tools Co.",
    contactPerson: "Victor Obi",
    email: "victor@legacytools.com",
    phone: "+234 802 119 4400",
    address: "Plot 12, Emene Industrial Estate, Enugu",
    category: "Industrial Equipment",
    taxNumber: "TIN-LT-872340",
    bankName: "Access Bank",
    bankAccount: "0088xxxxxx22",
    rating: 2.4,
    status: "BLACKLISTED",
    totalOrders: 3,
    totalValue: 14500,
    paymentTerms: "Net 30",
    preferredCurrency: "NGN",
    complianceScore: 35,
    onTimeDeliveryRate: 45,
    qualityRating: 2.2,
    documents: [],
    tags: ["blacklisted"],
    notes: "BLACKLISTED — Multiple delivery failures and quality issues. Do not engage.",
    createdAt: "2024-04-10T09:00:00Z",
  },
  {
    id: "vnd_dangote_cement",
    organizationId: "org_apex",
    companyName: "Dangote Cement PLC",
    contactPerson: "Ahmed Hassan",
    email: "enterprise@dangote.com",
    phone: "+234 700 326 4268",
    address: "Dangote Industries, Ikoyi, Lagos",
    category: "Construction Materials",
    taxNumber: "TIN-DC-001001",
    bankName: "Multiple",
    bankAccount: "On file",
    rating: 4.9,
    status: "PREFERRED",
    totalOrders: 18,
    totalValue: 245000,
    paymentTerms: "Net 30",
    preferredCurrency: "NGN",
    complianceScore: 98,
    onTimeDeliveryRate: 97,
    qualityRating: 4.9,
    documents: [],
    tags: ["preferred", "construction", "cement", "enterprise"],
    notes: "Largest cement manufacturer in Africa. Strategic partner pricing.",
    createdAt: "2023-03-20T09:00:00Z",
  },
  {
    id: "vnd_jumia_business",
    organizationId: "org_apex",
    companyName: "Jumia Business",
    contactPerson: "Sandra Okwu",
    email: "business@jumia.com",
    phone: "+234 700 525 8624",
    address: "Jumia HQ, Yaba, Lagos",
    category: "Office Supplies",
    taxNumber: "TIN-JB-778200",
    bankName: "GTBank",
    bankAccount: "0188xxxxxx33",
    rating: 4.2,
    status: "ACTIVE",
    totalOrders: 22,
    totalValue: 38900,
    paymentTerms: "Net 30",
    preferredCurrency: "NGN",
    complianceScore: 84,
    onTimeDeliveryRate: 90,
    qualityRating: 4.1,
    documents: [],
    tags: ["office", "supplies"],
    notes: "Wide catalog of office and operational supplies.",
    createdAt: "2024-05-12T09:00:00Z",
  },
];

export const seedRequests: PurchaseRequest[] = [
  {
    id: "req_001",
    organizationId: "org_apex",
    requestNumber: "PR-2026-0001",
    title: "Industrial Laptops for Engineering Team",
    departmentId: "dep_eng",
    requestedById: "usr_emeka",
    status: "UNDER_REVIEW",
    priority: "HIGH",
    category: "IT Equipment",
    tags: ["engineering", "field-work"],
    businessJustification:
      "Three site engineers need rugged laptops for field inspections and real-time reporting. Current units are 4+ years old and frequently fail on site, causing reporting delays of 2-3 days per incident. The ThinkPad P16 is rated for industrial environments with MIL-STD-810H durability.",
    neededByDate: iso(14),
    totalEstimated: 8400,
    currency: "NGN",
    attachments: [
      { name: "spec-sheet-thinkpad.pdf", size: "245 KB", type: "pdf" },
      { name: "current-fleet-condition.docx", size: "180 KB", type: "doc" },
    ],
    lineItems: [
      {
        id: "li_001_1",
        itemName: "ThinkPad P16 Gen 2 (Rugged)",
        description: "16\" mobile workstation, i9, 32GB RAM, 1TB SSD, RTX A2000",
        quantity: 3,
        unit: "units",
        estimatedCost: 2800,
      },
    ],
    approvals: [
      {
        id: "ap_001_1",
        requestId: "req_001",
        stage: "DEPARTMENT_MANAGER",
        approverId: "usr_chidi",
        approverRole: "DEPARTMENT_MANAGER",
        decision: "APPROVED",
        comment: "Approved — these are critical for the Q3 site expansion. Please expedite.",
        decidedAt: iso(-3),
        createdAt: iso(-5),
        slaHours: 48,
        slaExpiresAt: iso(-3),
        isEscalated: false,
      },
      {
        id: "ap_001_2",
        requestId: "req_001",
        stage: "FINANCE",
        approverId: "usr_fatima",
        approverRole: "FINANCE_OFFICER",
        decision: "PENDING",
        createdAt: iso(-3),
        slaHours: 72,
        slaExpiresAt: iso(0),
        isEscalated: false,
      },
    ],
    comments: [
      {
        id: "cm_001_1",
        entityType: "REQUEST",
        entityId: "req_001",
        authorId: "usr_chidi",
        content: "@usr_fatima please prioritize this — site engineers are blocked. Approving on my end.",
        mentions: ["usr_fatima"],
        createdAt: iso(-3),
      },
      {
        id: "cm_001_2",
        entityType: "REQUEST",
        entityId: "req_001",
        authorId: "usr_fatima",
        content: "Reviewing now. Will confirm budget availability against Q3 IT allocation by EOD.",
        mentions: [],
        createdAt: iso(-2),
      },
    ],
    watchers: ["usr_emeka", "usr_chidi", "usr_fatima"],
    createdAt: iso(-5),
    updatedAt: iso(-3),
    submittedAt: iso(-5),
    version: 1,
  },
  {
    id: "req_002",
    organizationId: "org_apex",
    requestNumber: "PR-2026-0002",
    title: "Personal Protective Equipment (PPE) — Q3 Restock",
    departmentId: "dep_fac",
    requestedById: "usr_yusuf",
    status: "APPROVED",
    priority: "URGENT",
    category: "Safety Equipment",
    tags: ["hse", "compliance", "quarterly"],
    businessJustification:
      "PPE stock is critically low following the Plant 2 expansion. Mandatory compliance with HSE policy requires quarterly restock. Current stock will be depleted within 10 days at current usage rates. Non-compliance risks regulatory penalties.",
    neededByDate: iso(7),
    totalEstimated: 12650,
    currency: "NGN",
    attachments: [{ name: "hse-compliance-checklist.pdf", size: "320 KB", type: "pdf" }],
    lineItems: [
      { id: "li_002_1", itemName: "Safety Helmets (Class B)", description: "ANSI-certified industrial hard hats, white, with chin strap", quantity: 50, unit: "pcs", estimatedCost: 28 },
      { id: "li_002_2", itemName: "High-Visibility Vests", description: "Class 2 reflective vests, one-size-fits-all, orange", quantity: 80, unit: "pcs", estimatedCost: 18 },
      { id: "li_002_3", itemName: "Steel-Toe Safety Boots", description: "Size 7-12 mixed, oil-resistant sole, electrical hazard protection", quantity: 30, unit: "pairs", estimatedCost: 95 },
      { id: "li_002_4", itemName: "Cut-Resistant Gloves (Level 5)", description: "ANSI A5 cut-resistant, polyurethane coated, breathable", quantity: 100, unit: "pairs", estimatedCost: 12 },
    ],
    approvals: [
      {
        id: "ap_002_1",
        requestId: "req_002",
        stage: "DEPARTMENT_MANAGER",
        approverId: "usr_chidi",
        approverRole: "DEPARTMENT_MANAGER",
        decision: "APPROVED",
        comment: "Approved — HSE compliance is non-negotiable.",
        decidedAt: iso(-2),
        createdAt: iso(-4),
        slaHours: 24,
        slaExpiresAt: iso(-3),
        isEscalated: false,
      },
      {
        id: "ap_002_2",
        requestId: "req_002",
        stage: "FINANCE",
        approverId: "usr_fatima",
        approverRole: "FINANCE_OFFICER",
        decision: "APPROVED",
        comment: "Approved within Q3 HSE budget. Please proceed to RFQ.",
        decidedAt: iso(-1),
        createdAt: iso(-2),
        slaHours: 48,
        slaExpiresAt: iso(0),
        isEscalated: false,
      },
      {
        id: "ap_002_3",
        requestId: "req_002",
        stage: "PROCUREMENT",
        approverId: "usr_tunde",
        approverRole: "PROCUREMENT_MANAGER",
        decision: "APPROVED",
        comment: "Procurement will issue RFQ to 3 safety equipment vendors.",
        decidedAt: iso(-1),
        createdAt: iso(-1),
        slaHours: 24,
        slaExpiresAt: iso(0),
        isEscalated: false,
      },
    ],
    comments: [],
    watchers: ["usr_yusuf", "usr_chidi", "usr_fatima", "usr_tunde"],
    createdAt: iso(-4),
    updatedAt: iso(-1),
    submittedAt: iso(-4),
    version: 1,
  },
  {
    id: "req_003",
    organizationId: "org_apex",
    requestNumber: "PR-2026-0003",
    title: "Server Rack & Networking Equipment for New Abuja Office",
    departmentId: "dep_it",
    requestedById: "usr_ngozi",
    status: "SUBMITTED",
    priority: "MEDIUM",
    category: "IT Infrastructure",
    tags: ["networking", "abuja", "new-office"],
    businessJustification:
      "New Abuja regional office requires a complete server rack and networking setup to support 60 staff. Currently no IT infrastructure exists at the new location. This is a foundational setup required before the office can become operational.",
    neededByDate: iso(30),
    totalEstimated: 24500,
    currency: "NGN",
    attachments: [
      { name: "abuja-office-network-diagram.pdf", size: "1.2 MB", type: "pdf" },
      { name: "vendor-preliminary-quotes.xlsx", size: "45 KB", type: "xls" },
    ],
    lineItems: [
      { id: "li_003_1", itemName: "42U Server Rack (Locking)", description: "42U cabinet, 600x1000mm, glass front door, dual fans", quantity: 2, unit: "units", estimatedCost: 1200 },
      { id: "li_003_2", itemName: "Cisco Catalyst 9300 Switch", description: "48-port PoE+ enterprise switch, stackable", quantity: 3, unit: "units", estimatedCost: 4500 },
      { id: "li_003_3", itemName: "UPS 5kVA Online Double-Conversion", description: "Rack-mount UPS, 5kVA, with network management card", quantity: 2, unit: "units", estimatedCost: 3200 },
      { id: "li_003_4", itemName: "Patch Panels & Cables", description: "Cat6 patch panels, fiber, copper patch cords complete kit", quantity: 1, unit: "lot", estimatedCost: 3900 },
    ],
    approvals: [
      {
        id: "ap_003_1",
        requestId: "req_003",
        stage: "DEPARTMENT_MANAGER",
        approverId: "usr_grace",
        approverRole: "DEPARTMENT_MANAGER",
        decision: "PENDING",
        createdAt: iso(-2),
        slaHours: 48,
        slaExpiresAt: iso(0),
        isEscalated: false,
      },
    ],
    comments: [
      {
        id: "cm_003_1",
        entityType: "REQUEST",
        entityId: "req_003",
        authorId: "usr_ngozi",
        content: "Need this approved ASAP to meet the office opening deadline of March 1st.",
        mentions: [],
        createdAt: iso(-2),
      },
    ],
    watchers: ["usr_ngozi", "usr_grace"],
    createdAt: iso(-2),
    updatedAt: iso(-2),
    submittedAt: iso(-2),
    version: 1,
  },
  {
    id: "req_004",
    organizationId: "org_apex",
    requestNumber: "PR-2026-0004",
    title: "Steel Rebar — Plant 2 Construction Phase 2",
    departmentId: "dep_eng",
    requestedById: "usr_emeka",
    status: "CLOSED",
    priority: "URGENT",
    category: "Construction Materials",
    tags: ["construction", "plant-2", "phase-2"],
    businessJustification:
      "Phase 2 of Plant 2 construction requires 50 tonnes of steel rebar for foundation reinforcement. Project timeline mandates delivery by month-end. Delay would push back the entire Phase 2 completion by 3 weeks.",
    neededByDate: iso(-5),
    totalEstimated: 38500,
    currency: "NGN",
    attachments: [{ name: "phase-2-structural-drawings.pdf", size: "3.4 MB", type: "pdf" }],
    lineItems: [
      { id: "li_004_1", itemName: "Steel Rebar Grade 60 — 16mm", description: "ASTM A615 Grade 60, 16mm diameter, 12m lengths", quantity: 30, unit: "tonnes", estimatedCost: 850 },
      { id: "li_004_2", itemName: "Steel Rebar Grade 60 — 20mm", description: "ASTM A615 Grade 60, 20mm diameter, 12m lengths", quantity: 20, unit: "tonnes", estimatedCost: 920 },
    ],
    approvals: [
      {
        id: "ap_004_1",
        requestId: "req_004",
        stage: "DEPARTMENT_MANAGER",
        approverId: "usr_chidi",
        approverRole: "DEPARTMENT_MANAGER",
        decision: "APPROVED",
        comment: "Critical for project timeline.",
        decidedAt: iso(-25),
        createdAt: iso(-27),
        slaHours: 24,
        slaExpiresAt: iso(-26),
        isEscalated: false,
      },
      {
        id: "ap_004_2",
        requestId: "req_004",
        stage: "FINANCE",
        approverId: "usr_fatima",
        approverRole: "FINANCE_OFFICER",
        decision: "APPROVED",
        decidedAt: iso(-24),
        createdAt: iso(-25),
        slaHours: 48,
        slaExpiresAt: iso(-23),
        isEscalated: false,
      },
      {
        id: "ap_004_3",
        requestId: "req_004",
        stage: "PROCUREMENT",
        approverId: "usr_tunde",
        approverRole: "PROCUREMENT_MANAGER",
        decision: "APPROVED",
        comment: "PO issued to SteelWorks Africa.",
        decidedAt: iso(-23),
        createdAt: iso(-24),
        slaHours: 24,
        slaExpiresAt: iso(-23),
        isEscalated: false,
      },
    ],
    comments: [],
    watchers: ["usr_emeka", "usr_chidi", "usr_tunde"],
    createdAt: iso(-27),
    updatedAt: iso(-8),
    submittedAt: iso(-27),
    completedAt: iso(-8),
    version: 1,
  },
  {
    id: "req_005",
    organizationId: "org_apex",
    requestNumber: "PR-2026-0005",
    title: "Marketing Team Laptops — Q1 Refresh",
    departmentId: "dep_mkt",
    requestedById: "usr_yusuf",
    status: "REJECTED",
    priority: "LOW",
    category: "IT Equipment",
    tags: ["marketing", "non-essential"],
    businessJustification:
      "Marketing team requesting 5 new MacBook Pro units for video editing and design work.",
    neededByDate: iso(45),
    totalEstimated: 12500,
    currency: "NGN",
    attachments: [],
    lineItems: [
      { id: "li_005_1", itemName: "MacBook Pro 14\" M3 Pro", description: "14-inch, M3 Pro chip, 18GB unified memory, 512GB SSD", quantity: 5, unit: "units", estimatedCost: 2500 },
    ],
    approvals: [
      {
        id: "ap_005_1",
        requestId: "req_005",
        stage: "FINANCE",
        approverId: "usr_fatima",
        approverRole: "FINANCE_OFFICER",
        decision: "REJECTED",
        comment: "Rejected — current FY IT budget exhausted. Recommend revisiting in Q2 2027 with formal business case showing ROI.",
        decidedAt: iso(-6),
        createdAt: iso(-8),
        slaHours: 72,
        slaExpiresAt: iso(-5),
        isEscalated: false,
      },
    ],
    comments: [
      {
        id: "cm_005_1",
        entityType: "REQUEST",
        entityId: "req_005",
        authorId: "usr_yusuf",
        content: "Understood. Will resubmit with detailed ROI analysis next quarter.",
        mentions: ["usr_fatima"],
        createdAt: iso(-6),
      },
    ],
    watchers: ["usr_yusuf", "usr_fatima"],
    createdAt: iso(-8),
    updatedAt: iso(-6),
    submittedAt: iso(-8),
    version: 1,
  },
  {
    id: "req_006",
    organizationId: "org_apex",
    requestNumber: "PR-2026-0006",
    title: "Backup Generator — 250kVA for Plant 2",
    departmentId: "dep_fac",
    requestedById: "usr_yusuf",
    status: "UNDER_REVIEW",
    priority: "HIGH",
    category: "Power & Electrical",
    tags: ["critical", "plant-2", "infrastructure"],
    businessJustification:
      "Plant 2 has experienced 14 power outages in the last 60 days, each causing 3-6 hours of downtime and average production loss of $4,200 per incident. A 250kVA backup generator is essential to maintain production continuity and meet customer delivery commitments.",
    neededByDate: iso(21),
    totalEstimated: 42000,
    currency: "NGN",
    attachments: [
      { name: "power-outage-log-2026.xlsx", size: "78 KB", type: "xls" },
      { name: "generator-spec-requirements.pdf", size: "410 KB", type: "pdf" },
    ],
    lineItems: [
      { id: "li_006_1", itemName: "Perkins 250kVA Diesel Generator", description: "250kVA standby, sound-attenuated canopy, ATS panel, 1000L fuel tank", quantity: 1, unit: "unit", estimatedCost: 38000 },
      { id: "li_006_2", itemName: "Installation & Commissioning", description: "Site installation, electrical connection, load testing, commissioning", quantity: 1, unit: "lot", estimatedCost: 4000 },
    ],
    approvals: [
      {
        id: "ap_006_1",
        requestId: "req_006",
        stage: "DEPARTMENT_MANAGER",
        approverId: "usr_chidi",
        approverRole: "DEPARTMENT_MANAGER",
        decision: "APPROVED",
        comment: "Critical infrastructure. Plant 2 cannot sustain further outages.",
        decidedAt: iso(-2),
        createdAt: iso(-3),
        slaHours: 24,
        slaExpiresAt: iso(-2),
        isEscalated: false,
      },
      {
        id: "ap_006_2",
        requestId: "req_006",
        stage: "FINANCE",
        approverId: "usr_fatima",
        approverRole: "FINANCE_OFFICER",
        decision: "PENDING",
        createdAt: iso(-2),
        slaHours: 72,
        slaExpiresAt: iso(1),
        isEscalated: false,
      },
    ],
    comments: [
      {
        id: "cm_006_1",
        entityType: "REQUEST",
        entityId: "req_006",
        authorId: "usr_chidi",
        content: "Production loss calc: 14 outages × avg 4.5h × $930/h = $58,590 lost. ROI on this generator is under 9 months.",
        mentions: ["usr_fatima"],
        createdAt: iso(-2),
      },
    ],
    watchers: ["usr_yusuf", "usr_chidi", "usr_fatima"],
    createdAt: iso(-3),
    updatedAt: iso(-2),
    submittedAt: iso(-3),
    version: 1,
  },
  {
    id: "req_007",
    organizationId: "org_apex",
    requestNumber: "PR-2026-0007",
    title: "Office Furniture — Abuja Office Setup",
    departmentId: "dep_ops",
    requestedById: "usr_yusuf",
    status: "DRAFT",
    priority: "MEDIUM",
    category: "Office Furniture",
    tags: ["abuja", "new-office"],
    businessJustification:
      "60 ergonomic workstations, 4 meeting room setups, and reception furniture for the new Abuja office opening.",
    neededByDate: iso(40),
    totalEstimated: 38200,
    currency: "NGN",
    attachments: [{ name: "office-layout-final.pdf", size: "2.1 MB", type: "pdf" }],
    lineItems: [
      { id: "li_007_1", itemName: "Ergonomic Office Chair", description: "Mesh back, adjustable lumbar, 4D armrests, BIFMA certified", quantity: 60, unit: "pcs", estimatedCost: 280 },
      { id: "li_007_2", itemName: "Electric Sit-Stand Desk", description: "160x80cm, dual motor, 4 memory presets, oak top", quantity: 60, unit: "pcs", estimatedCost: 320 },
      { id: "li_007_3", itemName: "Meeting Room Table (8-seater)", description: "240x120cm, modular, with cable management", quantity: 4, unit: "pcs", estimatedCost: 850 },
    ],
    approvals: [],
    comments: [],
    watchers: ["usr_yusuf"],
    createdAt: iso(-1),
    updatedAt: iso(-1),
    version: 1,
  },
  {
    id: "req_008",
    organizationId: "org_apex",
    requestNumber: "PR-2026-0008",
    title: "HVAC Maintenance Contract Renewal",
    departmentId: "dep_fac",
    requestedById: "usr_yusuf",
    status: "APPROVED",
    priority: "MEDIUM",
    category: "Maintenance",
    tags: ["hvac", "annual", "contract"],
    businessJustification:
      "Annual HVAC maintenance contract expires in 30 days. Renewal ensures continuous coverage across all 3 branches (Lagos HQ, Abuja, Port Harcourt Plant). Required for warranty compliance on existing HVAC equipment.",
    neededByDate: iso(28),
    totalEstimated: 18000,
    currency: "NGN",
    attachments: [],
    lineItems: [
      { id: "li_008_1", itemName: "Annual HVAC Maintenance Contract", description: "Quarterly preventive maintenance, 24/7 emergency response, parts discount, all 3 branches", quantity: 1, unit: "contract", estimatedCost: 18000 },
    ],
    approvals: [
      {
        id: "ap_008_1",
        requestId: "req_008",
        stage: "DEPARTMENT_MANAGER",
        approverId: "usr_chidi",
        approverRole: "DEPARTMENT_MANAGER",
        decision: "APPROVED",
        decidedAt: iso(-10),
        createdAt: iso(-12),
        slaHours: 24,
        slaExpiresAt: iso(-11),
        isEscalated: false,
      },
      {
        id: "ap_008_2",
        requestId: "req_008",
        stage: "FINANCE",
        approverId: "usr_fatima",
        approverRole: "FINANCE_OFFICER",
        decision: "APPROVED",
        decidedAt: iso(-9),
        createdAt: iso(-10),
        slaHours: 48,
        slaExpiresAt: iso(-8),
        isEscalated: false,
      },
      {
        id: "ap_008_3",
        requestId: "req_008",
        stage: "PROCUREMENT",
        approverId: "usr_tunde",
        approverRole: "PROCUREMENT_MANAGER",
        decision: "APPROVED",
        decidedAt: iso(-8),
        createdAt: iso(-9),
        slaHours: 24,
        slaExpiresAt: iso(-8),
        isEscalated: false,
      },
    ],
    comments: [],
    watchers: ["usr_yusuf", "usr_tunde"],
    createdAt: iso(-12),
    updatedAt: iso(-8),
    submittedAt: iso(-12),
    version: 1,
  },
  {
    id: "req_009",
    organizationId: "org_apex",
    requestNumber: "PR-2026-0009",
    title: "Quality Assurance Lab Equipment",
    departmentId: "dep_qa",
    requestedById: "usr_ngozi",
    status: "SUBMITTED",
    priority: "MEDIUM",
    category: "Lab Equipment",
    tags: ["qa", "lab", "testing"],
    businessJustification:
      "QA lab requires calibration tools and testing equipment to maintain ISO 9001 certification. Current equipment is overdue for replacement.",
    neededByDate: iso(35),
    totalEstimated: 15600,
    currency: "NGN",
    attachments: [],
    lineItems: [
      { id: "li_009_1", itemName: "Digital Micrometer Set", description: "0-25mm, 25-50mm, 50-75mm calibrated set with certificate", quantity: 2, unit: "sets", estimatedCost: 850 },
      { id: "li_009_2", itemName: "Tensile Testing Machine", description: "50kN capacity, computer-controlled, ASTM E8 compliant", quantity: 1, unit: "unit", estimatedCost: 12500 },
      { id: "li_009_3", itemName: "Calibration Weight Set", description: "OIML E2 class, 1mg-500g, with calibration certificate", quantity: 1, unit: "set", estimatedCost: 1400 },
    ],
    approvals: [
      {
        id: "ap_009_1",
        requestId: "req_009",
        stage: "DEPARTMENT_MANAGER",
        approverId: "usr_chidi",
        approverRole: "DEPARTMENT_MANAGER",
        decision: "PENDING",
        createdAt: iso(-1),
        slaHours: 48,
        slaExpiresAt: iso(1),
        isEscalated: false,
      },
    ],
    comments: [],
    watchers: ["usr_ngozi"],
    createdAt: iso(-1),
    updatedAt: iso(-1),
    submittedAt: iso(-1),
    version: 1,
  },
];

export const seedRFQs: RFQ[] = [
  {
    id: "rfq_001",
    organizationId: "org_apex",
    rfqNumber: "RFQ-2026-0001",
    requestId: "req_002",
    title: "PPE Supply — Q3 Restock",
    description:
      "Quote required for the following PPE items per attached spec. Delivery to Port Harcourt Plant. Payment terms Net 30. Warranty against manufacturing defects.",
    deadline: iso(5),
    status: "RECEIVED",
    invitedVendorIds: ["vnd_safetync", "vnd_officedirect", "vnd_globalequip"],
    createdAt: iso(-1),
    quotations: [
      {
        id: "q_001_1",
        rfqId: "rfq_001",
        vendorId: "vnd_safetync",
        totalAmount: 11480,
        currency: "NGN",
        deliveryDays: 5,
        warranty: "12 months against manufacturing defects",
        paymentTerms: "Net 30",
        validUntil: iso(20),
        notes: "Free delivery to Port Harcourt Plant. Can supply full quantity from stock.",
        status: "RECEIVED",
        createdAt: iso(-0.5),
      },
      {
        id: "q_001_2",
        rfqId: "rfq_001",
        vendorId: "vnd_officedirect",
        totalAmount: 12250,
        currency: "NGN",
        deliveryDays: 7,
        warranty: "6 months against manufacturing defects",
        paymentTerms: "50% advance, 50% on delivery",
        validUntil: iso(15),
        notes: "Delivery via third-party logistics. Boots and helmets in stock, gloves require 5-day lead time.",
        status: "RECEIVED",
        createdAt: iso(-0.3),
      },
      {
        id: "q_001_3",
        rfqId: "rfq_001",
        vendorId: "vnd_globalequip",
        totalAmount: 13900,
        currency: "NGN",
        deliveryDays: 14,
        warranty: "24 months against manufacturing defects (premium grade)",
        paymentTerms: "Letter of Credit at sight",
        validUntil: iso(30),
        notes: "Imported premium-grade items. Longer delivery but superior quality and warranty. Suitable for high-risk environments.",
        status: "RECEIVED",
        createdAt: iso(-0.1),
      },
    ],
    remindersSent: 1,
    selectedQuotationId: undefined,
  },
  {
    id: "rfq_002",
    organizationId: "org_apex",
    rfqNumber: "RFQ-2026-0002",
    requestId: "req_006",
    title: "250kVA Backup Generator Supply & Installation",
    description:
      "Supply, install, and commission a 250kVA Perkins-equivalent diesel generator with ATS, sound-attenuated canopy, and 1000L fuel tank at Plant 2 (Port Harcourt).",
    deadline: iso(7),
    status: "WAITING",
    invitedVendorIds: ["vnd_powergen", "vnd_globalequip"],
    createdAt: iso(-0.5),
    quotations: [
      {
        id: "q_002_1",
        rfqId: "rfq_002",
        vendorId: "vnd_powergen",
        totalAmount: 41500,
        currency: "NGN",
        deliveryDays: 21,
        warranty: "24 months comprehensive on generator, 12 months on ATS",
        paymentTerms: "30% advance, 60% on delivery, 10% after commissioning",
        validUntil: iso(45),
        notes: "Stock unit available. Includes free site survey. Local Perkins-certified service team.",
        status: "RECEIVED",
        createdAt: iso(-0.2),
      },
    ],
    remindersSent: 0,
    selectedQuotationId: undefined,
  },
  {
    id: "rfq_003",
    organizationId: "org_apex",
    rfqNumber: "RFQ-2026-0003",
    requestId: "req_008",
    title: "Annual HVAC Maintenance Contract — 3 Branches",
    description:
      "Comprehensive annual HVAC maintenance contract covering Lagos HQ, Abuja Office, and Port Harcourt Plant. Includes quarterly preventive maintenance, 24/7 emergency response, and parts discount.",
    deadline: iso(-2),
    status: "CLOSED",
    invitedVendorIds: ["vnd_arcticair"],
    createdAt: iso(-12),
    quotations: [
      {
        id: "q_003_1",
        rfqId: "rfq_003",
        vendorId: "vnd_arcticair",
        totalAmount: 17500,
        currency: "NGN",
        deliveryDays: 0,
        warranty: "Service-level agreement, 4-hour emergency response",
        paymentTerms: "Quarterly billing in advance",
        validUntil: iso(30),
        notes: "Includes all 3 branches. 15% discount on replacement parts. Dedicated account manager.",
        status: "RECEIVED",
        createdAt: iso(-10),
      },
    ],
    remindersSent: 0,
    selectedQuotationId: "q_003_1",
  },
];

export const seedPurchaseOrders: PurchaseOrder[] = [
  {
    id: "po_001",
    organizationId: "org_apex",
    poNumber: "PO-2026-0001",
    requestId: "req_004",
    vendorId: "vnd_steelworks",
    status: "RECEIVED",
    subtotal: 38500,
    taxAmount: 2887.5,
    totalAmount: 41387.5,
    currency: "NGN",
    taxRate: 7.5,
    issuedAt: iso(-23),
    expectedDelivery: iso(-8),
    receivedAt: iso(-8),
    notes: "Delivery to Plant 2 site. SteelWorks to coordinate with site engineer on delivery schedule.",
    termsAndConditions: "1. Payment terms: 30% advance, 70% on delivery.\n2. Goods must meet ASTM A615 Grade 60 specifications.\n3. Delivery to be completed by agreed date.\n4. Any discrepancies must be reported within 48 hours of receipt.\n5. Steel must be free from defects, rust, and surface damage.",
    lineItems: [
      { id: "li_po_001_1", itemName: "Steel Rebar Grade 60 — 16mm", description: "ASTM A615 Grade 60, 16mm diameter, 12m lengths", quantity: 30, unit: "tonnes", estimatedCost: 850 },
      { id: "li_po_001_2", itemName: "Steel Rebar Grade 60 — 20mm", description: "ASTM A615 Grade 60, 20mm diameter, 12m lengths", quantity: 20, unit: "tonnes", estimatedCost: 920 },
    ],
    version: 1,
    revisions: [],
    attachments: [{ name: "delivery-receipt.pdf", size: "120 KB" }],
  },
  {
    id: "po_002",
    organizationId: "org_apex",
    poNumber: "PO-2026-0002",
    vendorId: "vnd_officedirect",
    status: "CLOSED",
    subtotal: 7628,
    taxAmount: 572,
    totalAmount: 8200,
    currency: "NGN",
    taxRate: 7.5,
    issuedAt: iso(-30),
    expectedDelivery: iso(-22),
    receivedAt: iso(-22),
    notes: "Q1 office supplies restock.",
    termsAndConditions: "Standard terms apply.",
    lineItems: [
      { id: "li_po_002_1", itemName: "A4 Paper (80gsm, 500 sheets/ream)", description: "Multi-purpose white printer paper", quantity: 200, unit: "reams", estimatedCost: 6.5 },
      { id: "li_po_002_2", itemName: "Printer Toner Cartridges (HP)", description: "HP 414A original toner, mixed colors", quantity: 20, unit: "pcs", estimatedCost: 95 },
      { id: "li_po_002_3", itemName: "Desk Organizers & Stationery Kit", description: "Complete kit including pens, files, staplers, clips", quantity: 50, unit: "kits", estimatedCost: 36 },
    ],
    version: 1,
    revisions: [],
    attachments: [],
  },
  {
    id: "po_003",
    organizationId: "org_apex",
    poNumber: "PO-2026-0003",
    vendorId: "vnd_powergen",
    status: "IN_DELIVERY",
    subtotal: 15628,
    taxAmount: 1172,
    totalAmount: 16800,
    currency: "NGN",
    taxRate: 7.5,
    issuedAt: iso(-12),
    expectedDelivery: iso(3),
    notes: "UPS units for Lagos HQ server room upgrade.",
    termsAndConditions: "1. 24-month comprehensive warranty.\n2. Free site survey included.\n3. Installation by Perkins-certified team.",
    lineItems: [
      { id: "li_po_003_1", itemName: "UPS 5kVA Online Double-Conversion", description: "Rack-mount UPS, 5kVA, with network management card", quantity: 4, unit: "units", estimatedCost: 4200 },
    ],
    version: 1,
    revisions: [],
    attachments: [],
  },
  {
    id: "po_004",
    organizationId: "org_apex",
    poNumber: "PO-2026-0004",
    vendorId: "vnd_techcore",
    status: "ISSUED",
    subtotal: 14512,
    taxAmount: 1088,
    totalAmount: 15600,
    currency: "NGN",
    taxRate: 7.5,
    issuedAt: iso(-2),
    expectedDelivery: iso(10),
    notes: "Network switches and access points for Lagos HQ refresh.",
    termsAndConditions: "1. Net 30 payment terms.\n2. 36-month manufacturer warranty on switches.\n3. Free configuration and deployment support.",
    lineItems: [
      { id: "li_po_004_1", itemName: "Cisco Catalyst 9300 Switch", description: "48-port PoE+ enterprise switch, stackable", quantity: 2, unit: "units", estimatedCost: 4500 },
      { id: "li_po_004_2", itemName: "Ubiquiti U6-Pro Access Points", description: "Wi-Fi 6 access points, ceiling mount, PoE+", quantity: 15, unit: "pcs", estimatedCost: 280 },
    ],
    version: 2,
    revisions: [
      { version: 1, modifiedAt: iso(-3), modifiedBy: "usr_tunde", reason: "Initial issue" },
      { version: 2, modifiedAt: iso(-2), modifiedBy: "usr_tunde", reason: "Added 5 additional access points for full coverage" },
    ],
    attachments: [],
  },
  {
    id: "po_005",
    organizationId: "org_apex",
    poNumber: "PO-2026-0005",
    vendorId: "vnd_primecement",
    status: "ACKNOWLEDGED",
    subtotal: 22791,
    taxAmount: 1709,
    totalAmount: 24500,
    currency: "NGN",
    taxRate: 7.5,
    issuedAt: iso(-4),
    expectedDelivery: iso(7),
    notes: "Cement supply for Plant 2 Phase 2 construction.",
    termsAndConditions: "1. 50% advance, 50% on delivery.\n2. Delivery in 50kg bags.\n3. ASTM C150 Type I specification.",
    lineItems: [
      { id: "li_po_005_1", itemName: "Portland Cement Grade 42.5N", description: "Bulk cement, 50kg bags, ASTM C150 Type I", quantity: 500, unit: "bags", estimatedCost: 49 },
    ],
    version: 1,
    revisions: [],
    attachments: [],
  },
  {
    id: "po_006",
    organizationId: "org_apex",
    poNumber: "PO-2026-0006",
    vendorId: "vnd_dangote_cement",
    status: "ISSUED",
    subtotal: 18605,
    taxAmount: 1395,
    totalAmount: 20000,
    currency: "NGN",
    taxRate: 7.5,
    issuedAt: iso(-1),
    expectedDelivery: iso(14),
    notes: "Bulk cement procurement — strategic partner pricing.",
    termsAndConditions: "1. Net 30 payment terms.\n2. Strategic partner volume discount applied.\n3. Free delivery to all 3 branches.",
    lineItems: [
      { id: "li_po_006_1", itemName: "Bulk Portland Cement", description: "Grade 42.5N, bulk delivery", quantity: 400, unit: "bags", estimatedCost: 50 },
    ],
    version: 1,
    revisions: [],
    attachments: [],
  },
];

export const seedActivities: ActivityLog[] = [
  {
    id: "act_001",
    organizationId: "org_apex",
    userId: "usr_tunde",
    purchaseOrderId: "po_004",
    eventType: "PO_GENERATED",
    description: "Tunde Bello generated Purchase Order PO-2026-0004 to TechCore Distributors Ltd. ($15,600)",
    severity: "SUCCESS",
    ipAddress: "102.89.45.12",
    createdAt: iso(-2),
  },
  {
    id: "act_002",
    organizationId: "org_apex",
    userId: "usr_chidi",
    requestId: "req_006",
    eventType: "REQUEST_APPROVED",
    description: "Chidi Nwosu approved PR-2026-0006 (Backup Generator) at the Department Manager stage",
    severity: "SUCCESS",
    ipAddress: "102.89.45.18",
    createdAt: iso(-2),
  },
  {
    id: "act_003",
    organizationId: "org_apex",
    userId: "usr_tunde",
    rfqId: "rfq_001",
    eventType: "QUOTATION_RECEIVED",
    description: "Quotation received from Arctic Air HVAC Systems for RFQ-2026-0003",
    severity: "INFO",
    ipAddress: "102.89.45.12",
    createdAt: iso(-0.1),
  },
  {
    id: "act_004",
    organizationId: "org_apex",
    userId: "usr_emeka",
    requestId: "req_006",
    eventType: "REQUEST_SUBMITTED",
    description: "Emeka Eze submitted PR-2026-0006: 'Backup Generator — 250kVA for Plant 2'",
    severity: "INFO",
    ipAddress: "102.89.45.22",
    createdAt: iso(-3),
  },
  {
    id: "act_005",
    organizationId: "org_apex",
    userId: "usr_tunde",
    rfqId: "rfq_001",
    eventType: "RFQ_CREATED",
    description: "RFQ-2026-0001 issued to 3 vendors: SafetyNig Industrial, OfficeDirect Nigeria, Global Equipment Trading",
    severity: "INFO",
    ipAddress: "102.89.45.12",
    createdAt: iso(-1),
  },
  {
    id: "act_006",
    organizationId: "org_apex",
    userId: "usr_fatima",
    requestId: "req_002",
    eventType: "REQUEST_APPROVED",
    description: "Fatima Sani approved PR-2026-0002 (PPE Restock) — $12,650",
    severity: "SUCCESS",
    ipAddress: "102.89.45.15",
    createdAt: iso(-1),
  },
  {
    id: "act_007",
    organizationId: "org_apex",
    userId: "usr_chidi",
    requestId: "req_001",
    eventType: "REQUEST_COMMENTED",
    description: "Chidi Nwosu commented on PR-2026-0001 and mentioned @fatima.sani",
    severity: "INFO",
    ipAddress: "102.89.45.18",
    createdAt: iso(-3),
  },
  {
    id: "act_008",
    organizationId: "org_apex",
    userId: "usr_yusuf",
    requestId: "req_007",
    eventType: "REQUEST_CREATED",
    description: "Yusuf Aliyu created draft PR-2026-0007: 'Office Furniture — Abuja Office Setup'",
    severity: "INFO",
    ipAddress: "102.89.45.20",
    createdAt: iso(-1),
  },
  {
    id: "act_009",
    organizationId: "org_apex",
    purchaseOrderId: "po_001",
    eventType: "PO_STATUS_UPDATED",
    description: "Purchase Order PO-2026-0001 marked as RECEIVED — Steel rebar delivered to Plant 2",
    severity: "SUCCESS",
    ipAddress: "102.89.45.18",
    createdAt: iso(-8),
  },
  {
    id: "act_010",
    organizationId: "org_apex",
    userId: "usr_fatima",
    requestId: "req_005",
    eventType: "REQUEST_REJECTED",
    description: "Fatima Sani rejected PR-2026-0005 (Marketing Laptops) — 'FY IT budget exhausted'",
    severity: "WARNING",
    ipAddress: "102.89.45.15",
    createdAt: iso(-6),
  },
  {
    id: "act_011",
    organizationId: "org_apex",
    userId: "usr_amina",
    eventType: "USER_LOGIN",
    description: "Amina Okafor signed in from 102.89.45.10 (Lagos, Nigeria)",
    severity: "INFO",
    ipAddress: "102.89.45.10",
    createdAt: iso(0),
  },
  {
    id: "act_012",
    organizationId: "org_apex",
    userId: "usr_tunde",
    eventType: "VENDOR_UPDATED",
    description: "Tunde Bello updated compliance documents for TechCore Distributors Ltd.",
    severity: "INFO",
    ipAddress: "102.89.45.12",
    createdAt: iso(-4),
  },
  {
    id: "act_013",
    organizationId: "org_apex",
    eventType: "BUDGET_ALERT",
    description: "Engineering department budget at 78% utilization ($218,500 of $480,000)",
    severity: "WARNING",
    createdAt: iso(-5),
  },
  {
    id: "act_014",
    organizationId: "org_apex",
    userId: "usr_tunde",
    eventType: "VENDOR_BLACKLISTED",
    description: "Tunde Bello blacklisted Legacy Tools Co. due to repeated quality failures",
    severity: "CRITICAL",
    ipAddress: "102.89.45.12",
    createdAt: iso(-15),
  },
];

export const seedNotifications: Notification[] = [
  {
    id: "ntf_001",
    organizationId: "org_apex",
    userId: "usr_amina",
    title: "Approval needed: Backup Generator",
    message: "PR-2026-0006 (Backup Generator — 250kVA) is awaiting your Finance approval. $42,000 commitment.",
    type: "approval",
    read: false,
    link: "approvals",
    entityId: "req_006",
    entityType: "REQUEST",
    createdAt: iso(-2),
  },
  {
    id: "ntf_002",
    organizationId: "org_apex",
    userId: "usr_amina",
    title: "New quotation received",
    message: "Arctic Air HVAC Systems submitted a quotation for RFQ-2026-0003.",
    type: "info",
    read: false,
    link: "rfqs",
    entityId: "rfq_001",
    entityType: "RFQ",
    createdAt: iso(-0.1),
  },
  {
    id: "ntf_003",
    organizationId: "org_apex",
    userId: "usr_amina",
    title: "PO issued to TechCore",
    message: "PO-2026-0004 for $15,600 was issued to TechCore Distributors Ltd.",
    type: "success",
    read: false,
    link: "purchase-orders",
    entityId: "po_004",
    entityType: "PO",
    createdAt: iso(-2),
  },
  {
    id: "ntf_004",
    organizationId: "org_apex",
    userId: "usr_amina",
    title: "PR-2026-0001 needs Finance review",
    message: "Industrial Laptops request ($8,400) cleared Department Manager approval.",
    type: "approval",
    read: true,
    link: "requests",
    entityId: "req_001",
    entityType: "REQUEST",
    createdAt: iso(-3),
  },
  {
    id: "ntf_005",
    organizationId: "org_apex",
    userId: "usr_amina",
    title: "Steel delivery completed",
    message: "PO-2026-0001 (Steel rebar) was marked as received at Plant 2.",
    type: "success",
    read: true,
    link: "purchase-orders",
    entityId: "po_001",
    entityType: "PO",
    createdAt: iso(-8),
  },
  {
    id: "ntf_006",
    organizationId: "org_apex",
    userId: "usr_amina",
    title: "Budget alert: Engineering",
    message: "Engineering department has used 78% of annual budget.",
    type: "budget",
    read: false,
    link: "budgets",
    createdAt: iso(-5),
  },
  {
    id: "ntf_007",
    organizationId: "org_apex",
    userId: "usr_amina",
    title: "SLA warning: PR-2026-0003",
    message: "Approval SLA expires in 6 hours for Abuja Office Server Rack request.",
    type: "sla",
    read: false,
    link: "approvals",
    entityId: "req_003",
    entityType: "REQUEST",
    createdAt: iso(-0.2),
  },
  {
    id: "ntf_008",
    organizationId: "org_apex",
    userId: "usr_amina",
    title: "Vendor compliance: Insurance expired",
    message: "SafetyNig Industrial Supplies' Public Liability Insurance has expired.",
    type: "warning",
    read: false,
    link: "vendors",
    entityId: "vnd_safetync",
    entityType: "VENDOR",
    createdAt: iso(-1),
  },
];

// ---------------------------------------------------------------------------
// New enterprise entities
// ---------------------------------------------------------------------------
export const seedWorkflows: ApprovalWorkflow[] = [
  {
    id: "wf_standard",
    organizationId: "org_apex",
    name: "Standard Procurement Workflow",
    description: "3-stage approval chain for requests up to $25,000. Department → Finance → Procurement.",
    isActive: true,
    thresholdMin: 0,
    thresholdMax: 25000,
    stages: [
      { id: "ws_1", name: "Department Manager Approval", stage: "DEPARTMENT_MANAGER", approverRole: "DEPARTMENT_MANAGER", slaHours: 48, allowDelegation: true, isParallel: false },
      { id: "ws_2", name: "Finance Approval", stage: "FINANCE", approverRole: "FINANCE_OFFICER", slaHours: 72, allowDelegation: false, isParallel: false },
      { id: "ws_3", name: "Procurement Review", stage: "PROCUREMENT", approverRole: "PROCUREMENT_MANAGER", slaHours: 24, allowDelegation: false, isParallel: false },
    ],
    createdAt: "2023-03-15T09:00:00Z",
  },
  {
    id: "wf_high_value",
    organizationId: "org_apex",
    name: "High-Value Procurement Workflow",
    description: "4-stage approval for requests above $25,000. Includes executive sign-off.",
    isActive: true,
    thresholdMin: 25000,
    thresholdMax: 100000,
    stages: [
      { id: "ws_4", name: "Department Manager Approval", stage: "DEPARTMENT_MANAGER", approverRole: "DEPARTMENT_MANAGER", slaHours: 24, allowDelegation: true, isParallel: false },
      { id: "ws_5", name: "Finance Approval", stage: "FINANCE", approverRole: "FINANCE_OFFICER", slaHours: 48, allowDelegation: false, isParallel: false },
      { id: "ws_6", name: "Procurement Review", stage: "PROCUREMENT", approverRole: "PROCUREMENT_MANAGER", slaHours: 24, allowDelegation: false, isParallel: false },
      { id: "ws_7", name: "Executive Sign-off", stage: "EXECUTIVE", approverRole: "SUPER_ADMIN", slaHours: 72, escalationRole: "SUPER_ADMIN", allowDelegation: false, isParallel: false },
    ],
    createdAt: "2023-03-15T09:00:00Z",
  },
  {
    id: "wf_emergency",
    organizationId: "org_apex",
    name: "Emergency Procurement Workflow",
    description: "Expedited 1-stage approval for urgent requests. Auto-escalates after 4 hours.",
    isActive: true,
    priorityFilter: ["URGENT"],
    thresholdMin: 0,
    thresholdMax: 50000,
    stages: [
      { id: "ws_8", name: "Expedited Approval", stage: "PROCUREMENT", approverRole: "PROCUREMENT_MANAGER", slaHours: 4, escalationRole: "SUPER_ADMIN", allowDelegation: true, isParallel: false },
    ],
    createdAt: "2024-06-01T09:00:00Z",
  },
];

export const seedBudgets: Budget[] = [
  {
    id: "bud_eng_2026",
    organizationId: "org_apex",
    departmentId: "dep_eng",
    fiscalYear: 2026,
    totalAmount: 480000,
    spentAmount: 218500,
    committedAmount: 42000,
    remainingAmount: 219500,
    categories: [
      { name: "Equipment & Machinery", allocated: 200000, spent: 98000 },
      { name: "Construction Materials", allocated: 150000, spent: 78500 },
      { name: "Lab & Testing", allocated: 80000, spent: 24000 },
      { name: "Software & Tools", allocated: 50000, spent: 18000 },
    ],
    alerts: [
      { threshold: 75, triggered: true, triggeredAt: iso(-5) },
      { threshold: 90, triggered: false },
    ],
    status: "ACTIVE",
    createdAt: "2026-01-01T00:00:00Z",
  },
  {
    id: "bud_it_2026",
    organizationId: "org_apex",
    departmentId: "dep_it",
    fiscalYear: 2026,
    totalAmount: 240000,
    spentAmount: 89600,
    committedAmount: 24500,
    remainingAmount: 125900,
    categories: [
      { name: "Hardware", allocated: 120000, spent: 52000 },
      { name: "Software Licenses", allocated: 70000, spent: 24600 },
      { name: "Network & Infrastructure", allocated: 50000, spent: 13000 },
    ],
    alerts: [
      { threshold: 75, triggered: false },
      { threshold: 90, triggered: false },
    ],
    status: "ACTIVE",
    createdAt: "2026-01-01T00:00:00Z",
  },
  {
    id: "bud_ops_2026",
    organizationId: "org_apex",
    departmentId: "dep_ops",
    fiscalYear: 2026,
    totalAmount: 360000,
    spentAmount: 142800,
    committedAmount: 38200,
    remainingAmount: 179000,
    categories: [
      { name: "Office Operations", allocated: 150000, spent: 62000 },
      { name: "Furniture & Equipment", allocated: 100000, spent: 38200 },
      { name: "Logistics", allocated: 60000, spent: 22800 },
      { name: "Miscellaneous", allocated: 50000, spent: 19800 },
    ],
    alerts: [
      { threshold: 75, triggered: false },
      { threshold: 90, triggered: false },
    ],
    status: "ACTIVE",
    createdAt: "2026-01-01T00:00:00Z",
  },
  {
    id: "bud_fac_2026",
    organizationId: "org_apex",
    departmentId: "dep_fac",
    fiscalYear: 2026,
    totalAmount: 150000,
    spentAmount: 58200,
    committedAmount: 42000,
    remainingAmount: 49800,
    categories: [
      { name: "Maintenance Contracts", allocated: 60000, spent: 18000 },
      { name: "Power & Backup", allocated: 50000, spent: 42000 },
      { name: "Safety Equipment", allocated: 40000, spent: 0 },
    ],
    alerts: [
      { threshold: 75, triggered: false },
      { threshold: 90, triggered: false },
    ],
    status: "ACTIVE",
    createdAt: "2026-01-01T00:00:00Z",
  },
];

export const seedTemplates: RequestTemplate[] = [
  {
    id: "tpl_ppe",
    organizationId: "org_apex",
    name: "PPE Quarterly Restock",
    description: "Standard PPE restock template for quarterly safety equipment replenishment.",
    category: "Safety Equipment",
    departmentId: "dep_fac",
    priority: "HIGH",
    defaultLineItems: [
      { itemName: "Safety Helmets", description: "Class B hard hats", quantity: 50, unit: "pcs", estimatedCost: 28 },
      { itemName: "Safety Vests", description: "Class 2 reflective", quantity: 80, unit: "pcs", estimatedCost: 18 },
      { itemName: "Safety Boots", description: "Steel-toe, mixed sizes", quantity: 30, unit: "pairs", estimatedCost: 95 },
      { itemName: "Cut-Resistant Gloves", description: "Level 5 protection", quantity: 100, unit: "pairs", estimatedCost: 12 },
    ],
    defaultJustification: "Quarterly PPE restock per HSE compliance policy.",
    usageCount: 4,
    createdBy: "usr_tunde",
    createdAt: "2025-01-15T09:00:00Z",
  },
  {
    id: "tpl_laptop",
    organizationId: "org_apex",
    name: "Standard Laptop Request",
    description: "Standard company laptop for new hires or replacements.",
    category: "IT Equipment",
    departmentId: "dep_it",
    priority: "MEDIUM",
    defaultLineItems: [
      { itemName: "ThinkPad T14 Gen 5", description: "14-inch, i7, 16GB RAM, 512GB SSD", quantity: 1, unit: "unit", estimatedCost: 1450 },
      { itemName: "Docking Station", description: "USB-C dock with 2x DP, HDMI, Ethernet", quantity: 1, unit: "unit", estimatedCost: 180 },
      { itemName: "27\" Monitor", description: "QHD IPS display, height-adjustable", quantity: 1, unit: "unit", estimatedCost: 280 },
    ],
    defaultJustification: "Standard equipment for new team member / replacement of failed unit.",
    usageCount: 18,
    createdBy: "usr_grace",
    createdAt: "2025-02-10T09:00:00Z",
  },
  {
    id: "tpl_office_supplies",
    organizationId: "org_apex",
    name: "Monthly Office Supplies",
    description: "Recurring monthly office supplies order.",
    category: "Office Supplies",
    departmentId: "dep_ops",
    priority: "LOW",
    defaultLineItems: [
      { itemName: "A4 Paper", description: "80gsm, 500 sheets/ream", quantity: 100, unit: "reams", estimatedCost: 6.5 },
      { itemName: "Printer Toner", description: "HP 414A black, mixed colors", quantity: 10, unit: "pcs", estimatedCost: 95 },
      { itemName: "Stationery Kit", description: "Pens, files, staplers, clips", quantity: 20, unit: "kits", estimatedCost: 36 },
    ],
    defaultJustification: "Monthly office supplies restock.",
    usageCount: 24,
    createdBy: "usr_yusuf",
    createdAt: "2025-01-05T09:00:00Z",
  },
  {
    id: "tpl_hvac_maintenance",
    organizationId: "org_apex",
    name: "HVAC Annual Maintenance",
    description: "Annual HVAC maintenance contract renewal.",
    category: "Maintenance",
    departmentId: "dep_fac",
    priority: "MEDIUM",
    defaultLineItems: [
      { itemName: "Annual HVAC Maintenance Contract", description: "Quarterly maintenance, 24/7 emergency, 3 branches", quantity: 1, unit: "contract", estimatedCost: 18000 },
    ],
    defaultJustification: "Annual contract renewal to maintain HVAC warranty compliance.",
    usageCount: 2,
    createdBy: "usr_tunde",
    createdAt: "2025-01-20T09:00:00Z",
  },
];

export const seedIntegrations: Integration[] = [
  {
    id: "int_slack",
    organizationId: "org_apex",
    type: "SLACK",
    name: "Slack",
    status: "CONNECTED",
    configuredBy: "usr_amina",
    configuredAt: "2025-08-15T10:00:00Z",
    lastSyncAt: iso(-0.1),
    lastSyncStatus: "SUCCESS",
    config: { workspace: "apex-industries", channel: "#procurement" },
    enabledEvents: ["REQUEST_SUBMITTED", "REQUEST_APPROVED", "PO_GENERATED", "BUDGET_ALERT"],
    syncFrequency: "REAL_TIME",
    healthStatus: "HEALTHY",
    logs: [
      { id: "log_1", integrationId: "int_slack", timestamp: iso(-0.1), event: "SYNC", status: "SUCCESS", message: "Synced 4 notifications to #procurement", duration: 240 },
      { id: "log_2", integrationId: "int_slack", timestamp: iso(-2), event: "SYNC", status: "SUCCESS", message: "Synced 12 notifications", duration: 180 },
      { id: "log_3", integrationId: "int_slack", timestamp: iso(-5), event: "WEBHOOK_DELIVERY", status: "SUCCESS", message: "Delivered budget alert", duration: 95 },
    ],
  },
  {
    id: "int_quickbooks",
    organizationId: "org_apex",
    type: "QUICKBOOKS",
    name: "QuickBooks Online",
    status: "CONNECTED",
    configuredBy: "usr_fatima",
    configuredAt: "2025-06-10T10:00:00Z",
    lastSyncAt: iso(-2),
    lastSyncStatus: "SUCCESS",
    config: { company: "Apex Industries Ltd.", syncMode: "real-time" },
    enabledEvents: ["PO_ISSUED", "PO_RECEIVED"],
    syncFrequency: "HOURLY",
    healthStatus: "HEALTHY",
    logs: [
      { id: "log_4", integrationId: "int_quickbooks", timestamp: iso(-2), event: "PO_SYNC", status: "SUCCESS", message: "Synced 2 purchase orders", duration: 1200 },
      { id: "log_5", integrationId: "int_quickbooks", timestamp: iso(-26), event: "INVOICE_SYNC", status: "SUCCESS", message: "Synced 3 invoices", duration: 980 },
    ],
  },
  {
    id: "int_teams",
    organizationId: "org_apex",
    type: "TEAMS",
    name: "Microsoft Teams",
    status: "PENDING",
    configuredBy: "usr_amina",
    configuredAt: iso(-1),
    config: {},
    enabledEvents: [],
    syncFrequency: "MANUAL",
    healthStatus: "UNKNOWN",
    logs: [],
  },
  {
    id: "int_whatsapp",
    organizationId: "org_apex",
    type: "WHATSAPP",
    name: "WhatsApp Business",
    status: "DISCONNECTED",
    configuredBy: "usr_tunde",
    configuredAt: "2025-09-22T10:00:00Z",
    config: {},
    enabledEvents: [],
    syncFrequency: "MANUAL",
    healthStatus: "UNKNOWN",
    logs: [],
  },
  {
    id: "int_xero",
    organizationId: "org_apex",
    type: "XERO",
    name: "Xero",
    status: "DISCONNECTED",
    configuredBy: "usr_fatima",
    configuredAt: "2025-10-01T10:00:00Z",
    config: {},
    enabledEvents: [],
    syncFrequency: "MANUAL",
    healthStatus: "UNKNOWN",
    logs: [],
  },
  {
    id: "int_webhook",
    organizationId: "org_apex",
    type: "WEBHOOK",
    name: "Custom Webhook (ERP)",
    status: "CONNECTED",
    configuredBy: "usr_amina",
    configuredAt: "2025-04-12T10:00:00Z",
    lastSyncAt: iso(-0.05),
    lastSyncStatus: "SUCCESS",
    config: { url: "https://erp.apex.com/webhooks/procurement", secret: "***" },
    enabledEvents: ["PO_ISSUED", "PO_RECEIVED", "PO_CLOSED"],
    syncFrequency: "REAL_TIME",
    healthStatus: "HEALTHY",
    logs: [
      { id: "log_6", integrationId: "int_webhook", timestamp: iso(-0.05), event: "WEBHOOK_DELIVERY", status: "SUCCESS", message: "Delivered PO_ISSUED event", duration: 145 },
      { id: "log_7", integrationId: "int_webhook", timestamp: iso(-1), event: "WEBHOOK_DELIVERY", status: "SUCCESS", message: "Delivered PO_RECEIVED event", duration: 98 },
      { id: "log_8", integrationId: "int_webhook", timestamp: iso(-3), event: "WEBHOOK_RETRY", status: "SUCCESS", message: "Retry succeeded after 1 attempt", duration: 320 },
    ],
  },
];

export const seedAuditLogs: AuditLogEntry[] = [
  {
    id: "aud_001",
    organizationId: "org_apex",
    userId: "usr_amina",
    action: "USER_LOGIN",
    resource: "AUTH",
    ipAddress: "102.89.45.10",
    userAgent: "Chrome/120 macOS",
    timestamp: iso(0),
  },
  {
    id: "aud_002",
    organizationId: "org_apex",
    userId: "usr_tunde",
    action: "PO_GENERATED",
    resource: "PURCHASE_ORDER",
    resourceId: "po_004",
    after: { poNumber: "PO-2026-0004", vendor: "vnd_techcore", total: 15600 },
    ipAddress: "102.89.45.12",
    userAgent: "Chrome/120 Windows",
    timestamp: iso(-2),
  },
  {
    id: "aud_003",
    organizationId: "org_apex",
    userId: "usr_fatima",
    action: "PERMISSION_GRANTED",
    resource: "USER",
    resourceId: "usr_yusuf",
    after: { permission: "reports.export", grantedBy: "usr_fatima" },
    ipAddress: "102.89.45.15",
    userAgent: "Chrome/120 Windows",
    timestamp: iso(-7),
  },
  {
    id: "aud_004",
    organizationId: "org_apex",
    userId: "usr_chidi",
    action: "REQUEST_APPROVED",
    resource: "PURCHASE_REQUEST",
    resourceId: "req_006",
    after: { stage: "DEPARTMENT_MANAGER", decision: "APPROVED" },
    ipAddress: "102.89.45.18",
    userAgent: "Chrome/120 Windows",
    timestamp: iso(-2),
  },
  {
    id: "aud_005",
    organizationId: "org_apex",
    userId: "usr_tunde",
    action: "VENDOR_BLACKLISTED",
    resource: "VENDOR",
    resourceId: "vnd_legacytools",
    before: { status: "ACTIVE" },
    after: { status: "BLACKLISTED", reason: "Repeated quality failures" },
    ipAddress: "102.89.45.12",
    userAgent: "Chrome/120 Windows",
    timestamp: iso(-15),
  },
  {
    id: "aud_006",
    organizationId: "org_apex",
    userId: "usr_amina",
    action: "SETTINGS_UPDATED",
    resource: "ORGANIZATION",
    after: { field: "currency", oldValue: "NGN", newValue: "USD" },
    ipAddress: "102.89.45.10",
    userAgent: "Chrome/120 macOS",
    timestamp: iso(-30),
  },
];

export const seedNotificationPreference: NotificationPreference = {
  userId: "usr_amina",
  channels: {
    inApp: true,
    email: true,
    push: true,
    slack: true,
    teams: false,
    whatsapp: false,
    sms: false,
  },
  categories: {
    approvals: true,
    requests: true,
    rfqs: true,
    purchaseOrders: true,
    budgetAlerts: true,
    slaWarnings: true,
    mentions: true,
    weeklyDigest: true,
  },
  quietHoursStart: "19:00",
  quietHoursEnd: "07:00",
};

// ---------------------------------------------------------------------------
// Goods Receipts
// ---------------------------------------------------------------------------
export const seedGoodsReceipts: GoodsReceipt[] = [
  {
    id: "gr_001",
    organizationId: "org_apex",
    receiptNumber: "GR-2026-0001",
    poId: "po_001",
    vendorId: "vnd_steelworks",
    receivedById: "usr_emeka",
    status: "RECEIVED",
    receivedDate: iso(-8),
    notes: "Delivery completed successfully. All items inspected and verified.",
    items: [
      { id: "gri_001_1", lineItemId: "li_po_001_1", itemName: "Steel Rebar Grade 60 — 16mm", orderedQty: 30, receivedQty: 30, unit: "tonnes", condition: "GOOD" },
      { id: "gri_001_2", lineItemId: "li_po_001_2", itemName: "Steel Rebar Grade 60 — 20mm", orderedQty: 20, receivedQty: 20, unit: "tonnes", condition: "GOOD" },
    ],
    attachments: [{ name: "delivery-receipt.pdf", size: "120 KB" }],
    createdAt: iso(-8),
  },
  {
    id: "gr_002",
    organizationId: "org_apex",
    receiptNumber: "GR-2026-0002",
    poId: "po_002",
    vendorId: "vnd_officedirect",
    receivedById: "usr_yusuf",
    status: "RECEIVED",
    receivedDate: iso(-22),
    notes: "Office supplies delivered to Lagos HQ.",
    items: [
      { id: "gri_002_1", lineItemId: "li_po_002_1", itemName: "A4 Paper (80gsm, 500 sheets/ream)", orderedQty: 200, receivedQty: 200, unit: "reams", condition: "GOOD" },
      { id: "gri_002_2", lineItemId: "li_po_002_2", itemName: "Printer Toner Cartridges (HP)", orderedQty: 20, receivedQty: 20, unit: "pcs", condition: "GOOD" },
      { id: "gri_002_3", lineItemId: "li_po_002_3", itemName: "Desk Organizers & Stationery Kit", orderedQty: 50, receivedQty: 50, unit: "kits", condition: "GOOD" },
    ],
    attachments: [],
    createdAt: iso(-22),
  },
  {
    id: "gr_003",
    organizationId: "org_apex",
    receiptNumber: "GR-2026-0003",
    poId: "po_003",
    vendorId: "vnd_powergen",
    receivedById: "usr_emeka",
    status: "PARTIAL",
    receivedDate: iso(-1),
    notes: "2 of 4 UPS units received. Remaining 2 expected in 3 days.",
    items: [
      { id: "gri_003_1", lineItemId: "li_po_003_1", itemName: "UPS 5kVA Online Double-Conversion", orderedQty: 4, receivedQty: 2, unit: "units", condition: "GOOD", notes: "2 units pending delivery" },
    ],
    attachments: [{ name: "partial-delivery-note.pdf", size: "85 KB" }],
    createdAt: iso(-1),
  },
];

// ---------------------------------------------------------------------------
// Invoices
// ---------------------------------------------------------------------------
export const seedInvoices: Invoice[] = [
  {
    id: "inv_001",
    organizationId: "org_apex",
    invoiceNumber: "INV-2026-0001",
    vendorId: "vnd_steelworks",
    poId: "po_001",
    goodsReceiptId: "gr_001",
    status: "PAID",
    issueDate: iso(-7),
    dueDate: iso(23),
    subtotal: 38500,
    taxAmount: 2887.5,
    totalAmount: 41387.5,
    currency: "NGN",
    paidAmount: 41387.5,
    balance: 0,
    notes: "Steel rebar delivery — Plant 2 Phase 2.",
    attachments: [{ name: "steelworks-invoice.pdf", size: "245 KB" }],
    approvedById: "usr_fatima",
    approvedAt: iso(-5),
    createdAt: iso(-7),
  },
  {
    id: "inv_002",
    organizationId: "org_apex",
    invoiceNumber: "INV-2026-0002",
    vendorId: "vnd_officedirect",
    poId: "po_002",
    goodsReceiptId: "gr_002",
    status: "PAID",
    issueDate: iso(-21),
    dueDate: iso(-1),
    subtotal: 7628,
    taxAmount: 572,
    totalAmount: 8200,
    currency: "NGN",
    paidAmount: 8200,
    balance: 0,
    notes: "Q1 office supplies.",
    attachments: [],
    approvedById: "usr_fatima",
    approvedAt: iso(-20),
    createdAt: iso(-21),
  },
  {
    id: "inv_003",
    organizationId: "org_apex",
    invoiceNumber: "INV-2026-0003",
    vendorId: "vnd_powergen",
    poId: "po_003",
    status: "SUBMITTED",
    issueDate: iso(-1),
    dueDate: iso(29),
    subtotal: 8400,
    taxAmount: 630,
    totalAmount: 9030,
    currency: "NGN",
    paidAmount: 0,
    balance: 9030,
    notes: "Partial invoice for 2 of 4 UPS units delivered.",
    attachments: [{ name: "powergen-invoice.pdf", size: "180 KB" }],
    createdAt: iso(-1),
  },
  {
    id: "inv_004",
    organizationId: "org_apex",
    invoiceNumber: "INV-2026-0004",
    vendorId: "vnd_techcore",
    poId: "po_004",
    status: "APPROVED",
    issueDate: iso(-1),
    dueDate: iso(29),
    subtotal: 14512,
    taxAmount: 1088,
    totalAmount: 15600,
    currency: "NGN",
    paidAmount: 0,
    balance: 15600,
    notes: "Network switches and access points.",
    attachments: [],
    approvedById: "usr_fatima",
    approvedAt: iso(-0.5),
    createdAt: iso(-1),
  },
  {
    id: "inv_005",
    organizationId: "org_apex",
    invoiceNumber: "INV-2026-0005",
    vendorId: "vnd_primecement",
    poId: "po_005",
    status: "OVERDUE",
    issueDate: iso(-15),
    dueDate: iso(-1),
    subtotal: 22791,
    taxAmount: 1709,
    totalAmount: 24500,
    currency: "NGN",
    paidAmount: 0,
    balance: 24500,
    notes: "Cement supply — overdue for payment.",
    attachments: [],
    createdAt: iso(-15),
  },
  {
    id: "inv_006",
    organizationId: "org_apex",
    invoiceNumber: "INV-2026-0006",
    vendorId: "vnd_dangote_cement",
    poId: "po_006",
    status: "SUBMITTED",
    issueDate: iso(-0.5),
    dueDate: iso(29.5),
    subtotal: 18605,
    taxAmount: 1395,
    totalAmount: 20000,
    currency: "NGN",
    paidAmount: 0,
    balance: 20000,
    notes: "Bulk cement procurement — strategic partner.",
    attachments: [],
    createdAt: iso(-0.5),
  },
];

// ---------------------------------------------------------------------------
// Payments
// ---------------------------------------------------------------------------
export const seedPayments: Payment[] = [
  {
    id: "pay_001",
    organizationId: "org_apex",
    paymentNumber: "PAY-2026-0001",
    invoiceId: "inv_001",
    vendorId: "vnd_steelworks",
    amount: 41387.5,
    currency: "NGN",
    method: "BANK_TRANSFER",
    status: "COMPLETED",
    paymentDate: iso(-5),
    reference: "TRF-0012345678",
    notes: "Full payment for steel rebar delivery.",
    processedById: "usr_fatima",
    createdAt: iso(-5),
  },
  {
    id: "pay_002",
    organizationId: "org_apex",
    paymentNumber: "PAY-2026-0002",
    invoiceId: "inv_002",
    vendorId: "vnd_officedirect",
    amount: 8200,
    currency: "NGN",
    method: "BANK_TRANSFER",
    status: "COMPLETED",
    paymentDate: iso(-18),
    reference: "TRF-0012345679",
    notes: "Office supplies payment.",
    processedById: "usr_fatima",
    createdAt: iso(-18),
  },
  {
    id: "pay_003",
    organizationId: "org_apex",
    paymentNumber: "PAY-2026-0003",
    invoiceId: "inv_005",
    vendorId: "vnd_primecement",
    amount: 24500,
    currency: "NGN",
    method: "BANK_TRANSFER",
    status: "PENDING",
    paymentDate: iso(0),
    notes: "Payment scheduled for overdue cement invoice.",
    processedById: "usr_fatima",
    createdAt: iso(0),
  },
];

// ---------------------------------------------------------------------------
// Contracts
// ---------------------------------------------------------------------------
export const seedContracts: Contract[] = [
  {
    id: "ctr_001",
    organizationId: "org_apex",
    contractNumber: "CTR-2026-0001",
    title: "Annual HVAC Maintenance Contract",
    vendorId: "vnd_arcticair",
    status: "ACTIVE",
    startDate: iso(-30),
    endDate: iso(335),
    value: 17500,
    currency: "NGN",
    autoRenew: true,
    renewalNoticeDays: 60,
    slaTerms: "4-hour emergency response time, quarterly preventive maintenance, 15% discount on replacement parts.",
    description: "Comprehensive annual HVAC maintenance contract covering Lagos HQ, Abuja Office, and Port Harcourt Plant.",
    tags: ["hvac", "maintenance", "annual"],
    attachments: [{ name: "hvac-contract-2026.pdf", size: "1.2 MB" }],
    versions: [
      { version: 1, modifiedAt: iso(-30), modifiedBy: "usr_tunde", reason: "Initial contract signed" },
    ],
    createdAt: iso(-30),
    updatedAt: iso(-30),
  },
  {
    id: "ctr_002",
    organizationId: "org_apex",
    contractNumber: "CTR-2025-0008",
    title: "Steel Supply Framework Agreement",
    vendorId: "vnd_steelworks",
    status: "ACTIVE",
    startDate: iso(-180),
    endDate: iso(15),
    value: 250000,
    currency: "NGN",
    autoRenew: false,
    renewalNoticeDays: 30,
    slaTerms: "Delivery within 7 days of PO, quality guarantee per ASTM standards, 5% volume discount on orders >10 tonnes.",
    description: "Framework agreement for steel supply to all construction projects.",
    tags: ["steel", "construction", "framework"],
    attachments: [{ name: "steel-framework-2025.pdf", size: "2.1 MB" }],
    versions: [
      { version: 1, modifiedAt: iso(-180), modifiedBy: "usr_tunde", reason: "Initial agreement" },
      { version: 2, modifiedAt: iso(-90), modifiedBy: "usr_tunde", reason: "Updated pricing schedule" },
    ],
    createdAt: iso(-180),
    updatedAt: iso(-90),
  },
  {
    id: "ctr_003",
    organizationId: "org_apex",
    contractNumber: "CTR-2025-0003",
    title: "IT Equipment Supply Agreement",
    vendorId: "vnd_techcore",
    status: "EXPIRING",
    startDate: iso(-300),
    endDate: iso(20),
    value: 120000,
    currency: "NGN",
    autoRenew: true,
    renewalNoticeDays: 45,
    slaTerms: "Next-business-day delivery on stocked items, 3-year warranty, free setup and configuration.",
    description: "Preferred supplier agreement for IT equipment and peripherals.",
    tags: ["it", "equipment", "preferred"],
    attachments: [{ name: "techcore-agreement.pdf", size: "850 KB" }],
    versions: [
      { version: 1, modifiedAt: iso(-300), modifiedBy: "usr_amina", reason: "Initial agreement" },
    ],
    createdAt: iso(-300),
    updatedAt: iso(-300),
  },
  {
    id: "ctr_004",
    organizationId: "org_apex",
    contractNumber: "CTR-2024-0012",
    title: "Logistics Services Contract",
    vendorId: "vnd_logifleet",
    status: "EXPIRED",
    startDate: iso(-400),
    endDate: iso(-5),
    value: 45000,
    currency: "NGN",
    autoRenew: false,
    renewalNoticeDays: 30,
    slaTerms: "Port-to-site delivery within 48 hours, GPS tracking, insurance coverage up to $50k per shipment.",
    description: "Logistics services for port-to-site deliveries. Contract expired — under renegotiation.",
    tags: ["logistics", "freight"],
    attachments: [],
    versions: [
      { version: 1, modifiedAt: iso(-400), modifiedBy: "usr_tunde", reason: "Initial agreement" },
    ],
    createdAt: iso(-400),
    updatedAt: iso(-400),
  },
  {
    id: "ctr_005",
    organizationId: "org_apex",
    contractNumber: "CTR-2026-0002",
    title: "Strategic Cement Supply Agreement",
    vendorId: "vnd_dangote_cement",
    status: "ACTIVE",
    startDate: iso(-60),
    endDate: iso(305),
    value: 500000,
    currency: "NGN",
    autoRenew: true,
    renewalNoticeDays: 90,
    slaTerms: "Volume discount pricing, free delivery to all sites, priority allocation during peak demand.",
    description: "Strategic partnership for bulk cement supply across all construction projects.",
    tags: ["cement", "strategic", "construction"],
    attachments: [{ name: "dangote-strategic-agreement.pdf", size: "1.8 MB" }],
    versions: [
      { version: 1, modifiedAt: iso(-60), modifiedBy: "usr_amina", reason: "Strategic partnership signed" },
    ],
    createdAt: iso(-60),
    updatedAt: iso(-60),
  },
];

// ---------------------------------------------------------------------------
// Assets
// ---------------------------------------------------------------------------
export const seedAssets: Asset[] = [
  {
    id: "ast_001",
    organizationId: "org_apex",
    assetTag: "AST-IT-0001",
    name: "Dell PowerEdge R750 Server",
    category: "IT_EQUIPMENT",
    serialNumber: "SN-PE750-001234",
    poId: "po_003",
    vendorId: "vnd_techcore",
    assignedToId: "usr_grace",
    departmentId: "dep_it",
    branchId: "br_hq",
    location: "Server Room — Lagos HQ",
    status: "IN_USE",
    purchaseDate: iso(-12),
    purchaseValue: 8500,
    currentValue: 7650,
    currency: "NGN",
    warrantyExpiry: iso(353),
    depreciationRate: 10,
    qrCode: "AST-IT-0001",
    notes: "Primary application server for Lagos HQ.",
    maintenanceHistory: [
      { id: "mh_001", date: iso(-5), type: "PREVENTIVE", description: "Quarterly maintenance — firmware updates, disk check", cost: 0, performedBy: "Grace Adeyemi" },
    ],
    transfers: [
      { id: "tr_001", date: iso(-12), fromLocation: "Receiving", toLocation: "Server Room — Lagos HQ", reason: "Initial deployment" },
    ],
    createdAt: iso(-12),
  },
  {
    id: "ast_002",
    organizationId: "org_apex",
    assetTag: "AST-IT-0002",
    name: "Cisco Catalyst 9300 Switch",
    category: "IT_EQUIPMENT",
    serialNumber: "SN-C9300-567890",
    poId: "po_004",
    vendorId: "vnd_techcore",
    assignedToId: "usr_ngozi",
    departmentId: "dep_it",
    branchId: "br_hq",
    location: "Network Cabinet — Lagos HQ",
    status: "IN_USE",
    purchaseDate: iso(-2),
    purchaseValue: 4500,
    currentValue: 4500,
    currency: "NGN",
    warrantyExpiry: iso(363),
    depreciationRate: 20,
    qrCode: "AST-IT-0002",
    notes: "Core network switch for Lagos HQ refresh.",
    maintenanceHistory: [],
    transfers: [
      { id: "tr_002", date: iso(-2), fromLocation: "Receiving", toLocation: "Network Cabinet — Lagos HQ", reason: "New deployment" },
    ],
    createdAt: iso(-2),
  },
  {
    id: "ast_003",
    organizationId: "org_apex",
    assetTag: "AST-MCH-0001",
    name: "Perkins 250kVA Backup Generator",
    category: "MACHINERY",
    serialNumber: "SN-PK250-789012",
    poId: "po_003",
    vendorId: "vnd_powergen",
    departmentId: "dep_fac",
    branchId: "br_phc",
    location: "Generator House — Plant 2",
    status: "IN_USE",
    purchaseDate: iso(-1),
    purchaseValue: 38000,
    currentValue: 38000,
    currency: "NGN",
    warrantyExpiry: iso(729),
    depreciationRate: 15,
    qrCode: "AST-MCH-0001",
    notes: "Backup power for Plant 2 — critical infrastructure.",
    maintenanceHistory: [],
    transfers: [],
    createdAt: iso(-1),
  },
  {
    id: "ast_004",
    organizationId: "org_apex",
    assetTag: "AST-FUR-0001",
    name: "Executive Conference Table",
    category: "FURNITURE",
    poId: "po_002",
    vendorId: "vnd_officedirect",
    departmentId: "dep_ops",
    branchId: "br_hq",
    location: "Boardroom — Lagos HQ",
    status: "IN_USE",
    purchaseDate: iso(-30),
    purchaseValue: 3200,
    currentValue: 3040,
    currency: "NGN",
    warrantyExpiry: iso(335),
    depreciationRate: 5,
    notes: "12-seater executive boardroom table.",
    maintenanceHistory: [],
    transfers: [],
    createdAt: iso(-30),
  },
  {
    id: "ast_005",
    organizationId: "org_apex",
    assetTag: "AST-IT-0003",
    name: "ThinkPad P16 Workstation #1",
    category: "IT_EQUIPMENT",
    serialNumber: "SN-TP16-345678",
    vendorId: "vnd_techcore",
    assignedToId: "usr_emeka",
    departmentId: "dep_eng",
    branchId: "br_phc",
    location: "Engineering Office — Plant 2",
    status: "ASSIGNED",
    purchaseDate: iso(-90),
    purchaseValue: 2800,
    currentValue: 2100,
    currency: "NGN",
    warrantyExpiry: iso(275),
    depreciationRate: 25,
    notes: "Assigned to Emeka Eze for field engineering work.",
    maintenanceHistory: [
      { id: "mh_002", date: iso(-30), type: "REPAIR", description: "Battery replacement", cost: 180, performedBy: "IT Support" },
    ],
    transfers: [
      { id: "tr_003", date: iso(-90), fromLocation: "IT Storage", toLocation: "Engineering Office — Plant 2", reason: "Assigned to Emeka Eze" },
    ],
    createdAt: iso(-90),
  },
  {
    id: "ast_006",
    organizationId: "org_apex",
    assetTag: "AST-VEH-0001",
    name: "Toyota Hilux — Site Vehicle",
    category: "VEHICLE",
    serialNumber: "VIN-JTEBU14R8J0123456",
    departmentId: "dep_eng",
    branchId: "br_phc",
    location: "Plant 2 Parking",
    status: "IN_USE",
    purchaseDate: iso(-365),
    purchaseValue: 42000,
    currentValue: 31500,
    currency: "NGN",
    warrantyExpiry: iso(-5),
    depreciationRate: 25,
    qrCode: "AST-VEH-0001",
    notes: "Site vehicle for engineering team. Warranty expired — consider extended warranty.",
    maintenanceHistory: [
      { id: "mh_003", date: iso(-60), type: "PREVENTIVE", description: "60,000 km service — oil change, filters, brake check", cost: 450, performedBy: "Toyota Service Center" },
      { id: "mh_004", date: iso(-15), type: "REPAIR", description: "Tire replacement (4x)", cost: 680, performedBy: "Toyota Service Center" },
    ],
    transfers: [],
    createdAt: iso(-365),
  },
];

// ---------------------------------------------------------------------------
// Inventory
// ---------------------------------------------------------------------------
export const seedInventory: InventoryItem[] = [
  {
    id: "inv_item_001",
    organizationId: "org_apex",
    sku: "PPE-HELM-001",
    name: "Safety Helmet (Class B)",
    description: "ANSI-certified industrial hard hats, white, with chin strap",
    category: "Safety Equipment",
    unit: "pcs",
    quantity: 45,
    reorderLevel: 20,
    reorderQty: 50,
    unitCost: 28,
    currency: "NGN",
    location: "Store A — Plant 2",
    binLocation: "A-12-03",
    lastRestockDate: iso(-30),
    supplierId: "vnd_safetync",
    movements: [
      { id: "sm_001", itemId: "inv_item_001", type: "RECEIPT", quantity: 50, balanceAfter: 50, reference: "GR-2026-0001", notes: "Initial stock", performedById: "usr_emeka", createdAt: iso(-30) },
      { id: "sm_002", itemId: "inv_item_001", type: "ISSUE", quantity: 5, balanceAfter: 45, reference: "PR-2026-0002", notes: "Issued to site team", performedById: "usr_emeka", createdAt: iso(-10) },
    ],
    createdAt: iso(-30),
    updatedAt: iso(-10),
  },
  {
    id: "inv_item_002",
    organizationId: "org_apex",
    sku: "PPE-VEST-001",
    name: "High-Visibility Vest",
    description: "Class 2 reflective vests, one-size-fits-all, orange",
    category: "Safety Equipment",
    unit: "pcs",
    quantity: 75,
    reorderLevel: 30,
    reorderQty: 80,
    unitCost: 18,
    currency: "NGN",
    location: "Store A — Plant 2",
    binLocation: "A-12-04",
    lastRestockDate: iso(-30),
    supplierId: "vnd_safetync",
    movements: [
      { id: "sm_003", itemId: "inv_item_002", type: "RECEIPT", quantity: 80, balanceAfter: 80, reference: "GR-2026-0001", performedById: "usr_emeka", createdAt: iso(-30) },
      { id: "sm_004", itemId: "inv_item_002", type: "ISSUE", quantity: 5, balanceAfter: 75, reference: "PR-2026-0002", performedById: "usr_emeka", createdAt: iso(-10) },
    ],
    createdAt: iso(-30),
    updatedAt: iso(-10),
  },
  {
    id: "inv_item_003",
    organizationId: "org_apex",
    sku: "OFC-PAPER-A4",
    name: "A4 Paper (80gsm, 500 sheets/ream)",
    description: "Multi-purpose white printer paper",
    category: "Office Supplies",
    unit: "reams",
    quantity: 8,
    reorderLevel: 50,
    reorderQty: 200,
    unitCost: 6.5,
    currency: "NGN",
    location: "Stationery Store — Lagos HQ",
    binLocation: "S-05-01",
    lastRestockDate: iso(-22),
    supplierId: "vnd_officedirect",
    movements: [
      { id: "sm_005", itemId: "inv_item_003", type: "RECEIPT", quantity: 200, balanceAfter: 200, reference: "GR-2026-0002", performedById: "usr_yusuf", createdAt: iso(-22) },
      { id: "sm_006", itemId: "inv_item_003", type: "ISSUE", quantity: 192, balanceAfter: 8, notes: "Distributed to departments", performedById: "usr_yusuf", createdAt: iso(-5) },
    ],
    createdAt: iso(-22),
    updatedAt: iso(-5),
  },
  {
    id: "inv_item_004",
    organizationId: "org_apex",
    sku: "CON-CEMENT-42",
    name: "Portland Cement Grade 42.5N",
    description: "Bulk cement, 50kg bags, ASTM C150 Type I",
    category: "Construction Materials",
    unit: "bags",
    quantity: 350,
    reorderLevel: 100,
    reorderQty: 500,
    unitCost: 49,
    currency: "NGN",
    location: "Construction Store — Plant 2",
    binLocation: "C-01-01",
    lastRestockDate: iso(-4),
    supplierId: "vnd_primecement",
    movements: [
      { id: "sm_007", itemId: "inv_item_004", type: "RECEIPT", quantity: 500, balanceAfter: 500, reference: "PO-2026-0005", performedById: "usr_emeka", createdAt: iso(-4) },
      { id: "sm_008", itemId: "inv_item_004", type: "ISSUE", quantity: 150, balanceAfter: 350, notes: "Phase 2 construction", performedById: "usr_emeka", createdAt: iso(-2) },
    ],
    createdAt: iso(-4),
    updatedAt: iso(-2),
  },
  {
    id: "inv_item_005",
    organizationId: "org_apex",
    sku: "OFC-TONER-HP414",
    name: "HP 414A Toner Cartridge (Black)",
    description: "Original HP toner, black, ~2,400 page yield",
    category: "Office Supplies",
    unit: "pcs",
    quantity: 3,
    reorderLevel: 10,
    reorderQty: 20,
    unitCost: 95,
    currency: "NGN",
    location: "Stationery Store — Lagos HQ",
    binLocation: "S-03-02",
    lastRestockDate: iso(-22),
    supplierId: "vnd_officedirect",
    movements: [
      { id: "sm_009", itemId: "inv_item_005", type: "RECEIPT", quantity: 20, balanceAfter: 20, reference: "GR-2026-0002", performedById: "usr_yusuf", createdAt: iso(-22) },
      { id: "sm_010", itemId: "inv_item_005", type: "ISSUE", quantity: 17, balanceAfter: 3, notes: "Distributed to printers", performedById: "usr_yusuf", createdAt: iso(-3) },
    ],
    createdAt: iso(-22),
    updatedAt: iso(-3),
  },
];

// ---------------------------------------------------------------------------
// Supplier Portal
// ---------------------------------------------------------------------------
export const seedSupplierPortalUsers: SupplierPortalUser[] = [
  { id: "spu_001", vendorId: "vnd_techcore", email: "ibrahim@techcore-ng.com", contactName: "Ibrahim Mohammed", accessStatus: "ACTIVE", lastLoginAt: iso(-1), createdAt: iso(-90) },
  { id: "spu_002", vendorId: "vnd_safetync", email: "blessing@safetync.com", contactName: "Blessing Okon", accessStatus: "ACTIVE", lastLoginAt: iso(-2), createdAt: iso(-60) },
  { id: "spu_003", vendorId: "vnd_steelworks", email: "olumide@steelworks.africa", contactName: "Olumide Adesanya", accessStatus: "ACTIVE", lastLoginAt: iso(-3), createdAt: iso(-120) },
  { id: "spu_004", vendorId: "vnd_powergen", email: "samuel@powergen.com", contactName: "Samuel Adeyinka", accessStatus: "ACTIVE", lastLoginAt: iso(-5), createdAt: iso(-45) },
  { id: "spu_005", vendorId: "vnd_dangote_cement", email: "ahmed@dangote.com", contactName: "Ahmed Hassan", accessStatus: "ACTIVE", lastLoginAt: iso(-1), createdAt: iso(-30) },
  { id: "spu_006", vendorId: "vnd_officedirect", email: "chioma@officedirect.ng", contactName: "Chioma Eze", accessStatus: "PENDING", createdAt: iso(-2) },
];

export const seedSupplierActivities: SupplierActivity[] = [
  { id: "sa_001", vendorId: "vnd_safetync", type: "QUOTE_SUBMITTED", description: "Submitted quotation for RFQ-2026-0001 (PPE Supply)", referenceId: "rfq_001", createdAt: iso(-0.5) },
  { id: "sa_002", vendorId: "vnd_powergen", type: "QUOTE_SUBMITTED", description: "Submitted quotation for RFQ-2026-0002 (250kVA Generator)", referenceId: "rfq_002", createdAt: iso(-0.2) },
  { id: "sa_003", vendorId: "vnd_steelworks", type: "PAYMENT_RECEIVED", description: "Payment received: PAY-2026-0001 ($41,387.50)", referenceId: "pay_001", createdAt: iso(-5) },
  { id: "sa_004", vendorId: "vnd_dangote_cement", type: "PO_ACKNOWLEDGED", description: "Acknowledged PO-2026-0006 (Bulk Cement)", referenceId: "po_006", createdAt: iso(-0.5) },
  { id: "sa_005", vendorId: "vnd_techcore", type: "INVOICE_SUBMITTED", description: "Submitted invoice INV-2026-0004 ($15,600)", referenceId: "inv_004", createdAt: iso(-1) },
  { id: "sa_006", vendorId: "vnd_primecement", type: "DELIVERY_CONFIRMED", description: "Confirmed delivery for PO-2026-0005", referenceId: "po_005", createdAt: iso(-4) },
];

// ---------------------------------------------------------------------------
// Documents
// ---------------------------------------------------------------------------
export const seedDocuments: DocumentRecord[] = [
  {
    id: "doc_001",
    organizationId: "org_apex",
    name: "Steel Rebar Delivery Receipt",
    category: "DELIVERY_NOTE",
    mimeType: "application/pdf",
    fileSize: "120 KB",
    uploadedById: "usr_emeka",
    tags: ["steel", "delivery", "plant-2"],
    linkedEntityType: "PO",
    linkedEntityId: "po_001",
    versions: [{ version: 1, uploadedAt: iso(-8), uploadedBy: "usr_emeka", size: "120 KB" }],
    currentVersion: 1,
    description: "Signed delivery receipt for steel rebar delivery to Plant 2.",
    createdAt: iso(-8),
    updatedAt: iso(-8),
  },
  {
    id: "doc_002",
    organizationId: "org_apex",
    name: "Annual HVAC Maintenance Contract",
    category: "CONTRACT",
    mimeType: "application/pdf",
    fileSize: "1.2 MB",
    uploadedById: "usr_tunde",
    tags: ["hvac", "maintenance", "annual"],
    linkedEntityType: "CONTRACT",
    linkedEntityId: "ctr_001",
    versions: [{ version: 1, uploadedAt: iso(-30), uploadedBy: "usr_tunde", size: "1.2 MB" }],
    currentVersion: 1,
    description: "Signed HVAC maintenance contract with Arctic Air.",
    createdAt: iso(-30),
    updatedAt: iso(-30),
  },
  {
    id: "doc_003",
    organizationId: "org_apex",
    name: "SteelWorks Invoice — Jan 2026",
    category: "INVOICE",
    mimeType: "application/pdf",
    fileSize: "245 KB",
    uploadedById: "usr_fatima",
    tags: ["invoice", "steel"],
    linkedEntityType: "INVOICE",
    linkedEntityId: "inv_001",
    versions: [{ version: 1, uploadedAt: iso(-7), uploadedBy: "usr_fatima", size: "245 KB" }],
    currentVersion: 1,
    description: "Invoice from SteelWorks for steel rebar delivery.",
    createdAt: iso(-7),
    updatedAt: iso(-7),
  },
  {
    id: "doc_004",
    organizationId: "org_apex",
    name: "Procurement Policy 2026",
    category: "POLICY",
    mimeType: "application/pdf",
    fileSize: "450 KB",
    uploadedById: "usr_amina",
    tags: ["policy", "procurement", "2026"],
    versions: [
      { version: 1, uploadedAt: iso(-60), uploadedBy: "usr_amina", size: "420 KB" },
      { version: 2, uploadedAt: iso(-10), uploadedBy: "usr_amina", size: "450 KB" },
    ],
    currentVersion: 2,
    description: "Organization-wide procurement policy. Updated with new approval thresholds.",
    createdAt: iso(-60),
    updatedAt: iso(-10),
  },
  {
    id: "doc_005",
    organizationId: "org_apex",
    name: "TechCore ISO 9001 Certificate",
    category: "CERTIFICATE",
    mimeType: "application/pdf",
    fileSize: "198 KB",
    uploadedById: "usr_tunde",
    tags: ["iso", "quality", "certificate"],
    linkedEntityType: "VENDOR",
    linkedEntityId: "vnd_techcore",
    versions: [{ version: 1, uploadedAt: iso(-120), uploadedBy: "usr_tunde", size: "198 KB" }],
    currentVersion: 1,
    description: "ISO 9001 quality management certificate for TechCore Distributors.",
    createdAt: iso(-120),
    updatedAt: iso(-120),
  },
  {
    id: "doc_006",
    organizationId: "org_apex",
    name: "Generator Installation Report",
    category: "ATTACHMENT",
    mimeType: "application/pdf",
    fileSize: "320 KB",
    uploadedById: "usr_emeka",
    tags: ["generator", "installation", "plant-2"],
    linkedEntityType: "PO",
    linkedEntityId: "po_003",
    versions: [{ version: 1, uploadedAt: iso(-1), uploadedBy: "usr_emeka", size: "320 KB" }],
    currentVersion: 1,
    description: "Installation and commissioning report for Plant 2 backup generator.",
    createdAt: iso(-1),
    updatedAt: iso(-1),
  },
];
