// NextMav Procure — Realistic seed data
// Comprehensive demo data for "Apex Industries Ltd." showing the full P2P lifecycle.

import type {
  ActivityLog,
  Branch,
  Department,
  Notification,
  Organization,
  PurchaseOrder,
  PurchaseRequest,
  RFQ,
  User,
  Vendor,
} from "./types";

export const seedOrganization: Organization = {
  id: "org_apex",
  name: "Apex Industries",
  legalName: "Apex Industries Ltd.",
  industry: "Manufacturing & Construction",
  country: "Nigeria",
  currency: "USD",
  taxId: "TIN-NG-20194832",
};

export const seedBranches: Branch[] = [
  {
    id: "br_hq",
    organizationId: "org_apex",
    name: "Headquarters — Lagos",
    address: "12 Adeola Odeku Street, Victoria Island",
    city: "Lagos",
    country: "Nigeria",
  },
  {
    id: "br_abuja",
    organizationId: "org_apex",
    name: "Abuja Regional Office",
    address: "Plot 788, Central Business District",
    city: "Abuja",
    country: "Nigeria",
  },
  {
    id: "br_phc",
    organizationId: "org_apex",
    name: "Port Harcourt Plant",
    address: "Trans-Amadi Industrial Layout",
    city: "Port Harcourt",
    country: "Nigeria",
  },
];

export const seedDepartments: Department[] = [
  { id: "dep_eng", organizationId: "org_apex", branchId: "br_phc", name: "Engineering", budget: 480000, spent: 218500 },
  { id: "dep_ops", organizationId: "org_apex", branchId: "br_hq", name: "Operations", budget: 360000, spent: 142800 },
  { id: "dep_it", organizationId: "org_apex", branchId: "br_hq", name: "Information Technology", budget: 240000, spent: 89600 },
  { id: "dep_fin", organizationId: "org_apex", branchId: "br_hq", name: "Finance", budget: 120000, spent: 41200 },
  { id: "dep_hr", organizationId: "org_apex", branchId: "br_hq", name: "Human Resources", budget: 90000, spent: 32100 },
  { id: "dep_mkt", organizationId: "org_apex", branchId: "br_abuja", name: "Marketing & Sales", budget: 180000, spent: 67400 },
  { id: "dep_fac", organizationId: "org_apex", branchId: "br_phc", name: "Facilities", budget: 150000, spent: 58200 },
];

export const seedUsers: User[] = [
  {
    id: "usr_amina",
    organizationId: "org_apex",
    branchId: "br_hq",
    departmentId: "dep_eng",
    email: "amina.okafor@apex.com",
    name: "Amina Okafor",
    role: "SUPER_ADMIN",
    jobTitle: "Chief Operating Officer",
    phone: "+234 803 555 0101",
    avatarColor: "bg-emerald-500",
    initials: "AO",
  },
  {
    id: "usr_tunde",
    organizationId: "org_apex",
    branchId: "br_hq",
    departmentId: "dep_ops",
    email: "tunde.bello@apex.com",
    name: "Tunde Bello",
    role: "PROCUREMENT_MANAGER",
    jobTitle: "Head of Procurement",
    phone: "+234 803 555 0102",
    avatarColor: "bg-amber-500",
    initials: "TB",
  },
  {
    id: "usr_fatima",
    organizationId: "org_apex",
    branchId: "br_hq",
    departmentId: "dep_fin",
    email: "fatima.sani@apex.com",
    name: "Fatima Sani",
    role: "FINANCE_OFFICER",
    jobTitle: "Senior Finance Officer",
    phone: "+234 803 555 0103",
    avatarColor: "bg-rose-500",
    initials: "FS",
  },
  {
    id: "usr_chidi",
    organizationId: "org_apex",
    branchId: "br_phc",
    departmentId: "dep_eng",
    email: "chidi.nwosu@apex.com",
    name: "Chidi Nwosu",
    role: "DEPARTMENT_MANAGER",
    jobTitle: "Engineering Manager",
    phone: "+234 803 555 0104",
    avatarColor: "bg-sky-500",
    initials: "CN",
  },
  {
    id: "usr_grace",
    organizationId: "org_apex",
    branchId: "br_hq",
    departmentId: "dep_it",
    email: "grace.adeyemi@apex.com",
    name: "Grace Adeyemi",
    role: "DEPARTMENT_MANAGER",
    jobTitle: "IT Manager",
    phone: "+234 803 555 0105",
    avatarColor: "bg-violet-500",
    initials: "GA",
  },
  {
    id: "usr_emeka",
    organizationId: "org_apex",
    branchId: "br_phc",
    departmentId: "dep_eng",
    email: "emeka.eze@apex.com",
    name: "Emeka Eze",
    role: "EMPLOYEE",
    jobTitle: "Site Engineer",
    phone: "+234 803 555 0106",
    avatarColor: "bg-teal-500",
    initials: "EE",
  },
  {
    id: "usr_ngozi",
    organizationId: "org_apex",
    branchId: "br_hq",
    departmentId: "dep_it",
    email: "ngozi.obi@apex.com",
    name: "Ngozi Obi",
    role: "EMPLOYEE",
    jobTitle: "IT Specialist",
    phone: "+234 803 555 0107",
    avatarColor: "bg-orange-500",
    initials: "NO",
  },
  {
    id: "usr_yusuf",
    organizationId: "org_apex",
    branchId: "br_hq",
    departmentId: "dep_ops",
    email: "yusuf.aliyu@apex.com",
    name: "Yusuf Aliyu",
    role: "EMPLOYEE",
    jobTitle: "Operations Analyst",
    phone: "+234 803 555 0108",
    avatarColor: "bg-cyan-500",
    initials: "YA",
  },
  {
    id: "usr_funke",
    organizationId: "org_apex",
    branchId: "br_hq",
    email: "funke.adewale@apex.com",
    name: "Funke Adewale",
    role: "AUDITOR",
    jobTitle: "Internal Auditor",
    phone: "+234 803 555 0109",
    avatarColor: "bg-slate-500",
    initials: "FA",
  },
];

export const seedVendors: Vendor[] = [
  {
    id: "vnd_techcore",
    organizationId: "org_apex",
    companyName: "TechCore Distributors Ltd.",
    contactPerson: "Ibrahim Mohammed",
    email: "sales@techcore-ng.com",
    phone: "+234 805 234 1100",
    address: "14 Computer Village, Ikeja, Lagos",
    category: "IT Equipment",
    taxNumber: "TIN-TC-193820",
    bankName: "First Bank Nigeria",
    bankAccount: "3031xxxxxx92",
    rating: 4.7,
    status: "ACTIVE",
    totalOrders: 24,
    totalValue: 184500,
    createdAt: "2024-03-12T09:00:00Z",
  },
  {
    id: "vnd_safetync",
    organizationId: "org_apex",
    companyName: "SafetyNig Industrial Supplies",
    contactPerson: "Blessing Okon",
    email: "info@safetync.com",
    phone: "+234 805 999 2233",
    address: "78 Industrial Layout, Trans-Amadi, Port Harcourt",
    category: "Safety Equipment",
    taxNumber: "TIN-SN-445120",
    bankName: "Access Bank",
    bankAccount: "0091xxxxxx34",
    rating: 4.5,
    status: "ACTIVE",
    totalOrders: 18,
    totalValue: 96200,
    createdAt: "2024-01-25T09:00:00Z",
  },
  {
    id: "vnd_steelworks",
    organizationId: "org_apex",
    companyName: "SteelWorks Africa Ltd.",
    contactPerson: "Olumide Adesanya",
    email: "quotes@steelworks.africa",
    phone: "+234 807 112 8890",
    address: "Plot 45, Apapa Industrial Zone, Lagos",
    category: "Construction Materials",
    taxNumber: "TIN-SW-778301",
    bankName: "Zenith Bank",
    bankAccount: "1015xxxxxx88",
    rating: 4.3,
    status: "ACTIVE",
    totalOrders: 31,
    totalValue: 412000,
    createdAt: "2023-09-18T09:00:00Z",
  },
  {
    id: "vnd_officedirect",
    organizationId: "org_apex",
    companyName: "OfficeDirect Nigeria",
    contactPerson: "Chioma Eze",
    email: "orders@officedirect.ng",
    phone: "+234 809 445 6677",
    address: "21 Allen Avenue, Ikeja, Lagos",
    category: "Office Supplies",
    taxNumber: "TIN-OD-220914",
    bankName: "GTBank",
    bankAccount: "0123xxxxxx76",
    rating: 4.6,
    status: "ACTIVE",
    totalOrders: 42,
    totalValue: 67800,
    createdAt: "2023-05-08T09:00:00Z",
  },
  {
    id: "vnd_powergen",
    organizationId: "org_apex",
    companyName: "PowerGen Solutions",
    contactPerson: "Samuel Adeyinka",
    email: "sales@powergen.com",
    phone: "+234 802 778 1100",
    address: "5 Marina Road, Lagos Island",
    category: "Electrical & Power",
    taxNumber: "TIN-PG-556720",
    bankName: "UBA",
    bankAccount: "2155xxxxxx09",
    rating: 4.4,
    status: "ACTIVE",
    totalOrders: 16,
    totalValue: 138900,
    createdAt: "2024-02-14T09:00:00Z",
  },
  {
    id: "vnd_logifleet",
    organizationId: "org_apex",
    companyName: "LogiFleet Logistics",
    contactPerson: "Hauwa Bello",
    email: "contact@logifleet.ng",
    phone: "+234 806 223 4478",
    address: "Apapa Port Complex, Lagos",
    category: "Logistics",
    taxNumber: "TIN-LF-991023",
    bankName: "Stanbic IBTC",
    bankAccount: "0009xxxxxx55",
    rating: 4.1,
    status: "ACTIVE",
    totalOrders: 9,
    totalValue: 52300,
    createdAt: "2024-06-30T09:00:00Z",
  },
  {
    id: "vnd_globalequip",
    organizationId: "org_apex",
    companyName: "Global Equipment Trading",
    contactPerson: "Daniel Park",
    email: "daniel@globalequip.com",
    phone: "+27 11 555 4400",
    address: "Sandton City, Johannesburg, South Africa",
    category: "Industrial Equipment",
    taxNumber: "TIN-GE-SA-22001",
    bankName: "Standard Bank",
    bankAccount: "62xxxxxx01",
    rating: 4.8,
    status: "PROSPECTIVE",
    totalOrders: 2,
    totalValue: 84000,
    createdAt: "2025-11-04T09:00:00Z",
  },
  {
    id: "vnd_primecement",
    organizationId: "org_apex",
    companyName: "Prime Cement Distributors",
    contactPerson: "Rasaq Olaniyan",
    email: "sales@primecement.ng",
    phone: "+234 803 447 8821",
    address: "Shagamu Industrial Road, Ogun State",
    category: "Construction Materials",
    taxNumber: "TIN-PC-664200",
    bankName: "First Bank Nigeria",
    bankAccount: "3044xxxxxx11",
    rating: 4.0,
    status: "ACTIVE",
    totalOrders: 14,
    totalValue: 92700,
    createdAt: "2024-08-22T09:00:00Z",
  },
  {
    id: "vnd_arcticair",
    organizationId: "org_apex",
    companyName: "Arctic Air HVAC Systems",
    contactPerson: "Lola Martins",
    email: "lola@arcticair.com",
    phone: "+234 809 223 5566",
    address: "34 Adeyemo Alakija, Victoria Island, Lagos",
    category: "HVAC & Cooling",
    taxNumber: "TIN-AA-337812",
    bankName: "GTBank",
    bankAccount: "0222xxxxxx83",
    rating: 3.9,
    status: "PROSPECTIVE",
    totalOrders: 0,
    totalValue: 0,
    createdAt: "2026-01-15T09:00:00Z",
  },
  {
    id: "vnd_legacytools",
    organizationId: "org_apex",
    companyName: "Legacy Tools Co.",
    contactPerson: "Victor Obi",
    email: "victor@legacytools.com",
    phone: "+234 802 119 4400",
    address: "Plot 12, Emene Industrial Estate, Enugu",
    category: "Industrial Equipment",
    taxNumber: "TIN-LT-872340",
    bankName: "Access Bank",
    bankAccount: "0088xxxxxx22",
    rating: 2.4,
    status: "BLACKLISTED",
    totalOrders: 3,
    totalValue: 14500,
    createdAt: "2024-04-10T09:00:00Z",
  },
];

const now = new Date();
const iso = (offsetDays: number) =>
  new Date(now.getTime() + offsetDays * 24 * 60 * 60 * 1000).toISOString();

export const seedRequests: PurchaseRequest[] = [
  {
    id: "req_001",
    organizationId: "org_apex",
    requestNumber: "PR-2026-0001",
    title: "Industrial Laptops for Engineering Team",
    departmentId: "dep_eng",
    requestedById: "usr_emeka",
    status: "UNDER_REVIEW",
    priority: "HIGH",
    businessJustification:
      "Three site engineers need rugged laptops for field inspections and real-time reporting. Current units are 4+ years old and frequently fail on site, causing reporting delays of 2-3 days per incident.",
    neededByDate: iso(14),
    totalEstimated: 8400,
    currency: "USD",
    attachments: [
      { name: "spec-sheet-thinkpad.pdf", size: "245 KB" },
      { name: "current-fleet-condition.docx", size: "180 KB" },
    ],
    lineItems: [
      {
        id: "li_001_1",
        itemName: "ThinkPad P16 Gen 2 (Rugged)",
        description: "16\" mobile workstation, i9, 32GB RAM, 1TB SSD, RTX A2000",
        quantity: 3,
        unit: "units",
        estimatedCost: 2800,
      },
    ],
    approvals: [
      {
        id: "ap_001_1",
        requestId: "req_001",
        stage: "DEPARTMENT_MANAGER",
        approverId: "usr_chidi",
        decision: "APPROVED",
        comment: "Approved — these are critical for the Q3 site expansion. Please expedite.",
        decidedAt: iso(-3),
        createdAt: iso(-5),
      },
      {
        id: "ap_001_2",
        requestId: "req_001",
        stage: "FINANCE",
        approverId: "usr_fatima",
        decision: "PENDING",
        createdAt: iso(-3),
      },
    ],
    createdAt: iso(-5),
    updatedAt: iso(-3),
    submittedAt: iso(-5),
  },
  {
    id: "req_002",
    organizationId: "org_apex",
    requestNumber: "PR-2026-0002",
    title: "Personal Protective Equipment (PPE) — Q3 Restock",
    departmentId: "dep_fac",
    requestedById: "usr_yusuf",
    status: "APPROVED",
    priority: "URGENT",
    businessJustification:
      "PPE stock is critically low following the Plant 2 expansion. Mandatory compliance with HSE policy requires quarterly restock. Current stock will be depleted within 10 days at current usage rates.",
    neededByDate: iso(7),
    totalEstimated: 12650,
    currency: "USD",
    attachments: [{ name: "hse-compliance-checklist.pdf", size: "320 KB" }],
    lineItems: [
      {
        id: "li_002_1",
        itemName: "Safety Helmets (Class B)",
        description: "ANSI-certified industrial hard hats, white, with chin strap",
        quantity: 50,
        unit: "pcs",
        estimatedCost: 28,
      },
      {
        id: "li_002_2",
        itemName: "High-Visibility Vests",
        description: "Class 2 reflective vests, one-size-fits-all, orange",
        quantity: 80,
        unit: "pcs",
        estimatedCost: 18,
      },
      {
        id: "li_002_3",
        itemName: "Steel-Toe Safety Boots",
        description: "Size 7-12 mixed, oil-resistant sole, electrical hazard protection",
        quantity: 30,
        unit: "pairs",
        estimatedCost: 95,
      },
      {
        id: "li_002_4",
        itemName: "Cut-Resistant Gloves (Level 5)",
        description: "ANSI A5 cut-resistant, polyurethane coated, breathable",
        quantity: 100,
        unit: "pairs",
        estimatedCost: 12,
      },
    ],
    approvals: [
      {
        id: "ap_002_1",
        requestId: "req_002",
        stage: "DEPARTMENT_MANAGER",
        approverId: "usr_chidi",
        decision: "APPROVED",
        comment: "Approved — HSE compliance is non-negotiable.",
        decidedAt: iso(-2),
        createdAt: iso(-4),
      },
      {
        id: "ap_002_2",
        requestId: "req_002",
        stage: "FINANCE",
        approverId: "usr_fatima",
        decision: "APPROVED",
        comment: "Approved within Q3 HSE budget. Please proceed to RFQ.",
        decidedAt: iso(-1),
        createdAt: iso(-2),
      },
      {
        id: "ap_002_3",
        requestId: "req_002",
        stage: "PROCUREMENT",
        approverId: "usr_tunde",
        decision: "APPROVED",
        comment: "Procurement will issue RFQ to 3 safety equipment vendors.",
        decidedAt: iso(-1),
        createdAt: iso(-1),
      },
    ],
    createdAt: iso(-4),
    updatedAt: iso(-1),
    submittedAt: iso(-4),
  },
  {
    id: "req_003",
    organizationId: "org_apex",
    requestNumber: "PR-2026-0003",
    title: "Server Rack & Networking Equipment for New Abuja Office",
    departmentId: "dep_it",
    requestedById: "usr_ngozi",
    status: "SUBMITTED",
    priority: "MEDIUM",
    businessJustification:
      "New Abuja regional office requires a complete server rack and networking setup to support 60 staff. Currently no IT infrastructure exists at the new location.",
    neededByDate: iso(30),
    totalEstimated: 24500,
    currency: "USD",
    attachments: [
      { name: "abuja-office-network-diagram.pdf", size: "1.2 MB" },
      { name: "vendor-preliminary-quotes.xlsx", size: "45 KB" },
    ],
    lineItems: [
      {
        id: "li_003_1",
        itemName: "42U Server Rack (Locking)",
        description: "42U cabinet, 600x1000mm, glass front door, dual fans",
        quantity: 2,
        unit: "units",
        estimatedCost: 1200,
      },
      {
        id: "li_003_2",
        itemName: "Cisco Catalyst 9300 Switch",
        description: "48-port PoE+ enterprise switch, stackable",
        quantity: 3,
        unit: "units",
        estimatedCost: 4500,
      },
      {
        id: "li_003_3",
        itemName: "UPS 5kVA Online Double-Conversion",
        description: "Rack-mount UPS, 5kVA, with network management card",
        quantity: 2,
        unit: "units",
        estimatedCost: 3200,
      },
      {
        id: "li_003_4",
        itemName: "Patch Panels & Cables",
        description: "Cat6 patch panels, fiber, copper patch cords complete kit",
        quantity: 1,
        unit: "lot",
        estimatedCost: 3900,
      },
    ],
    approvals: [
      {
        id: "ap_003_1",
        requestId: "req_003",
        stage: "DEPARTMENT_MANAGER",
        approverId: "usr_grace",
        decision: "PENDING",
        createdAt: iso(-2),
      },
    ],
    createdAt: iso(-2),
    updatedAt: iso(-2),
    submittedAt: iso(-2),
  },
  {
    id: "req_004",
    organizationId: "org_apex",
    requestNumber: "PR-2026-0004",
    title: "Steel Rebar — Plant 2 Construction Phase 2",
    departmentId: "dep_eng",
    requestedById: "usr_emeka",
    status: "COMPLETED",
    priority: "URGENT",
    businessJustification:
      "Phase 2 of Plant 2 construction requires 50 tonnes of steel rebar for foundation reinforcement. Project timeline mandates delivery by month-end.",
    neededByDate: iso(-5),
    totalEstimated: 38500,
    currency: "USD",
    attachments: [{ name: "phase-2-structural-drawings.pdf", size: "3.4 MB" }],
    lineItems: [
      {
        id: "li_004_1",
        itemName: "Steel Rebar Grade 60 — 16mm",
        description: "ASTM A615 Grade 60, 16mm diameter, 12m lengths",
        quantity: 30,
        unit: "tonnes",
        estimatedCost: 850,
      },
      {
        id: "li_004_2",
        itemName: "Steel Rebar Grade 60 — 20mm",
        description: "ASTM A615 Grade 60, 20mm diameter, 12m lengths",
        quantity: 20,
        unit: "tonnes",
        estimatedCost: 920,
      },
    ],
    approvals: [
      {
        id: "ap_004_1",
        requestId: "req_004",
        stage: "DEPARTMENT_MANAGER",
        approverId: "usr_chidi",
        decision: "APPROVED",
        comment: "Critical for project timeline.",
        decidedAt: iso(-25),
        createdAt: iso(-27),
      },
      {
        id: "ap_004_2",
        requestId: "req_004",
        stage: "FINANCE",
        approverId: "usr_fatima",
        decision: "APPROVED",
        decidedAt: iso(-24),
        createdAt: iso(-25),
      },
      {
        id: "ap_004_3",
        requestId: "req_004",
        stage: "PROCUREMENT",
        approverId: "usr_tunde",
        decision: "APPROVED",
        comment: "PO issued to SteelWorks Africa.",
        decidedAt: iso(-23),
        createdAt: iso(-24),
      },
    ],
    createdAt: iso(-27),
    updatedAt: iso(-8),
    submittedAt: iso(-27),
  },
  {
    id: "req_005",
    organizationId: "org_apex",
    requestNumber: "PR-2026-0005",
    title: "Marketing Team Laptops — Q1 Refresh",
    departmentId: "dep_mkt",
    requestedById: "usr_yusuf",
    status: "REJECTED",
    priority: "LOW",
    businessJustification:
      "Marketing team requesting 5 new MacBook Pro units for video editing and design work.",
    neededByDate: iso(45),
    totalEstimated: 12500,
    currency: "USD",
    attachments: [],
    lineItems: [
      {
        id: "li_005_1",
        itemName: "MacBook Pro 14\" M3 Pro",
        description: "14-inch, M3 Pro chip, 18GB unified memory, 512GB SSD",
        quantity: 5,
        unit: "units",
        estimatedCost: 2500,
      },
    ],
    approvals: [
      {
        id: "ap_005_1",
        requestId: "req_005",
        stage: "FINANCE",
        approverId: "usr_fatima",
        decision: "REJECTED",
        comment: "Rejected — current FY IT budget exhausted. Recommend revisiting in Q2 2027 with formal business case.",
        decidedAt: iso(-6),
        createdAt: iso(-8),
      },
    ],
    createdAt: iso(-8),
    updatedAt: iso(-6),
    submittedAt: iso(-8),
  },
  {
    id: "req_006",
    organizationId: "org_apex",
    requestNumber: "PR-2026-0006",
    title: "Backup Generator — 250kVA for Plant 2",
    departmentId: "dep_fac",
    requestedById: "usr_yusuf",
    status: "UNDER_REVIEW",
    priority: "HIGH",
    businessJustification:
      "Plant 2 has experienced 14 power outages in the last 60 days, each causing 3-6 hours of downtime. A 250kVA backup generator is essential to maintain production continuity.",
    neededByDate: iso(21),
    totalEstimated: 42000,
    currency: "USD",
    attachments: [
      { name: "power-outage-log-2026.xlsx", size: "78 KB" },
      { name: "generator-spec-requirements.pdf", size: "410 KB" },
    ],
    lineItems: [
      {
        id: "li_006_1",
        itemName: "Perkins 250kVA Diesel Generator",
        description: "250kVA standby, sound-attenuated canopy, ATS panel, 1000L fuel tank",
        quantity: 1,
        unit: "unit",
        estimatedCost: 38000,
      },
      {
        id: "li_006_2",
        itemName: "Installation & Commissioning",
        description: "Site installation, electrical connection, load testing, commissioning",
        quantity: 1,
        unit: "lot",
        estimatedCost: 4000,
      },
    ],
    approvals: [
      {
        id: "ap_006_1",
        requestId: "req_006",
        stage: "DEPARTMENT_MANAGER",
        approverId: "usr_chidi",
        decision: "APPROVED",
        comment: "Critical infrastructure. Plant 2 cannot sustain further outages.",
        decidedAt: iso(-2),
        createdAt: iso(-3),
      },
      {
        id: "ap_006_2",
        requestId: "req_006",
        stage: "FINANCE",
        approverId: "usr_fatima",
        decision: "PENDING",
        createdAt: iso(-2),
      },
    ],
    createdAt: iso(-3),
    updatedAt: iso(-2),
    submittedAt: iso(-3),
  },
  {
    id: "req_007",
    organizationId: "org_apex",
    requestNumber: "PR-2026-0007",
    title: "Office Furniture — Abuja Office Setup",
    departmentId: "dep_ops",
    requestedById: "usr_yusuf",
    status: "DRAFT",
    priority: "MEDIUM",
    businessJustification:
      "60 ergonomic workstations, 4 meeting room setups, and reception furniture for the new Abuja office opening.",
    neededByDate: iso(40),
    totalEstimated: 38200,
    currency: "USD",
    attachments: [{ name: "office-layout-final.pdf", size: "2.1 MB" }],
    lineItems: [
      {
        id: "li_007_1",
        itemName: "Ergonomic Office Chair",
        description: "Mesh back, adjustable lumbar, 4D armrests, BIFMA certified",
        quantity: 60,
        unit: "pcs",
        estimatedCost: 280,
      },
      {
        id: "li_007_2",
        itemName: "Electric Sit-Stand Desk",
        description: "160x80cm, dual motor, 4 memory presets, oak top",
        quantity: 60,
        unit: "pcs",
        estimatedCost: 320,
      },
      {
        id: "li_007_3",
        itemName: "Meeting Room Table (8-seater)",
        description: "240x120cm, modular, with cable management",
        quantity: 4,
        unit: "pcs",
        estimatedCost: 850,
      },
    ],
    approvals: [],
    createdAt: iso(-1),
    updatedAt: iso(-1),
  },
  {
    id: "req_008",
    organizationId: "org_apex",
    requestNumber: "PR-2026-0008",
    title: "HVAC Maintenance Contract Renewal",
    departmentId: "dep_fac",
    requestedById: "usr_yusuf",
    status: "APPROVED",
    priority: "MEDIUM",
    businessJustification:
      "Annual HVAC maintenance contract expires in 30 days. Renewal ensures continuous coverage across all 3 branches (Lagos HQ, Abuja, Port Harcourt Plant).",
    neededByDate: iso(28),
    totalEstimated: 18000,
    currency: "USD",
    attachments: [],
    lineItems: [
      {
        id: "li_008_1",
        itemName: "Annual HVAC Maintenance Contract",
        description: "Quarterly preventive maintenance, 24/7 emergency response, parts discount, all 3 branches",
        quantity: 1,
        unit: "contract",
        estimatedCost: 18000,
      },
    ],
    approvals: [
      {
        id: "ap_008_1",
        requestId: "req_008",
        stage: "DEPARTMENT_MANAGER",
        approverId: "usr_chidi",
        decision: "APPROVED",
        decidedAt: iso(-10),
        createdAt: iso(-12),
      },
      {
        id: "ap_008_2",
        requestId: "req_008",
        stage: "FINANCE",
        approverId: "usr_fatima",
        decision: "APPROVED",
        decidedAt: iso(-9),
        createdAt: iso(-10),
      },
      {
        id: "ap_008_3",
        requestId: "req_008",
        stage: "PROCUREMENT",
        approverId: "usr_tunde",
        decision: "APPROVED",
        decidedAt: iso(-8),
        createdAt: iso(-9),
      },
    ],
    createdAt: iso(-12),
    updatedAt: iso(-8),
    submittedAt: iso(-12),
  },
];

export const seedRFQs: RFQ[] = [
  {
    id: "rfq_001",
    organizationId: "org_apex",
    rfqNumber: "RFQ-2026-0001",
    requestId: "req_002",
    title: "PPE Supply — Q3 Restock",
    description:
      "Quote required for the following PPE items per attached spec. Delivery to Port Harcourt Plant. Payment terms Net 30. Warranty against manufacturing defects.",
    deadline: iso(5),
    status: "RECEIVED",
    invitedVendorIds: ["vnd_safetync", "vnd_officedirect", "vnd_globalequip"],
    createdAt: iso(-1),
    quotations: [
      {
        id: "q_001_1",
        rfqId: "rfq_001",
        vendorId: "vnd_safetync",
        totalAmount: 11480,
        currency: "USD",
        deliveryDays: 5,
        warranty: "12 months against manufacturing defects",
        paymentTerms: "Net 30",
        validUntil: iso(20),
        notes: "Free delivery to Port Harcourt Plant. Can supply full quantity from stock.",
        status: "RECEIVED",
        createdAt: iso(-0.5),
      },
      {
        id: "q_001_2",
        rfqId: "rfq_001",
        vendorId: "vnd_officedirect",
        totalAmount: 12250,
        currency: "USD",
        deliveryDays: 7,
        warranty: "6 months against manufacturing defects",
        paymentTerms: "50% advance, 50% on delivery",
        validUntil: iso(15),
        notes: "Delivery via third-party logistics. Boots and helmets in stock, gloves require 5-day lead time.",
        status: "RECEIVED",
        createdAt: iso(-0.3),
      },
      {
        id: "q_001_3",
        rfqId: "rfq_001",
        vendorId: "vnd_globalequip",
        totalAmount: 13900,
        currency: "USD",
        deliveryDays: 14,
        warranty: "24 months against manufacturing defects (premium grade)",
        paymentTerms: "Letter of Credit at sight",
        validUntil: iso(30),
        notes: "Imported premium-grade items. Longer delivery but superior quality and warranty. Suitable for high-risk environments.",
        status: "RECEIVED",
        createdAt: iso(-0.1),
      },
    ],
    selectedQuotationId: undefined,
  },
  {
    id: "rfq_002",
    organizationId: "org_apex",
    rfqNumber: "RFQ-2026-0002",
    requestId: "req_006",
    title: "250kVA Backup Generator Supply & Installation",
    description:
      "Supply, install, and commission a 250kVA Perkins-equivalent diesel generator with ATS, sound-attenuated canopy, and 1000L fuel tank at Plant 2 (Port Harcourt).",
    deadline: iso(7),
    status: "WAITING",
    invitedVendorIds: ["vnd_powergen", "vnd_globalequip"],
    createdAt: iso(-0.5),
    quotations: [
      {
        id: "q_002_1",
        rfqId: "rfq_002",
        vendorId: "vnd_powergen",
        totalAmount: 41500,
        currency: "USD",
        deliveryDays: 21,
        warranty: "24 months comprehensive on generator, 12 months on ATS",
        paymentTerms: "30% advance, 60% on delivery, 10% after commissioning",
        validUntil: iso(45),
        notes: "Stock unit available. Includes free site survey. Local Perkins-certified service team.",
        status: "RECEIVED",
        createdAt: iso(-0.2),
      },
    ],
    selectedQuotationId: undefined,
  },
  {
    id: "rfq_003",
    organizationId: "org_apex",
    rfqNumber: "RFQ-2026-0003",
    requestId: "req_008",
    title: "Annual HVAC Maintenance Contract — 3 Branches",
    description:
      "Comprehensive annual HVAC maintenance contract covering Lagos HQ, Abuja Office, and Port Harcourt Plant. Includes quarterly preventive maintenance, 24/7 emergency response, and parts discount.",
    deadline: iso(-2),
    status: "CLOSED",
    invitedVendorIds: ["vnd_arcticair"],
    createdAt: iso(-12),
    quotations: [
      {
        id: "q_003_1",
        rfqId: "rfq_003",
        vendorId: "vnd_arcticair",
        totalAmount: 17500,
        currency: "USD",
        deliveryDays: 0,
        warranty: "Service-level agreement, 4-hour emergency response",
        paymentTerms: "Quarterly billing in advance",
        validUntil: iso(30),
        notes: "Includes all 3 branches. 15% discount on replacement parts. Dedicated account manager.",
        status: "RECEIVED",
        createdAt: iso(-10),
      },
    ],
    selectedQuotationId: "q_003_1",
  },
];

export const seedPurchaseOrders: PurchaseOrder[] = [
  {
    id: "po_001",
    organizationId: "org_apex",
    poNumber: "PO-2026-0001",
    requestId: "req_004",
    rfqId: "rfq_legacy",
    quotationId: "q_legacy",
    vendorId: "vnd_steelworks",
    status: "RECEIVED",
    totalAmount: 38500,
    currency: "USD",
    taxRate: 7.5,
    issuedAt: iso(-23),
    expectedDelivery: iso(-8),
    notes: "Delivery to Plant 2 site. SteelWorks to coordinate with site engineer on delivery schedule.",
    lineItems: [
      {
        id: "li_po_001_1",
        itemName: "Steel Rebar Grade 60 — 16mm",
        description: "ASTM A615 Grade 60, 16mm diameter, 12m lengths",
        quantity: 30,
        unit: "tonnes",
        estimatedCost: 850,
      },
      {
        id: "li_po_001_2",
        itemName: "Steel Rebar Grade 60 — 20mm",
        description: "ASTM A615 Grade 60, 20mm diameter, 12m lengths",
        quantity: 20,
        unit: "tonnes",
        estimatedCost: 920,
      },
    ],
  },
  {
    id: "po_002",
    organizationId: "org_apex",
    poNumber: "PO-2026-0002",
    vendorId: "vnd_officedirect",
    status: "CLOSED",
    totalAmount: 8200,
    currency: "USD",
    taxRate: 7.5,
    issuedAt: iso(-30),
    expectedDelivery: iso(-22),
    notes: "Q1 office supplies restock.",
    lineItems: [
      {
        id: "li_po_002_1",
        itemName: "A4 Paper (80gsm, 500 sheets/ream)",
        description: "Multi-purpose white printer paper",
        quantity: 200,
        unit: "reams",
        estimatedCost: 6.5,
      },
      {
        id: "li_po_002_2",
        itemName: "Printer Toner Cartridges (HP)",
        description: "HP 414A original toner, mixed colors",
        quantity: 20,
        unit: "pcs",
        estimatedCost: 95,
      },
      {
        id: "li_po_002_3",
        itemName: "Desk Organizers & Stationery Kit",
        description: "Complete kit including pens, files, staplers, clips",
        quantity: 50,
        unit: "kits",
        estimatedCost: 36,
      },
    ],
  },
  {
    id: "po_003",
    organizationId: "org_apex",
    poNumber: "PO-2026-0003",
    vendorId: "vnd_powergen",
    status: "IN_DELIVERY",
    totalAmount: 16800,
    currency: "USD",
    taxRate: 7.5,
    issuedAt: iso(-12),
    expectedDelivery: iso(3),
    notes: "UPS units for Lagos HQ server room upgrade.",
    lineItems: [
      {
        id: "li_po_003_1",
        itemName: "UPS 5kVA Online Double-Conversion",
        description: "Rack-mount UPS, 5kVA, with network management card",
        quantity: 4,
        unit: "units",
        estimatedCost: 4200,
      },
    ],
  },
  {
    id: "po_004",
    organizationId: "org_apex",
    poNumber: "PO-2026-0004",
    vendorId: "vnd_techcore",
    status: "ISSUED",
    totalAmount: 15600,
    currency: "USD",
    taxRate: 7.5,
    issuedAt: iso(-2),
    expectedDelivery: iso(10),
    notes: "Network switches and access points for Lagos HQ refresh.",
    lineItems: [
      {
        id: "li_po_004_1",
        itemName: "Cisco Catalyst 9300 Switch",
        description: "48-port PoE+ enterprise switch, stackable",
        quantity: 2,
        unit: "units",
        estimatedCost: 4500,
      },
      {
        id: "li_po_004_2",
        itemName: "Ubiquiti U6-Pro Access Points",
        description: "Wi-Fi 6 access points, ceiling mount, PoE+",
        quantity: 15,
        unit: "pcs",
        estimatedCost: 280,
      },
    ],
  },
  {
    id: "po_005",
    organizationId: "org_apex",
    poNumber: "PO-2026-0005",
    vendorId: "vnd_primecement",
    status: "ACKNOWLEDGED",
    totalAmount: 24500,
    currency: "USD",
    taxRate: 7.5,
    issuedAt: iso(-4),
    expectedDelivery: iso(7),
    notes: "Cement supply for Plant 2 Phase 2 construction.",
    lineItems: [
      {
        id: "li_po_005_1",
        itemName: "Portland Cement Grade 42.5N",
        description: "Bulk cement, 50kg bags, ASTM C150 Type I",
        quantity: 500,
        unit: "bags",
        estimatedCost: 49,
      },
    ],
  },
];

export const seedActivities: ActivityLog[] = [
  {
    id: "act_001",
    organizationId: "org_apex",
    userId: "usr_tunde",
    purchaseOrderId: "po_004",
    eventType: "PO_GENERATED",
    description: "Tunde Bello generated Purchase Order PO-2026-0004 to TechCore Distributors Ltd. ($15,600)",
    createdAt: iso(-2),
  },
  {
    id: "act_002",
    organizationId: "org_apex",
    userId: "usr_fatima",
    requestId: "req_006",
    eventType: "REQUEST_APPROVED",
    description: "Fatima Sani approved PR-2026-0006 (Backup Generator) at the Department Manager stage",
    createdAt: iso(-2),
  },
  {
    id: "act_003",
    organizationId: "org_apex",
    userId: "usr_tunde",
    eventType: "QUOTATION_RECEIVED",
    description: "Quotation received from Arctic Air HVAC Systems for RFQ-2026-0003",
    createdAt: iso(-0.1),
  },
  {
    id: "act_004",
    organizationId: "org_apex",
    userId: "usr_emeka",
    requestId: "req_006",
    eventType: "REQUEST_SUBMITTED",
    description: "Emeka Eze submitted PR-2026-0006: 'Backup Generator — 250kVA for Plant 2'",
    createdAt: iso(-3),
  },
  {
    id: "act_005",
    organizationId: "org_apex",
    userId: "usr_tunde",
    eventType: "RFQ_CREATED",
    description: "RFQ-2026-0001 issued to 3 vendors: SafetyNig Industrial, OfficeDirect Nigeria, Global Equipment Trading",
    createdAt: iso(-1),
  },
  {
    id: "act_006",
    organizationId: "org_apex",
    userId: "usr_fatima",
    requestId: "req_002",
    eventType: "REQUEST_APPROVED",
    description: "Fatima Sani approved PR-2026-0002 (PPE Restock) — $12,650",
    createdAt: iso(-1),
  },
  {
    id: "act_007",
    organizationId: "org_apex",
    userId: "usr_chidi",
    requestId: "req_001",
    eventType: "REQUEST_APPROVED",
    description: "Chidi Nwosu approved PR-2026-0001 (Industrial Laptops) at Department Manager stage",
    createdAt: iso(-3),
  },
  {
    id: "act_008",
    organizationId: "org_apex",
    userId: "usr_yusuf",
    requestId: "req_007",
    eventType: "REQUEST_CREATED",
    description: "Yusuf Aliyu created draft PR-2026-0007: 'Office Furniture — Abuja Office Setup'",
    createdAt: iso(-1),
  },
  {
    id: "act_009",
    organizationId: "org_apex",
    purchaseOrderId: "po_001",
    eventType: "STATUS_CHANGE",
    description: "Purchase Order PO-2026-0001 marked as RECEIVED — Steel rebar delivered to Plant 2",
    createdAt: iso(-8),
  },
  {
    id: "act_010",
    organizationId: "org_apex",
    userId: "usr_fatima",
    requestId: "req_005",
    eventType: "REQUEST_REJECTED",
    description: "Fatima Sani rejected PR-2026-0005 (Marketing Laptops) — 'FY IT budget exhausted'",
    createdAt: iso(-6),
  },
];

export const seedNotifications: Notification[] = [
  {
    id: "ntf_001",
    organizationId: "org_apex",
    userId: "usr_amina",
    title: "Approval needed: Backup Generator",
    message: "PR-2026-0006 (Backup Generator — 250kVA) is awaiting your Finance approval. $42,000 commitment.",
    type: "approval",
    read: false,
    link: "requests",
    createdAt: iso(-2),
  },
  {
    id: "ntf_002",
    organizationId: "org_apex",
    userId: "usr_amina",
    title: "New quotation received",
    message: "Arctic Air HVAC Systems submitted a quotation for RFQ-2026-0003.",
    type: "info",
    read: false,
    link: "rfqs",
    createdAt: iso(-0.1),
  },
  {
    id: "ntf_003",
    organizationId: "org_apex",
    userId: "usr_amina",
    title: "PO issued to TechCore",
    message: "PO-2026-0004 for $15,600 was issued to TechCore Distributors Ltd.",
    type: "success",
    read: false,
    link: "purchase-orders",
    createdAt: iso(-2),
  },
  {
    id: "ntf_004",
    organizationId: "org_apex",
    userId: "usr_amina",
    title: "PR-2026-0001 needs Finance review",
    message: "Industrial Laptops request ($8,400) cleared Department Manager approval.",
    type: "approval",
    read: true,
    link: "requests",
    createdAt: iso(-3),
  },
  {
    id: "ntf_005",
    organizationId: "org_apex",
    userId: "usr_amina",
    title: "Steel delivery completed",
    message: "PO-2026-0001 (Steel rebar) was marked as received at Plant 2.",
    type: "success",
    read: true,
    link: "purchase-orders",
    createdAt: iso(-8),
  },
];
