// GENERATED by scripts/codegen/decimal-map.mjs — do not edit by hand.
//
// Money and quantity columns are Postgres `numeric`, so aggregation is exact and
// no rounding drift accumulates in the ledger. Prisma returns those as Decimal
// objects. This extension converts them to `number` on every read — including
// nested `include`s and reads inside transactions — so services and views work
// with plain numbers and the TypeScript types match what is actually there.
//
// Writes are unaffected: Prisma accepts a number for a Decimal column and the
// database rounds it to the column scale.
//
// Aggregates (`_sum`, `_avg`) are deliberately NOT covered — they still return
// Decimal, and the compiler will point at every call site that must convert.

import type { Prisma } from "@prisma/client";

export const decimalAsNumber = {
  name: "decimal-as-number",
  result: {
  vendor: {
    totalValue: {
      needs: { totalValue: true },
      compute: (r: { totalValue: Prisma.Decimal }) => Number(r.totalValue),
    },
  },
  vendorPerformanceSnapshot: {
    totalSpend: {
      needs: { totalSpend: true },
      compute: (r: { totalSpend: Prisma.Decimal }) => Number(r.totalSpend),
    },
  },
  purchaseRequest: {
    totalEstimated: {
      needs: { totalEstimated: true },
      compute: (r: { totalEstimated: Prisma.Decimal }) => Number(r.totalEstimated),
    },
  },
  requestLineItem: {
    quantity: {
      needs: { quantity: true },
      compute: (r: { quantity: Prisma.Decimal }) => Number(r.quantity),
    },
    estimatedCost: {
      needs: { estimatedCost: true },
      compute: (r: { estimatedCost: Prisma.Decimal }) => Number(r.estimatedCost),
    },
    taxRate: {
      needs: { taxRate: true },
      compute: (r: { taxRate: Prisma.Decimal }) => Number(r.taxRate),
    },
  },
  approvalWorkflow: {
    thresholdMin: {
      needs: { thresholdMin: true },
      compute: (r: { thresholdMin: Prisma.Decimal | null }) => r.thresholdMin === null || r.thresholdMin === undefined ? null : Number(r.thresholdMin),
    },
    thresholdMax: {
      needs: { thresholdMax: true },
      compute: (r: { thresholdMax: Prisma.Decimal | null }) => r.thresholdMax === null || r.thresholdMax === undefined ? null : Number(r.thresholdMax),
    },
  },
  approvalWorkflowStage: {
    conditionMinAmount: {
      needs: { conditionMinAmount: true },
      compute: (r: { conditionMinAmount: Prisma.Decimal | null }) => r.conditionMinAmount === null || r.conditionMinAmount === undefined ? null : Number(r.conditionMinAmount),
    },
    conditionMaxAmount: {
      needs: { conditionMaxAmount: true },
      compute: (r: { conditionMaxAmount: Prisma.Decimal | null }) => r.conditionMaxAmount === null || r.conditionMaxAmount === undefined ? null : Number(r.conditionMaxAmount),
    },
  },
  approvalInstance: {
    amount: {
      needs: { amount: true },
      compute: (r: { amount: Prisma.Decimal | null }) => r.amount === null || r.amount === undefined ? null : Number(r.amount),
    },
  },
  rFQLineItem: {
    quantity: {
      needs: { quantity: true },
      compute: (r: { quantity: Prisma.Decimal }) => Number(r.quantity),
    },
  },
  quotation: {
    totalAmount: {
      needs: { totalAmount: true },
      compute: (r: { totalAmount: Prisma.Decimal }) => Number(r.totalAmount),
    },
  },
  quotationLineItem: {
    quantity: {
      needs: { quantity: true },
      compute: (r: { quantity: Prisma.Decimal }) => Number(r.quantity),
    },
    unitPrice: {
      needs: { unitPrice: true },
      compute: (r: { unitPrice: Prisma.Decimal }) => Number(r.unitPrice),
    },
    taxRate: {
      needs: { taxRate: true },
      compute: (r: { taxRate: Prisma.Decimal }) => Number(r.taxRate),
    },
  },
  rFQAward: {
    awardedAmount: {
      needs: { awardedAmount: true },
      compute: (r: { awardedAmount: Prisma.Decimal }) => Number(r.awardedAmount),
    },
  },
  purchaseOrder: {
    subtotal: {
      needs: { subtotal: true },
      compute: (r: { subtotal: Prisma.Decimal }) => Number(r.subtotal),
    },
    taxRate: {
      needs: { taxRate: true },
      compute: (r: { taxRate: Prisma.Decimal }) => Number(r.taxRate),
    },
    taxAmount: {
      needs: { taxAmount: true },
      compute: (r: { taxAmount: Prisma.Decimal }) => Number(r.taxAmount),
    },
    discountAmount: {
      needs: { discountAmount: true },
      compute: (r: { discountAmount: Prisma.Decimal }) => Number(r.discountAmount),
    },
    totalAmount: {
      needs: { totalAmount: true },
      compute: (r: { totalAmount: Prisma.Decimal }) => Number(r.totalAmount),
    },
  },
  pOLineItem: {
    unitPrice: {
      needs: { unitPrice: true },
      compute: (r: { unitPrice: Prisma.Decimal }) => Number(r.unitPrice),
    },
    taxRate: {
      needs: { taxRate: true },
      compute: (r: { taxRate: Prisma.Decimal }) => Number(r.taxRate),
    },
    orderedQty: {
      needs: { orderedQty: true },
      compute: (r: { orderedQty: Prisma.Decimal }) => Number(r.orderedQty),
    },
    receivedQty: {
      needs: { receivedQty: true },
      compute: (r: { receivedQty: Prisma.Decimal }) => Number(r.receivedQty),
    },
    rejectedQty: {
      needs: { rejectedQty: true },
      compute: (r: { rejectedQty: Prisma.Decimal }) => Number(r.rejectedQty),
    },
    invoicedQty: {
      needs: { invoicedQty: true },
      compute: (r: { invoicedQty: Prisma.Decimal }) => Number(r.invoicedQty),
    },
  },
  goodsReceiptItem: {
    orderedQty: {
      needs: { orderedQty: true },
      compute: (r: { orderedQty: Prisma.Decimal }) => Number(r.orderedQty),
    },
    receivedQty: {
      needs: { receivedQty: true },
      compute: (r: { receivedQty: Prisma.Decimal }) => Number(r.receivedQty),
    },
    deliveredQty: {
      needs: { deliveredQty: true },
      compute: (r: { deliveredQty: Prisma.Decimal }) => Number(r.deliveredQty),
    },
    rejectedQty: {
      needs: { rejectedQty: true },
      compute: (r: { rejectedQty: Prisma.Decimal }) => Number(r.rejectedQty),
    },
    damagedQty: {
      needs: { damagedQty: true },
      compute: (r: { damagedQty: Prisma.Decimal }) => Number(r.damagedQty),
    },
  },
  invoice: {
    subtotal: {
      needs: { subtotal: true },
      compute: (r: { subtotal: Prisma.Decimal }) => Number(r.subtotal),
    },
    taxAmount: {
      needs: { taxAmount: true },
      compute: (r: { taxAmount: Prisma.Decimal }) => Number(r.taxAmount),
    },
    totalAmount: {
      needs: { totalAmount: true },
      compute: (r: { totalAmount: Prisma.Decimal }) => Number(r.totalAmount),
    },
    paidAmount: {
      needs: { paidAmount: true },
      compute: (r: { paidAmount: Prisma.Decimal }) => Number(r.paidAmount),
    },
    balance: {
      needs: { balance: true },
      compute: (r: { balance: Prisma.Decimal }) => Number(r.balance),
    },
    matchVariance: {
      needs: { matchVariance: true },
      compute: (r: { matchVariance: Prisma.Decimal | null }) => r.matchVariance === null || r.matchVariance === undefined ? null : Number(r.matchVariance),
    },
  },
  invoiceLineItem: {
    quantity: {
      needs: { quantity: true },
      compute: (r: { quantity: Prisma.Decimal }) => Number(r.quantity),
    },
    unitPrice: {
      needs: { unitPrice: true },
      compute: (r: { unitPrice: Prisma.Decimal }) => Number(r.unitPrice),
    },
    taxRate: {
      needs: { taxRate: true },
      compute: (r: { taxRate: Prisma.Decimal }) => Number(r.taxRate),
    },
  },
  invoiceMatchException: {
    orderedQty: {
      needs: { orderedQty: true },
      compute: (r: { orderedQty: Prisma.Decimal | null }) => r.orderedQty === null || r.orderedQty === undefined ? null : Number(r.orderedQty),
    },
    receivedQty: {
      needs: { receivedQty: true },
      compute: (r: { receivedQty: Prisma.Decimal | null }) => r.receivedQty === null || r.receivedQty === undefined ? null : Number(r.receivedQty),
    },
    invoicedQty: {
      needs: { invoicedQty: true },
      compute: (r: { invoicedQty: Prisma.Decimal | null }) => r.invoicedQty === null || r.invoicedQty === undefined ? null : Number(r.invoicedQty),
    },
    orderedPrice: {
      needs: { orderedPrice: true },
      compute: (r: { orderedPrice: Prisma.Decimal | null }) => r.orderedPrice === null || r.orderedPrice === undefined ? null : Number(r.orderedPrice),
    },
    invoicedPrice: {
      needs: { invoicedPrice: true },
      compute: (r: { invoicedPrice: Prisma.Decimal | null }) => r.invoicedPrice === null || r.invoicedPrice === undefined ? null : Number(r.invoicedPrice),
    },
    variance: {
      needs: { variance: true },
      compute: (r: { variance: Prisma.Decimal | null }) => r.variance === null || r.variance === undefined ? null : Number(r.variance),
    },
  },
  payment: {
    amount: {
      needs: { amount: true },
      compute: (r: { amount: Prisma.Decimal }) => Number(r.amount),
    },
    reconciledAmount: {
      needs: { reconciledAmount: true },
      compute: (r: { reconciledAmount: Prisma.Decimal | null }) => r.reconciledAmount === null || r.reconciledAmount === undefined ? null : Number(r.reconciledAmount),
    },
  },
  paymentAllocation: {
    amount: {
      needs: { amount: true },
      compute: (r: { amount: Prisma.Decimal }) => Number(r.amount),
    },
  },
  paymentTransaction: {
    amount: {
      needs: { amount: true },
      compute: (r: { amount: Prisma.Decimal }) => Number(r.amount),
    },
  },
  budget: {
    totalAmount: {
      needs: { totalAmount: true },
      compute: (r: { totalAmount: Prisma.Decimal }) => Number(r.totalAmount),
    },
    reservedAmount: {
      needs: { reservedAmount: true },
      compute: (r: { reservedAmount: Prisma.Decimal }) => Number(r.reservedAmount),
    },
    committedAmount: {
      needs: { committedAmount: true },
      compute: (r: { committedAmount: Prisma.Decimal }) => Number(r.committedAmount),
    },
    requestedAmount: {
      needs: { requestedAmount: true },
      compute: (r: { requestedAmount: Prisma.Decimal }) => Number(r.requestedAmount),
    },
    spentAmount: {
      needs: { spentAmount: true },
      compute: (r: { spentAmount: Prisma.Decimal }) => Number(r.spentAmount),
    },
    invoicedAmount: {
      needs: { invoicedAmount: true },
      compute: (r: { invoicedAmount: Prisma.Decimal }) => Number(r.invoicedAmount),
    },
    paidAmount: {
      needs: { paidAmount: true },
      compute: (r: { paidAmount: Prisma.Decimal }) => Number(r.paidAmount),
    },
    remainingAmount: {
      needs: { remainingAmount: true },
      compute: (r: { remainingAmount: Prisma.Decimal }) => Number(r.remainingAmount),
    },
  },
  budgetCategory: {
    allocated: {
      needs: { allocated: true },
      compute: (r: { allocated: Prisma.Decimal }) => Number(r.allocated),
    },
    spent: {
      needs: { spent: true },
      compute: (r: { spent: Prisma.Decimal }) => Number(r.spent),
    },
    committed: {
      needs: { committed: true },
      compute: (r: { committed: Prisma.Decimal }) => Number(r.committed),
    },
  },
  budgetEntry: {
    amount: {
      needs: { amount: true },
      compute: (r: { amount: Prisma.Decimal }) => Number(r.amount),
    },
  },
  contract: {
    value: {
      needs: { value: true },
      compute: (r: { value: Prisma.Decimal }) => Number(r.value),
    },
  },
  asset: {
    purchaseValue: {
      needs: { purchaseValue: true },
      compute: (r: { purchaseValue: Prisma.Decimal }) => Number(r.purchaseValue),
    },
    currentValue: {
      needs: { currentValue: true },
      compute: (r: { currentValue: Prisma.Decimal }) => Number(r.currentValue),
    },
    depreciationRate: {
      needs: { depreciationRate: true },
      compute: (r: { depreciationRate: Prisma.Decimal }) => Number(r.depreciationRate),
    },
    salvageValue: {
      needs: { salvageValue: true },
      compute: (r: { salvageValue: Prisma.Decimal }) => Number(r.salvageValue),
    },
  },
  assetMaintenance: {
    cost: {
      needs: { cost: true },
      compute: (r: { cost: Prisma.Decimal }) => Number(r.cost),
    },
  },
  inventoryItem: {
    quantity: {
      needs: { quantity: true },
      compute: (r: { quantity: Prisma.Decimal }) => Number(r.quantity),
    },
    reorderLevel: {
      needs: { reorderLevel: true },
      compute: (r: { reorderLevel: Prisma.Decimal }) => Number(r.reorderLevel),
    },
    reorderQty: {
      needs: { reorderQty: true },
      compute: (r: { reorderQty: Prisma.Decimal }) => Number(r.reorderQty),
    },
    unitCost: {
      needs: { unitCost: true },
      compute: (r: { unitCost: Prisma.Decimal }) => Number(r.unitCost),
    },
  },
  stockMovement: {
    quantity: {
      needs: { quantity: true },
      compute: (r: { quantity: Prisma.Decimal }) => Number(r.quantity),
    },
    balanceAfter: {
      needs: { balanceAfter: true },
      compute: (r: { balanceAfter: Prisma.Decimal }) => Number(r.balanceAfter),
    },
    unitCost: {
      needs: { unitCost: true },
      compute: (r: { unitCost: Prisma.Decimal | null }) => r.unitCost === null || r.unitCost === undefined ? null : Number(r.unitCost),
    },
  },
  stockBalance: {
    quantity: {
      needs: { quantity: true },
      compute: (r: { quantity: Prisma.Decimal }) => Number(r.quantity),
    },
    reservedQty: {
      needs: { reservedQty: true },
      compute: (r: { reservedQty: Prisma.Decimal }) => Number(r.reservedQty),
    },
  },
  },
} as const;
