// NextMav Procure — demo supplier master.
//
// These fixtures live here, next to the seeder that consumes them, rather than in
// src/lib/seed-data.ts. That file is imported by the browser store, so vendor
// fixtures kept there were shipped to every client — and a fictional supplier
// master rendered by the same components as the real one is indistinguishable
// from it. §31: the application shows real data or an empty state.
//
// Nothing in src/ imports this module.

import type { ComplianceDocStatus, VendorDocumentType, VendorStatus } from "@prisma/client";

interface SeedVendorDocument {
  id: string;
  vendorId: string;
  type: VendorDocumentType;
  name: string;
  fileName: string;
  fileSize: string;
  uploadedAt: string;
  expiresAt?: string;
  status: ComplianceDocStatus;
}

interface SeedVendor {
  id: string;
  organizationId: string;
  companyName: string;
  contactPerson?: string;
  email?: string;
  phone?: string;
  address?: string;
  category?: string;
  taxNumber?: string;
  bankName?: string;
  bankAccount?: string;
  paymentTerms?: string;
  preferredCurrency?: string;
  status: VendorStatus;
  isPreferred?: boolean;
  rating?: number;
  notes?: string;
  tags?: string[];
  totalOrders?: number;
  totalValue?: number;
  complianceScore?: number;
  onTimeDeliveryRate?: number;
  qualityRating?: number;
  documents?: SeedVendorDocument[];
  createdAt?: string;
}

const now = new Date();
const iso = (offsetDays: number) =>
  new Date(now.getTime() + offsetDays * 24 * 60 * 60 * 1000).toISOString();

const seedVendorDocuments: SeedVendorDocument[] = [
  { id: "vd_1", vendorId: "vnd_techcore", type: "CERTIFICATE", name: "ISO 9001 Certificate", fileName: "iso-9001-2024.pdf", fileSize: "245 KB", uploadedAt: "2024-03-15T10:00:00Z", expiresAt: iso(180), status: "VALID" },
  { id: "vd_2", vendorId: "vnd_techcore", type: "TAX", name: "Tax Clearance Certificate", fileName: "tax-clearance-2024.pdf", fileSize: "180 KB", uploadedAt: "2024-03-15T10:00:00Z", expiresAt: iso(60), status: "EXPIRING" },
  { id: "vd_3", vendorId: "vnd_techcore", type: "BANK_PROOF", name: "Bank Account Proof", fileName: "bank-proof.pdf", fileSize: "92 KB", uploadedAt: "2024-03-15T10:00:00Z", status: "VALID" },
  { id: "vd_4", vendorId: "vnd_safetync", type: "CERTIFICATE", name: "HSE Compliance Certificate", fileName: "hse-cert.pdf", fileSize: "312 KB", uploadedAt: "2024-01-25T10:00:00Z", expiresAt: iso(120), status: "VALID" },
  { id: "vd_5", vendorId: "vnd_safetync", type: "INSURANCE", name: "Public Liability Insurance", fileName: "liability-insurance.pdf", fileSize: "425 KB", uploadedAt: "2024-01-25T10:00:00Z", expiresAt: iso(-15), status: "EXPIRED" },
  { id: "vd_6", vendorId: "vnd_steelworks", type: "CERTIFICATE", name: "ASTM A615 Compliance", fileName: "astm-cert.pdf", fileSize: "198 KB", uploadedAt: "2023-09-18T10:00:00Z", status: "VALID" },
  { id: "vd_7", vendorId: "vnd_steelworks", type: "INSURANCE", name: "Workers Compensation Insurance", fileName: "wc-insurance.pdf", fileSize: "356 KB", uploadedAt: "2023-09-18T10:00:00Z", expiresAt: iso(90), status: "VALID" },
  { id: "vd_8", vendorId: "vnd_powergen", type: "CERTIFICATE", name: "Perkins Authorized Dealer", fileName: "perkins-auth.pdf", fileSize: "142 KB", uploadedAt: "2024-02-14T10:00:00Z", expiresAt: iso(200), status: "VALID" },
];

export const seedVendors: SeedVendor[] = [
  {
    id: "vnd_techcore",
    organizationId: "org_apex",
    companyName: "TechCore Distributors Ltd.",
    contactPerson: "Ibrahim Mohammed",
    email: "sales@techcore-ng.com",
    phone: "+234 805 234 1100",
    address: "14 Computer Village, Ikeja, Lagos",
    category: "IT Equipment",
    taxNumber: "TIN-TC-193820",
    bankName: "First Bank Nigeria",
    bankAccount: "3031xxxxxx92",
    rating: 4.7,
    status: "ACTIVE",
    totalOrders: 24,
    totalValue: 184500,
    paymentTerms: "Net 30",
    preferredCurrency: "NGN",
    complianceScore: 92,
    onTimeDeliveryRate: 94,
    qualityRating: 4.6,
    documents: seedVendorDocuments.filter((d) => d.vendorId === "vnd_techcore"),
    tags: ["preferred", "it", "lagos"],
    notes: "Reliable IT equipment distributor with strong delivery performance.",
    createdAt: "2024-03-12T09:00:00Z",
  },
  {
    id: "vnd_safetync",
    organizationId: "org_apex",
    companyName: "SafetyNig Industrial Supplies",
    contactPerson: "Blessing Okon",
    email: "info@safetync.com",
    phone: "+234 805 999 2233",
    address: "78 Industrial Layout, Trans-Amadi, Port Harcourt",
    category: "Safety Equipment",
    taxNumber: "TIN-SN-445120",
    bankName: "Access Bank",
    bankAccount: "0091xxxxxx34",
    rating: 4.5,
    status: "ACTIVE",
    isPreferred: true,
    totalOrders: 18,
    totalValue: 96200,
    paymentTerms: "Net 30",
    preferredCurrency: "NGN",
    complianceScore: 88,
    onTimeDeliveryRate: 91,
    qualityRating: 4.5,
    documents: seedVendorDocuments.filter((d) => d.vendorId === "vnd_safetync"),
    tags: ["preferred", "safety", "ppe"],
    notes: "Specializes in safety equipment. Insurance expired — needs renewal.",
    createdAt: "2024-01-25T09:00:00Z",
  },
  {
    id: "vnd_steelworks",
    organizationId: "org_apex",
    companyName: "SteelWorks Africa Ltd.",
    contactPerson: "Olumide Adesanya",
    email: "quotes@steelworks.africa",
    phone: "+234 807 112 8890",
    address: "Plot 45, Apapa Industrial Zone, Lagos",
    category: "Construction Materials",
    taxNumber: "TIN-SW-778301",
    bankName: "Zenith Bank",
    bankAccount: "1015xxxxxx88",
    rating: 4.3,
    status: "ACTIVE",
    totalOrders: 31,
    totalValue: 412000,
    paymentTerms: "30% advance, 70% on delivery",
    preferredCurrency: "NGN",
    complianceScore: 95,
    onTimeDeliveryRate: 88,
    qualityRating: 4.4,
    documents: seedVendorDocuments.filter((d) => d.vendorId === "vnd_steelworks"),
    tags: ["construction", "steel", "lagos"],
    notes: "Largest steel supplier. Excellent quality but delivery times can vary.",
    createdAt: "2023-09-18T09:00:00Z",
  },
  {
    id: "vnd_officedirect",
    organizationId: "org_apex",
    companyName: "OfficeDirect Nigeria",
    contactPerson: "Chioma Eze",
    email: "orders@officedirect.ng",
    phone: "+234 809 445 6677",
    address: "21 Allen Avenue, Ikeja, Lagos",
    category: "Office Supplies",
    taxNumber: "TIN-OD-220914",
    bankName: "GTBank",
    bankAccount: "0123xxxxxx76",
    rating: 4.6,
    status: "ACTIVE",
    totalOrders: 42,
    totalValue: 67800,
    paymentTerms: "Net 15",
    preferredCurrency: "NGN",
    complianceScore: 90,
    onTimeDeliveryRate: 96,
    qualityRating: 4.5,
    documents: [],
    tags: ["office", "supplies"],
    notes: "Reliable office supplies vendor. Fast turnaround.",
    createdAt: "2023-05-08T09:00:00Z",
  },
  {
    id: "vnd_powergen",
    organizationId: "org_apex",
    companyName: "PowerGen Solutions",
    contactPerson: "Samuel Adeyinka",
    email: "sales@powergen.com",
    phone: "+234 802 778 1100",
    address: "5 Marina Road, Lagos Island",
    category: "Electrical & Power",
    taxNumber: "TIN-PG-556720",
    bankName: "UBA",
    bankAccount: "2155xxxxxx09",
    rating: 4.4,
    status: "ACTIVE",
    totalOrders: 16,
    totalValue: 138900,
    paymentTerms: "30% advance, 60% on delivery, 10% after commissioning",
    preferredCurrency: "NGN",
    complianceScore: 91,
    onTimeDeliveryRate: 89,
    qualityRating: 4.4,
    documents: seedVendorDocuments.filter((d) => d.vendorId === "vnd_powergen"),
    tags: ["electrical", "generators", "power"],
    notes: "Authorized Perkins dealer. Strong technical team.",
    createdAt: "2024-02-14T09:00:00Z",
  },
  {
    id: "vnd_logifleet",
    organizationId: "org_apex",
    companyName: "LogiFleet Logistics",
    contactPerson: "Hauwa Bello",
    email: "contact@logifleet.ng",
    phone: "+234 806 223 4478",
    address: "Apapa Port Complex, Lagos",
    category: "Logistics",
    taxNumber: "TIN-LF-991023",
    bankName: "Stanbic IBTC",
    bankAccount: "0009xxxxxx55",
    rating: 4.1,
    status: "ACTIVE",
    totalOrders: 9,
    totalValue: 52300,
    paymentTerms: "Net 15",
    preferredCurrency: "NGN",
    complianceScore: 78,
    onTimeDeliveryRate: 82,
    qualityRating: 4.0,
    documents: [],
    tags: ["logistics", "freight"],
    notes: "Logistics partner for port-to-site deliveries.",
    createdAt: "2024-06-30T09:00:00Z",
  },
  {
    id: "vnd_globalequip",
    organizationId: "org_apex",
    companyName: "Global Equipment Trading",
    contactPerson: "Daniel Park",
    email: "daniel@globalequip.com",
    phone: "+27 11 555 4400",
    address: "Sandton City, Johannesburg, South Africa",
    category: "Industrial Equipment",
    taxNumber: "TIN-GE-SA-22001",
    bankName: "Standard Bank",
    bankAccount: "62xxxxxx01",
    rating: 4.8,
    status: "PROSPECTIVE",
    totalOrders: 2,
    totalValue: 84000,
    paymentTerms: "Letter of Credit at sight",
    preferredCurrency: "NGN",
    complianceScore: 86,
    onTimeDeliveryRate: 100,
    qualityRating: 4.9,
    documents: [],
    tags: ["premium", "international", "south-africa"],
    notes: "Premium international supplier. Higher cost but superior quality and 24-month warranty.",
    createdAt: "2025-11-04T09:00:00Z",
  },
  {
    id: "vnd_primecement",
    organizationId: "org_apex",
    companyName: "Prime Cement Distributors",
    contactPerson: "Rasaq Olaniyan",
    email: "sales@primecement.ng",
    phone: "+234 803 447 8821",
    address: "Shagamu Industrial Road, Ogun State",
    category: "Construction Materials",
    taxNumber: "TIN-PC-664200",
    bankName: "First Bank Nigeria",
    bankAccount: "3044xxxxxx11",
    rating: 4.0,
    status: "ACTIVE",
    totalOrders: 14,
    totalValue: 92700,
    paymentTerms: "50% advance, 50% on delivery",
    preferredCurrency: "NGN",
    complianceScore: 85,
    onTimeDeliveryRate: 87,
    qualityRating: 4.0,
    documents: [],
    tags: ["construction", "cement"],
    notes: "Cement distributor for construction projects.",
    createdAt: "2024-08-22T09:00:00Z",
  },
  {
    id: "vnd_arcticair",
    organizationId: "org_apex",
    companyName: "Arctic Air HVAC Systems",
    contactPerson: "Lola Martins",
    email: "lola@arcticair.com",
    phone: "+234 809 223 5566",
    address: "34 Adeyemo Alakija, Victoria Island, Lagos",
    category: "HVAC & Cooling",
    taxNumber: "TIN-AA-337812",
    bankName: "GTBank",
    bankAccount: "0222xxxxxx83",
    rating: 3.9,
    status: "PROSPECTIVE",
    totalOrders: 0,
    totalValue: 0,
    paymentTerms: "Quarterly billing in advance",
    preferredCurrency: "NGN",
    complianceScore: 72,
    onTimeDeliveryRate: 0,
    qualityRating: 0,
    documents: [],
    tags: ["hvac", "maintenance"],
    notes: "HVAC maintenance contractor. Recently onboarded.",
    createdAt: "2026-01-15T09:00:00Z",
  },
  {
    id: "vnd_legacytools",
    organizationId: "org_apex",
    companyName: "Legacy Tools Co.",
    contactPerson: "Victor Obi",
    email: "victor@legacytools.com",
    phone: "+234 802 119 4400",
    address: "Plot 12, Emene Industrial Estate, Enugu",
    category: "Industrial Equipment",
    taxNumber: "TIN-LT-872340",
    bankName: "Access Bank",
    bankAccount: "0088xxxxxx22",
    rating: 2.4,
    status: "BLACKLISTED",
    totalOrders: 3,
    totalValue: 14500,
    paymentTerms: "Net 30",
    preferredCurrency: "NGN",
    complianceScore: 35,
    onTimeDeliveryRate: 45,
    qualityRating: 2.2,
    documents: [],
    tags: ["blacklisted"],
    notes: "BLACKLISTED — Multiple delivery failures and quality issues. Do not engage.",
    createdAt: "2024-04-10T09:00:00Z",
  },
  {
    id: "vnd_dangote_cement",
    organizationId: "org_apex",
    companyName: "Dangote Cement PLC",
    contactPerson: "Ahmed Hassan",
    email: "enterprise@dangote.com",
    phone: "+234 700 326 4268",
    address: "Dangote Industries, Ikoyi, Lagos",
    category: "Construction Materials",
    taxNumber: "TIN-DC-001001",
    bankName: "Multiple",
    bankAccount: "On file",
    rating: 4.9,
    status: "ACTIVE",
    isPreferred: true,
    totalOrders: 18,
    totalValue: 245000,
    paymentTerms: "Net 30",
    preferredCurrency: "NGN",
    complianceScore: 98,
    onTimeDeliveryRate: 97,
    qualityRating: 4.9,
    documents: [],
    tags: ["preferred", "construction", "cement", "enterprise"],
    notes: "Largest cement manufacturer in Africa. Strategic partner pricing.",
    createdAt: "2023-03-20T09:00:00Z",
  },
  {
    id: "vnd_jumia_business",
    organizationId: "org_apex",
    companyName: "Jumia Business",
    contactPerson: "Sandra Okwu",
    email: "business@jumia.com",
    phone: "+234 700 525 8624",
    address: "Jumia HQ, Yaba, Lagos",
    category: "Office Supplies",
    taxNumber: "TIN-JB-778200",
    bankName: "GTBank",
    bankAccount: "0188xxxxxx33",
    rating: 4.2,
    status: "ACTIVE",
    totalOrders: 22,
    totalValue: 38900,
    paymentTerms: "Net 30",
    preferredCurrency: "NGN",
    complianceScore: 84,
    onTimeDeliveryRate: 90,
    qualityRating: 4.1,
    documents: [],
    tags: ["office", "supplies"],
    notes: "Wide catalog of office and operational supplies.",
    createdAt: "2024-05-12T09:00:00Z",
  },
];

