// NextMav Procure — client bootstrap.
//
// Returns the organization's data shaped exactly like the interfaces in
// `src/lib/types.ts`, which is what all 33 views already consume.
//
// This is the bridge that lets the UI move from mock data to the database
// without redesigning a single view: the store keeps its shape, the views keep
// their selectors, and only the *source* of the data changes. Dates become ISO
// strings, JSON columns are parsed back into arrays, and relational children are
// nested the way the client types expect.
//
// Only data the caller is permitted to see is included — vendor bank details and
// integration credentials are projected out for roles that should not see them.

import { db } from "../db";
import { effectivePermissions } from "../permissions";
import { scoped, type ServiceContext } from "./context";
import { daysUntil, documentStatus } from "./vendor-service";
import { fulfilmentSummary } from "./po-service";

const iso = (d: Date | null | undefined): string | undefined => d?.toISOString();
const isoReq = (d: Date | null | undefined): string => (d ?? new Date()).toISOString();

function parseArray<T = string>(raw: string | null, fallback: T[] = []): T[] {
  if (!raw) return fallback;
  try {
    const v = JSON.parse(raw);
    return Array.isArray(v) ? (v as T[]) : fallback;
  } catch {
    return fallback;
  }
}

/**
 * Everything the shell needs on load.
 *
 * One round trip rather than thirty: the previous client had all of this in
 * memory from module scope, so a per-module fetch cascade would have made the
 * app visibly slower than the mock it replaces.
 */
export async function bootstrap(ctx: ServiceContext) {
  const tdb = scoped(ctx);
  const organizationId = ctx.principal.organizationId;

  const canSeeBankDetails = (await effectivePermissions(ctx.principal)).includes("vendors.edit");
  const canSeeAudit = (await effectivePermissions(ctx.principal)).includes("audit.view");

  const [
    organization,
    branches,
    departments,
    users,
    vendors,
    requests,
    rfqs,
    purchaseOrders,
    goodsReceipts,
    invoices,
    payments,
    contracts,
    assets,
    inventory,
    documents,
    budgets,
    workflows,
    templates,
    integrations,
    notifications,
    activities,
    auditLogs,
    supplierUsers,
    supplierActivities,
    notificationPreference,
    roles,
    savedViews,
  ] = await Promise.all([
    db.organization.findUnique({ where: { id: organizationId } }),
    tdb.branch.findMany({ orderBy: { name: "asc" } }),
    tdb.department.findMany({ orderBy: { name: "asc" } }),
    tdb.user.findMany({ orderBy: { createdAt: "asc" } }),
    tdb.vendor.findMany({
      include: {
        documents: { orderBy: { uploadedAt: "desc" } },
        contacts: { orderBy: [{ isPrimary: "desc" }, { name: "asc" }] },
        complianceRequirements: { orderBy: [{ isMandatory: "desc" }, { name: "asc" }] },
        categoryLinks: { include: { category: { select: { id: true, code: true, name: true } } } },
      },
      orderBy: { companyName: "asc" },
    }),
    tdb.purchaseRequest.findMany({
      include: {
        lineItems: { orderBy: { sortOrder: "asc" } },
        approvals: { orderBy: { sequence: "asc" } },
        comments: { orderBy: { createdAt: "asc" } },
        watchers: true,
      },
      orderBy: { createdAt: "desc" },
    }),
    tdb.rFQ.findMany({
      include: {
        lineItems: { orderBy: { sortOrder: "asc" } },
        invitedVendors: true,
        quotations: { include: { lineItems: true }, orderBy: { totalAmount: "asc" } },
      },
      orderBy: { createdAt: "desc" },
    }),
    tdb.purchaseOrder.findMany({
      include: {
        lineItems: { orderBy: { sortOrder: "asc" } },
        revisions: { orderBy: { version: "desc" } },
        invoices: { select: { id: true, invoiceNumber: true, status: true, totalAmount: true, paidAmount: true, balance: true, dueDate: true } },
        goodsReceipts: { include: { items: true } },
      },
      orderBy: { createdAt: "desc" },
    }),
    tdb.goodsReceipt.findMany({ include: { items: true }, orderBy: { receivedDate: "desc" } }),
    tdb.invoice.findMany({ include: { lineItems: true }, orderBy: { issueDate: "desc" } }),
    tdb.payment.findMany({ orderBy: { createdAt: "desc" } }),
    tdb.contract.findMany({ include: { versions: true, obligations: true }, orderBy: { endDate: "asc" } }),
    tdb.asset.findMany({
      include: { maintenanceRecords: true, transfers: true },
      orderBy: { createdAt: "desc" },
    }),
    tdb.inventoryItem.findMany({
      include: { movements: { orderBy: { createdAt: "desc" }, take: 50 } },
      orderBy: { name: "asc" },
    }),
    tdb.documentRecord.findMany({ include: { versions: true }, orderBy: { createdAt: "desc" } }),
    tdb.budget.findMany({ include: { categories: true, alerts: true }, orderBy: { fiscalYear: "desc" } }),
    tdb.approvalWorkflow.findMany({
      include: { stages: { orderBy: { sequence: "asc" } } },
      orderBy: { createdAt: "asc" },
    }),
    tdb.requestTemplate.findMany({ orderBy: { usageCount: "desc" } }),
    tdb.integration.findMany({ include: { logs: { orderBy: { createdAt: "desc" }, take: 20 } } }),
    tdb.notification.findMany({
      where: { userId: ctx.principal.userId },
      orderBy: { createdAt: "desc" },
      take: 200,
    }),
    tdb.activityLog.findMany({ orderBy: { createdAt: "desc" }, take: 300 }),
    canSeeAudit
      ? tdb.auditLogEntry.findMany({ orderBy: { createdAt: "desc" }, take: 300 })
      : Promise.resolve([]),
    tdb.supplierUser.findMany(),
    db.supplierActivity.findMany({
      where: { vendor: { organizationId } },
      orderBy: { createdAt: "desc" },
      take: 200,
    }),
    db.notificationPreference.findUnique({ where: { userId: ctx.principal.userId } }),
    tdb.role.findMany({
      include: { permissions: { select: { permission: true } } },
      orderBy: { rank: "desc" },
    }),
    tdb.savedView.findMany({
      where: { OR: [{ userId: ctx.principal.userId }, { isShared: true }] },
    }),
  ]);

  // Cumulative received quantities per PO line, so the client can show the
  // ordered/received/invoiced picture without a second round trip.
  const poFulfilment: Record<string, ReturnType<typeof fulfilmentSummary>> = {};
  for (const po of purchaseOrders) {
    poFulfilment[po.id] = fulfilmentSummary(po as Parameters<typeof fulfilmentSummary>[0]);
  }

  return {
    permissions: await effectivePermissions(ctx.principal),
    currentUserId: ctx.principal.userId,

    organization: organization && {
      id: organization.id,
      name: organization.name,
      legalName: organization.legalName ?? undefined,
      industry: organization.industry ?? undefined,
      country: organization.country ?? undefined,
      currency: organization.currency,
      taxId: organization.taxId ?? undefined,
      plan: "ENTERPRISE",
      branding: { primaryColor: organization.brandPrimaryColor ?? undefined },
      createdAt: isoReq(organization.createdAt),
    },

    branches: branches.map((b) => ({
      id: b.id,
      organizationId: b.organizationId,
      name: b.name,
      address: b.address ?? "",
      city: b.city ?? "",
      country: b.country ?? "",
    })),

    departments: departments.map((d) => ({
      id: d.id,
      organizationId: d.organizationId,
      branchId: d.branchId ?? undefined,
      name: d.name,
    })),

    users: users.map((u) => ({
      id: u.id,
      organizationId: u.organizationId,
      branchId: u.branchId ?? undefined,
      departmentId: u.departmentId ?? undefined,
      email: u.email,
      name: u.name,
      role: u.role,
      jobTitle: u.jobTitle ?? "",
      phone: u.phone ?? undefined,
      avatarColor: u.avatarColor,
      initials: u.initials,
      status: u.status,
      lastLoginAt: iso(u.lastLoginAt),
      mfaEnabled: u.mfaEnabled,
      customPermissions: parseArray(u.customPermissions),
      createdAt: isoReq(u.createdAt),
    })),

    // The directory and the vendor profile read from /api/vendors, which pages and
    // filters in the database. This projection stays because thirty other screens
    // — contracts, invoices, RFQ invitations — need a vendor name for an id
    // without a round trip each.
    vendors: vendors.map((v) => ({
      id: v.id,
      organizationId: v.organizationId,
      companyName: v.companyName,
      legalName: v.legalName ?? undefined,
      tradingName: v.tradingName ?? undefined,
      vendorType: v.vendorType,
      description: v.description ?? undefined,
      contactPerson: v.contactPerson ?? "",
      email: v.email ?? "",
      phone: v.phone ?? "",
      address: v.address ?? "",
      city: v.city ?? undefined,
      stateRegion: v.stateRegion ?? undefined,
      postalCode: v.postalCode ?? undefined,
      country: v.country ?? undefined,
      category: v.category ?? "",
      taxNumber: v.taxNumber ?? "",
      registrationNumber: v.registrationNumber ?? undefined,
      businessClassification: v.businessClassification ?? undefined,
      businessSize: v.businessSize ?? undefined,
      incorporatedOn: iso(v.incorporatedOn),
      website: v.website ?? undefined,
      code: v.code ?? undefined,
      leadTimeDays: v.leadTimeDays ?? undefined,
      minimumOrderValue: v.minimumOrderValue ?? undefined,
      // Banking details are only projected for roles that manage vendors.
      bankName: canSeeBankDetails ? (v.bankName ?? "") : "",
      bankAccount: canSeeBankDetails ? (v.bankAccount ?? "") : "",
      rating: v.rating,
      status: v.status,
      isPreferred: v.isPreferred,
      complianceState: v.complianceState,
      riskLevel: v.riskLevel,
      riskScore: v.riskScore ?? undefined,
      riskStatus: v.riskStatus,
      riskReviewedAt: iso(v.riskReviewedAt),
      riskNextReviewAt: iso(v.riskNextReviewAt),
      totalOrders: v.totalOrders,
      totalValue: v.totalValue,
      paymentTerms: v.paymentTerms,
      preferredCurrency: v.preferredCurrency,
      complianceScore: v.complianceScore,
      onTimeDeliveryRate: v.onTimeDeliveryRate,
      qualityRating: v.qualityRating,
      performanceUpdatedAt: iso(v.performanceUpdatedAt),
      onboardedAt: iso(v.onboardedAt),
      invitedAt: iso(v.invitedAt),
      onboardingStartedAt: iso(v.onboardingStartedAt),
      submittedForReviewAt: iso(v.submittedForReviewAt),
      approvedAt: iso(v.approvedAt),
      approvedById: v.approvedById ?? undefined,
      rejectedAt: iso(v.rejectedAt),
      rejectedReason: v.rejectedReason ?? undefined,
      activatedAt: iso(v.activatedAt),
      deactivatedAt: iso(v.deactivatedAt),
      deactivatedReason: v.deactivatedReason ?? undefined,
      archivedAt: iso(v.archivedAt),
      suspendedAt: iso(v.suspendedAt),
      suspendedReason: v.suspendedReason ?? undefined,
      blacklistedAt: iso(v.blacklistedAt),
      blacklistedReason: v.blacklistedReason ?? undefined,
      createdById: v.createdById ?? undefined,
      contacts: v.contacts.map((c) => ({
        id: c.id,
        vendorId: c.vendorId,
        name: c.name,
        email: c.email ?? undefined,
        phone: c.phone ?? undefined,
        jobTitle: c.jobTitle ?? undefined,
        department: c.department ?? undefined,
        type: c.type,
        isPrimary: c.isPrimary,
        isActive: c.isActive,
        notes: c.notes ?? undefined,
        createdAt: isoReq(c.createdAt),
      })),
      categories: v.categoryLinks.map((l) => ({
        id: l.id,
        vendorId: l.vendorId,
        categoryId: l.categoryId,
        categoryName: l.category.name,
        categoryCode: l.category.code,
        isPreferred: l.isPreferred,
      })),
      compliance: v.complianceRequirements.map((r) => ({
        id: r.id,
        vendorId: r.vendorId,
        type: r.type,
        name: r.name,
        description: r.description ?? undefined,
        status: r.status,
        isMandatory: r.isMandatory,
        documentId: r.documentId ?? undefined,
        expiresAt: iso(r.expiresAt),
        submittedAt: iso(r.submittedAt),
        reviewedAt: iso(r.reviewedAt),
        reviewedById: r.reviewedById ?? undefined,
        reviewNotes: r.reviewNotes ?? undefined,
        waivedById: r.waivedById ?? undefined,
        waivedReason: r.waivedReason ?? undefined,
        daysToExpiry: daysUntil(r.expiresAt) ?? undefined,
        createdAt: isoReq(r.createdAt),
      })),
      documents: v.documents.map((d) => ({
        id: d.id,
        vendorId: d.vendorId,
        type: d.type,
        name: d.name,
        fileName: d.name,
        fileSize: "—",
        documentNumber: d.documentNumber ?? undefined,
        issuedAt: iso(d.issuedAt),
        uploadedAt: isoReq(d.uploadedAt),
        expiresAt: iso(d.expiresAt),
        // Derived, not read from the column: expiry moves on its own with the
        // calendar, and a stored status goes stale the day after it is written.
        status: documentStatus(d),
        version: d.version,
        uploadedById: d.uploadedById ?? undefined,
        verifiedById: d.verifiedById ?? undefined,
        verifiedAt: iso(d.verifiedAt),
        rejectedReason: d.rejectedReason ?? undefined,
        notes: d.notes ?? undefined,
        daysToExpiry: daysUntil(d.expiresAt) ?? undefined,
      })),
      tags: parseArray(v.tags),
      notes: v.notes ?? "",
      createdAt: isoReq(v.createdAt),
    })),

    requests: requests.map((r) => ({
      id: r.id,
      organizationId: r.organizationId,
      requestNumber: r.requestNumber,
      title: r.title,
      departmentId: r.departmentId ?? undefined,
      requestedById: r.requestedById,
      status: r.status,
      priority: r.priority,
      category: r.category ?? "",
      tags: parseArray(r.tags),
      businessJustification: r.businessJustification ?? "",
      neededByDate: isoReq(r.neededByDate),
      totalEstimated: r.totalEstimated,
      currency: r.currency,
      attachments: [],
      workflowId: r.workflowId ?? undefined,
      lineItems: r.lineItems.map((li) => ({
        id: li.id,
        itemName: li.itemName,
        description: li.description ?? "",
        quantity: li.quantity,
        unit: li.unit,
        estimatedCost: li.estimatedCost,
        taxRate: li.taxRate,
      })),
      approvals: r.approvals.map((a) => ({
        id: a.id,
        requestId: a.requestId,
        stage: a.stage,
        sequence: a.sequence,
        approverId: a.approverId,
        approverRole: a.approverRole,
        decision: a.decision,
        comment: a.comment ?? undefined,
        delegatedTo: a.delegatedToId ?? undefined,
        decidedAt: iso(a.decidedAt),
        slaHours: a.slaHours,
        slaExpiresAt: isoReq(a.slaExpiresAt),
        isEscalated: a.isEscalated,
        createdAt: isoReq(a.createdAt),
      })),
      comments: r.comments.map((c) => ({
        id: c.id,
        entityType: c.entityType,
        entityId: c.entityId,
        authorId: c.authorId,
        content: c.content,
        mentions: parseArray(c.mentions),
        createdAt: isoReq(c.createdAt),
      })),
      watchers: r.watchers.map((w) => w.userId),
      submittedAt: iso(r.submittedAt),
      approvedAt: iso(r.approvedAt),
      orderedAt: iso(r.orderedAt),
      fulfilledAt: iso(r.fulfilledAt),
      // The UI reads completedAt; a request now completes when it closes.
      completedAt: iso(r.closedAt),
      closedAt: iso(r.closedAt),
      returnedAt: iso(r.returnedAt),
      returnReason: r.returnReason ?? undefined,
      rejectionReason: r.rejectionReason ?? undefined,
      createdAt: isoReq(r.createdAt),
      updatedAt: isoReq(r.updatedAt),
      version: r.version,
    })),

    rfqs: rfqs.map((r) => ({
      id: r.id,
      organizationId: r.organizationId,
      rfqNumber: r.rfqNumber,
      requestId: r.requestId ?? undefined,
      title: r.title,
      description: r.description ?? "",
      deadline: isoReq(r.deadline),
      status: r.status,
      invitedVendorIds: r.invitedVendors.map((iv) => iv.vendorId),
      invitations: r.invitedVendors.map((iv) => ({
        vendorId: iv.vendorId,
        status: iv.status,
        invitedAt: isoReq(iv.invitedAt),
      })),
      lineItems: r.lineItems.map((li) => ({
        id: li.id,
        itemName: li.itemName,
        description: li.description ?? "",
        quantity: li.quantity,
        unit: li.unit,
        estimatedCost: 0,
      })),
      quotations: r.quotations.map((q) => ({
        id: q.id,
        rfqId: q.rfqId,
        vendorId: q.vendorId,
        revision: q.revision,
        totalAmount: q.totalAmount,
        currency: q.currency,
        deliveryDays: q.deliveryDays,
        warranty: q.warranty ?? "",
        paymentTerms: q.paymentTerms ?? "",
        validUntil: isoReq(q.validUntil),
        notes: q.notes ?? "",
        status: q.status,
        evaluationScore: q.evaluationScore ?? undefined,
        lineItems: q.lineItems.map((ql) => ({
          id: ql.id,
          itemName: ql.itemName,
          description: ql.description ?? "",
          quantity: ql.quantity,
          unit: ql.unit,
          estimatedCost: ql.unitPrice,
        })),
        createdAt: isoReq(q.createdAt),
      })),
      selectedQuotationId: r.selectedQuotationId ?? undefined,
      remindersSent: r.remindersSent,
      createdAt: isoReq(r.createdAt),
    })),

    purchaseOrders: purchaseOrders.map((p) => ({
      id: p.id,
      organizationId: p.organizationId,
      poNumber: p.poNumber,
      requestId: p.requestId ?? undefined,
      rfqId: p.rfqId ?? undefined,
      quotationId: p.quotationId ?? undefined,
      vendorId: p.vendorId,
      status: p.status,
      subtotal: p.subtotal,
      taxAmount: p.taxAmount,
      discountAmount: p.discountAmount,
      totalAmount: p.totalAmount,
      currency: p.currency,
      taxRate: p.taxRate,
      issuedAt: isoReq(p.issuedAt ?? p.createdAt),
      expectedDelivery: isoReq(p.expectedDelivery),
      receivedAt: iso(p.receivedAt),
      notes: p.notes ?? undefined,
      termsAndConditions: p.termsAndConditions ?? "",
      lineItems: p.lineItems.map((li) => ({
        id: li.id,
        itemName: li.itemName,
        description: li.description ?? "",
        quantity: li.orderedQty,
        unit: li.unit,
        estimatedCost: li.unitPrice,
        taxRate: li.taxRate,
        orderedQty: li.orderedQty,
        receivedQty: li.receivedQty,
        rejectedQty: li.rejectedQty,
        invoicedQty: li.invoicedQty,
        outstandingQty: Math.max(0, li.orderedQty - li.receivedQty - li.rejectedQty),
      })),
      fulfilment: poFulfilment[p.id],
      version: p.version,
      revisions: p.revisions.map((rv) => ({
        version: rv.version,
        modifiedAt: isoReq(rv.modifiedAt),
        modifiedBy: rv.modifiedById,
        reason: rv.reason,
      })),
      attachments: [],
    })),

    goodsReceipts: goodsReceipts.map((g) => ({
      id: g.id,
      organizationId: g.organizationId,
      receiptNumber: g.receiptNumber,
      poId: g.purchaseOrderId,
      vendorId: g.vendorId,
      receivedById: g.receivedById,
      status: g.status,
      receivedDate: isoReq(g.receivedDate),
      location: g.location ?? undefined,
      deliveryNoteRef: g.deliveryNoteRef ?? undefined,
      postedAt: iso(g.postedAt),
      notes: g.notes ?? undefined,
      items: g.items.map((i) => ({
        id: i.id,
        lineItemId: i.poLineItemId,
        itemName: i.itemName,
        orderedQty: i.orderedQty,
        receivedQty: i.receivedQty,
        rejectedQty: i.rejectedQty,
        unit: i.unit,
        condition: i.condition,
        notes: i.notes ?? undefined,
      })),
      attachments: [],
      createdAt: isoReq(g.createdAt),
    })),

    invoices: invoices.map((i) => ({
      id: i.id,
      organizationId: i.organizationId,
      invoiceNumber: i.invoiceNumber,
      vendorInvoiceRef: i.vendorInvoiceRef ?? undefined,
      vendorId: i.vendorId,
      poId: i.purchaseOrderId ?? undefined,
      goodsReceiptId: i.goodsReceiptId ?? undefined,
      status: i.status,
      matchStatus: i.matchStatus,
      matchVariance: i.matchVariance ?? undefined,
      issueDate: isoReq(i.issueDate),
      dueDate: isoReq(i.dueDate),
      subtotal: i.subtotal,
      taxAmount: i.taxAmount,
      totalAmount: i.totalAmount,
      currency: i.currency,
      paidAmount: i.paidAmount,
      balance: i.balance,
      notes: i.notes ?? undefined,
      lineItems: i.lineItems.map((li) => ({
        id: li.id,
        itemName: li.itemName,
        description: li.description ?? "",
        quantity: li.quantity,
        unit: li.unit,
        estimatedCost: li.unitPrice,
      })),
      attachments: [],
      approvedById: i.approvedById ?? undefined,
      approvedAt: iso(i.approvedAt),
      createdAt: isoReq(i.createdAt),
    })),

    payments: payments.map((p) => ({
      id: p.id,
      organizationId: p.organizationId,
      paymentNumber: p.paymentNumber,
      invoiceId: p.invoiceId,
      vendorId: p.vendorId,
      amount: p.amount,
      currency: p.currency,
      method: p.method,
      status: p.status,
      paymentDate: isoReq(p.paymentDate ?? p.scheduledFor ?? p.createdAt),
      scheduledFor: iso(p.scheduledFor),
      reference: p.reference ?? undefined,
      notes: p.notes ?? undefined,
      approvedById: p.approvedById ?? undefined,
      approvedAt: iso(p.approvedAt),
      failureReason: p.failureReason ?? undefined,
      reconciledAt: iso(p.reconciledAt),
      processedById: p.processedById,
      createdAt: isoReq(p.createdAt),
    })),

    contracts: contracts.map((c) => ({
      id: c.id,
      organizationId: c.organizationId,
      contractNumber: c.contractNumber,
      title: c.title,
      vendorId: c.vendorId,
      status: c.status,
      startDate: isoReq(c.startDate),
      endDate: isoReq(c.endDate),
      value: c.value,
      currency: c.currency,
      autoRenew: c.autoRenew,
      renewalNoticeDays: c.renewalNoticeDays,
      slaTerms: c.slaTerms ?? undefined,
      description: c.description ?? undefined,
      tags: parseArray(c.tags),
      attachments: [],
      obligations: c.obligations.map((o) => ({
        id: o.id,
        description: o.description,
        dueDate: iso(o.dueDate),
        status: o.status,
      })),
      versions: c.versions.map((v) => ({
        version: v.version,
        modifiedAt: isoReq(v.modifiedAt),
        modifiedBy: v.modifiedById,
        reason: v.reason,
      })),
      createdAt: isoReq(c.createdAt),
      updatedAt: isoReq(c.updatedAt),
    })),

    assets: assets.map((a) => ({
      id: a.id,
      organizationId: a.organizationId,
      assetTag: a.assetTag,
      name: a.name,
      category: a.category,
      serialNumber: a.serialNumber ?? undefined,
      poId: a.purchaseOrderId ?? undefined,
      goodsReceiptId: a.goodsReceiptId ?? undefined,
      vendorId: a.vendorId ?? undefined,
      assignedToId: a.assignedToId ?? undefined,
      departmentId: a.departmentId ?? undefined,
      branchId: a.branchId ?? undefined,
      location: a.location ?? undefined,
      status: a.status,
      purchaseDate: isoReq(a.purchaseDate),
      purchaseValue: a.purchaseValue,
      currentValue: a.currentValue,
      currency: a.currency,
      warrantyExpiry: iso(a.warrantyExpiry),
      depreciationRate: a.depreciationRate,
      qrCode: a.qrCode ?? undefined,
      notes: a.notes ?? undefined,
      maintenanceHistory: a.maintenanceRecords.map((m) => ({
        id: m.id,
        date: isoReq(m.date),
        type: m.type,
        description: m.description,
        cost: m.cost,
        performedBy: m.performedBy ?? undefined,
      })),
      transfers: a.transfers.map((t) => ({
        id: t.id,
        date: isoReq(t.date),
        fromUserId: t.fromUserId ?? undefined,
        toUserId: t.toUserId ?? undefined,
        fromLocation: t.fromLocation ?? undefined,
        toLocation: t.toLocation ?? undefined,
        reason: t.reason,
      })),
      createdAt: isoReq(a.createdAt),
    })),

    inventory: inventory.map((i) => ({
      id: i.id,
      organizationId: i.organizationId,
      sku: i.sku,
      name: i.name,
      description: i.description ?? undefined,
      category: i.category ?? "",
      unit: i.unit,
      quantity: i.quantity,
      reorderLevel: i.reorderLevel,
      reorderQty: i.reorderQty,
      unitCost: i.unitCost,
      currency: i.currency,
      location: i.location ?? undefined,
      binLocation: i.binLocation ?? undefined,
      lastRestockDate: iso(i.lastRestockDate),
      supplierId: i.supplierId ?? undefined,
      movements: i.movements.map((m) => ({
        id: m.id,
        itemId: m.itemId,
        type: m.type,
        quantity: m.quantity,
        balanceAfter: m.balanceAfter,
        reference: m.reference ?? undefined,
        poId: m.purchaseOrderId ?? undefined,
        notes: m.notes ?? undefined,
        performedById: m.performedById,
        createdAt: isoReq(m.createdAt),
      })),
      createdAt: isoReq(i.createdAt),
      updatedAt: isoReq(i.updatedAt),
    })),

    documents: documents.map((d) => ({
      id: d.id,
      organizationId: d.organizationId,
      name: d.name,
      category: d.category,
      mimeType: "application/octet-stream",
      fileSize: d.versions[d.versions.length - 1]?.sizeLabel ?? "—",
      uploadedById: d.uploadedById,
      tags: parseArray(d.tags),
      linkedEntityType: d.linkedEntityType ?? undefined,
      linkedEntityId: d.linkedEntityId ?? undefined,
      versions: d.versions.map((v) => ({
        version: v.version,
        uploadedAt: isoReq(v.uploadedAt),
        uploadedBy: v.uploadedById,
        size: v.sizeLabel ?? "—",
      })),
      currentVersion: d.currentVersion,
      description: d.description ?? undefined,
      createdAt: isoReq(d.createdAt),
      updatedAt: isoReq(d.updatedAt),
    })),

    budgets: budgets.map((b) => ({
      id: b.id,
      organizationId: b.organizationId,
      departmentId: b.departmentId,
      fiscalYear: b.fiscalYear,
      fiscalQuarter: b.fiscalQuarter ?? undefined,
      totalAmount: b.totalAmount,
      spentAmount: b.spentAmount,
      committedAmount: b.committedAmount,
      reservedAmount: b.reservedAmount,
      remainingAmount: b.remainingAmount,
      enforceHardLimit: b.enforceHardLimit,
      categories: b.categories.map((c) => ({
        name: c.name,
        allocated: c.allocated,
        spent: c.spent,
      })),
      alerts: b.alerts.map((a) => ({
        threshold: a.threshold,
        triggered: a.triggered,
        triggeredAt: iso(a.triggeredAt),
      })),
      status: b.status,
      createdAt: isoReq(b.createdAt),
    })),

    workflows: workflows.map((w) => ({
      id: w.id,
      organizationId: w.organizationId,
      name: w.name,
      description: w.description ?? "",
      isActive: w.isActive,
      thresholdMin: w.thresholdMin ?? undefined,
      thresholdMax: w.thresholdMax ?? undefined,
      priorityFilter: parseArray(w.priorityFilter),
      stages: w.stages.map((s) => ({
        id: s.id,
        name: s.name,
        stage: s.stage,
        approverRole: s.approverRole,
        sequence: s.sequence,
        slaHours: s.slaHours,
        escalationRole: s.escalationRole ?? undefined,
        allowDelegation: s.allowDelegation,
        isParallel: s.isParallel,
      })),
      createdAt: isoReq(w.createdAt),
    })),

    templates: templates.map((t) => ({
      id: t.id,
      organizationId: t.organizationId,
      name: t.name,
      description: t.description ?? "",
      category: t.category ?? "",
      departmentId: t.departmentId ?? undefined,
      priority: t.priority,
      defaultLineItems: parseArray<Record<string, unknown>>(t.defaultLineItems),
      defaultJustification: t.defaultJustification ?? "",
      usageCount: t.usageCount,
      createdBy: t.createdById,
      createdAt: isoReq(t.createdAt),
    })),

    integrations: integrations.map((i) => ({
      id: i.id,
      organizationId: i.organizationId,
      type: i.type,
      name: i.name,
      status: i.status,
      configuredBy: i.configuredById ?? "",
      configuredAt: isoReq(i.configuredAt),
      lastSyncAt: iso(i.lastSyncAt),
      lastSyncStatus: i.lastSyncStatus ?? undefined,
      lastError: i.lastError ?? undefined,
      // Only which credential keys are set, never their values.
      config: JSON.parse(i.publicConfig ?? "{}"),
      hasCredentials: i.encryptedConfig !== null,
      enabledEvents: parseArray(i.enabledEvents),
      syncFrequency: i.syncFrequency,
      healthStatus: i.healthStatus,
      logs: i.logs.map((l) => ({
        id: l.id,
        integrationId: l.integrationId,
        timestamp: isoReq(l.createdAt),
        event: l.event,
        status: l.status,
        message: l.message ?? "",
        duration: l.durationMs ?? undefined,
      })),
    })),

    notifications: notifications.map((n) => ({
      id: n.id,
      organizationId: n.organizationId,
      userId: n.userId,
      title: n.title,
      message: n.message,
      type: n.type,
      read: n.read,
      link: n.link ?? undefined,
      entityId: n.entityId ?? undefined,
      entityType: n.entityType ?? undefined,
      createdAt: isoReq(n.createdAt),
    })),

    activities: activities.map((a) => ({
      id: a.id,
      organizationId: a.organizationId,
      userId: a.userId ?? undefined,
      requestId: a.requestId ?? undefined,
      purchaseOrderId: a.purchaseOrderId ?? undefined,
      rfqId: a.rfqId ?? undefined,
      vendorId: a.vendorId ?? undefined,
      eventType: a.eventType,
      description: a.description,
      severity: a.severity,
      ipAddress: a.ipAddress ?? undefined,
      userAgent: a.userAgent ?? undefined,
      createdAt: isoReq(a.createdAt),
    })),

    auditLogs: auditLogs.map((a) => ({
      id: a.id,
      organizationId: a.organizationId,
      userId: a.userId ?? "",
      action: a.action,
      resource: a.resource,
      resourceId: a.resourceId ?? undefined,
      // jsonb columns: already objects, not strings waiting to be parsed.
      before: a.before ?? undefined,
      after: a.after ?? undefined,
      changedFields: a.changedFields,
      ipAddress: a.ipAddress ?? "",
      userAgent: a.userAgent ?? "",
      timestamp: isoReq(a.createdAt),
    })),

    supplierPortalUsers: supplierUsers.map((s) => ({
      id: s.id,
      vendorId: s.vendorId,
      email: s.email,
      contactName: s.contactName,
      accessStatus: s.accessStatus,
      lastLoginAt: iso(s.lastLoginAt),
      createdAt: isoReq(s.createdAt),
    })),

    supplierActivities: supplierActivities.map((s) => ({
      id: s.id,
      vendorId: s.vendorId,
      type: s.type,
      description: s.description,
      referenceId: s.referenceId ?? undefined,
      createdAt: isoReq(s.createdAt),
    })),

    notificationPreference: notificationPreference
      ? {
          userId: notificationPreference.userId,
          channels: {
            inApp: notificationPreference.channelInApp,
            email: notificationPreference.channelEmail,
            push: notificationPreference.channelPush,
            slack: notificationPreference.channelSlack,
            teams: notificationPreference.channelTeams,
            whatsapp: notificationPreference.channelWhatsapp,
            sms: notificationPreference.channelSms,
          },
          categories: {
            approvals: notificationPreference.catApprovals,
            requests: notificationPreference.catRequests,
            rfqs: notificationPreference.catRfqs,
            purchaseOrders: notificationPreference.catPurchaseOrders,
            budgetAlerts: notificationPreference.catBudgetAlerts,
            slaWarnings: notificationPreference.catSlaWarnings,
            mentions: notificationPreference.catMentions,
            weeklyDigest: notificationPreference.catWeeklyDigest,
          },
          quietHoursStart: notificationPreference.quietHoursStart ?? undefined,
          quietHoursEnd: notificationPreference.quietHoursEnd ?? undefined,
        }
      : null,

    // The organization's configured roles, sent as data. The roles screen renders
    // these rather than a hardcoded list, so a role an administrator invents shows
    // up without a release.
    roles: roles.map((r) => ({
      id: r.id,
      key: r.key,
      name: r.name,
      description: r.description ?? undefined,
      rank: r.rank,
      isSystem: r.isSystem,
      isActive: r.isActive,
      legacyRole: r.legacyRole ?? undefined,
      permissions: r.permissions.map((p) => p.permission),
    })),

    // Kept for the roles screen, which is keyed on the legacy enum: the permission
    // set each built-in role currently grants in this organization.
    roleOverrides: Object.fromEntries(
      roles
        .filter((r) => r.legacyRole)
        .map((r) => [r.legacyRole as string, r.permissions.map((p) => p.permission)])
    ),

    savedViews: savedViews.map((s) => ({
      id: s.id,
      organizationId: s.organizationId,
      userId: s.userId,
      name: s.name,
      entityType: s.entityType,
      filters: JSON.parse(s.filters),
      isShared: s.isShared,
      createdAt: isoReq(s.createdAt),
    })),
  };
}
