// Regenerates src/server/decimal-fields.ts from the Prisma schema.
//
// Money and quantity columns are `numeric` in Postgres so that sums are exact.
// Prisma surfaces those as Decimal objects, which would ripple a decimal type
// through every service and every view. This generates the result extension that
// converts them back to `number` on read — at the client boundary, once, with
// types that match the runtime value.
//
//   npm run db:generate   (runs automatically)
import fs from "node:fs";

const src = fs.readFileSync("prisma/schema.prisma", "utf8");
const models = [];
let cur = null;
for (const line of src.split("\n")) {
  const m = /^model (\w+) \{/.exec(line);
  if (m) { cur = { name: m[1], fields: [] }; continue; }
  if (line === "}" && cur) { if (cur.fields.length) models.push(cur); cur = null; continue; }
  if (!cur) continue;
  const f = /^\s+(\w+)\s+Decimal(\??)/.exec(line);
  if (f) cur.fields.push({ name: f[1], optional: f[2] === "?" });
}

const camel = (s) => s[0].toLowerCase() + s.slice(1);
const body = models
  .map((m) => {
    const fields = m.fields
      .map((f) => {
        const expr = f.optional
          ? `r.${f.name} === null || r.${f.name} === undefined ? null : Number(r.${f.name})`
          : `Number(r.${f.name})`;
        return `    ${f.name}: {\n      needs: { ${f.name}: true },\n      compute: (r: { ${f.name}: Prisma.Decimal${f.optional ? " | null" : ""} }) => ${expr},\n    },`;
      })
      .join("\n");
    return `  ${camel(m.name)}: {\n${fields}\n  },`;
  })
  .join("\n");

const out = `// GENERATED by scripts/codegen/decimal-map.mjs — do not edit by hand.
//
// Money and quantity columns are Postgres \`numeric\`, so aggregation is exact and
// no rounding drift accumulates in the ledger. Prisma returns those as Decimal
// objects. This extension converts them to \`number\` on every read — including
// nested \`include\`s and reads inside transactions — so services and views work
// with plain numbers and the TypeScript types match what is actually there.
//
// Writes are unaffected: Prisma accepts a number for a Decimal column and the
// database rounds it to the column scale.
//
// Aggregates (\`_sum\`, \`_avg\`) are deliberately NOT covered — they still return
// Decimal, and the compiler will point at every call site that must convert.

import type { Prisma } from "@prisma/client";

export const decimalAsNumber = {
  name: "decimal-as-number",
  result: {
${body}
  },
} as const;
`;

fs.writeFileSync("src/server/decimal-fields.ts", out);
console.log(`decimal map: ${models.length} models, ${models.reduce((n, m) => n + m.fields.length, 0)} fields`);
